$axure.loadCurrentPage({
  "url":"需求.html",
  "generationDate":new Date(1442542995112.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2b2c9274863e463e9569685c22266b8f",
    "type":"Axure:Page",
    "name":"需求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da5b148ca1554883900718d51bb95ac9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-93,
              "y":0},
            "size":{
              "width":1413,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a252f926443448829c187bde0797e951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-93,
                  "y":0},
                "size":{
                  "width":1413,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u0.png"}},
{
          "id":"692452d76c494ecc9585d77b649b2fad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":10},
            "size":{
              "width":440,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f7de47647742ccad256b3e28cb193d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":10},
                "size":{
                  "width":440,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u2.png"}},
{
          "id":"5b648c9eeef742d78b8b8223861a24cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":21},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fde3169e34834a679205e5d5b95859e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":21},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39a66a1f19624d73943a06c600115ff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":79},
            "size":{
              "width":1140,
              "height":121},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e1e35605cf54b9e9e74961165d979ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":79},
                "size":{
                  "width":1140,
                  "height":121},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u6.png"}},
{
          "id":"47386c658e2440c1a0432bf7aea3079c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"230eded61aad49b9ad3ea053ccd3017d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u8.png"}},
{
          "id":"bed5ece0e5c2451fb2a53408624c32cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":48,
              "y":94},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deb8d245dbbd4fad874c7094ea063e4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":48,
                  "y":94},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b9cbfb1f17742debe41aa482f1cf14b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":94},
            "size":{
              "width":69,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece6e2a2e5674770b9463dbe857c9094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":94},
                "size":{
                  "width":69,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8328633eebc2493ca09f34707624b523",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":119},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9be2ab24583e478382d4363cac6d15b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":119},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u8.png"}},
{
          "id":"11d9776af8d744a8ab9d4ee0e43533dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":48,
              "y":123},
            "size":{
              "width":58,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6fe0787b7ae4ffdb47fbd2e0f33cb92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":48,
                  "y":123},
                "size":{
                  "width":58,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5abfb56753014e188304961fe6e7abcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":123},
            "size":{
              "width":317,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a2e6fa1a1844be790597f177ad21bdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":123},
                "size":{
                  "width":317,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee971dcb0f424fc59467dc4f1acec262",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":149},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e968e8eddc854f3b86c43ff988af1a4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":149},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u8.png"}},
{
          "id":"09bdc373edcd48419e3e2c6d9692b397",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":48,
              "y":153},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43b744b731f14177bf6e486771ac4ff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":48,
                  "y":153},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f92514b77c3348efa135f7d1a0f638eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":153},
            "size":{
              "width":307,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8470c19cebfe46d8901ff59efe52ed62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":153},
                "size":{
                  "width":307,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd3965e7a1fa4773bc6db46e2934e6e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":210},
            "size":{
              "width":752,
              "height":626}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f65210e71384a76af2bf71c1b47aba2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":210},
                "size":{
                  "width":752,
                  "height":626}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u26.png"}},
{
          "id":"67e7c0333cff4d66bf909cfd4fd2f8df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":884,
              "y":210},
            "size":{
              "width":266,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b78def39154f339c7b33f931eca654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":884,
                  "y":210},
                "size":{
                  "width":266,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u28.png"}},
{
          "id":"21b483c27a31446195a70120bc4e77e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":990,
              "y":220},
            "size":{
              "width":130,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c84f5e35e7946ebbbaaeee35e331549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":990,
                  "y":220},
                "size":{
                  "width":130,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u30.png"}},
{
          "id":"de17ef2b318a43469e257f3fc4536b6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":997,
              "y":223},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7c814286373499fa4ba359b1d1fd34b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":997,
                  "y":223},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bacf68996d94de19364fbca2c3f7269",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":893,
              "y":260},
            "size":{
              "width":249,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f181c8aef7b4601994ee081ebca6bc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":893,
                  "y":260},
                "size":{
                  "width":249,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "da5b148ca1554883900718d51bb95ac9":{
      "scriptId":"u0"},
    "a252f926443448829c187bde0797e951":{
      "scriptId":"u1"},
    "692452d76c494ecc9585d77b649b2fad":{
      "scriptId":"u2"},
    "92f7de47647742ccad256b3e28cb193d":{
      "scriptId":"u3"},
    "5b648c9eeef742d78b8b8223861a24cd":{
      "scriptId":"u4"},
    "fde3169e34834a679205e5d5b95859e9":{
      "scriptId":"u5"},
    "39a66a1f19624d73943a06c600115ff4":{
      "scriptId":"u6"},
    "0e1e35605cf54b9e9e74961165d979ae":{
      "scriptId":"u7"},
    "47386c658e2440c1a0432bf7aea3079c":{
      "scriptId":"u8"},
    "230eded61aad49b9ad3ea053ccd3017d":{
      "scriptId":"u9"},
    "bed5ece0e5c2451fb2a53408624c32cd":{
      "scriptId":"u10"},
    "deb8d245dbbd4fad874c7094ea063e4d":{
      "scriptId":"u11"},
    "5b9cbfb1f17742debe41aa482f1cf14b":{
      "scriptId":"u12"},
    "ece6e2a2e5674770b9463dbe857c9094":{
      "scriptId":"u13"},
    "8328633eebc2493ca09f34707624b523":{
      "scriptId":"u14"},
    "9be2ab24583e478382d4363cac6d15b6":{
      "scriptId":"u15"},
    "11d9776af8d744a8ab9d4ee0e43533dc":{
      "scriptId":"u16"},
    "d6fe0787b7ae4ffdb47fbd2e0f33cb92":{
      "scriptId":"u17"},
    "5abfb56753014e188304961fe6e7abcc":{
      "scriptId":"u18"},
    "3a2e6fa1a1844be790597f177ad21bdd":{
      "scriptId":"u19"},
    "ee971dcb0f424fc59467dc4f1acec262":{
      "scriptId":"u20"},
    "e968e8eddc854f3b86c43ff988af1a4d":{
      "scriptId":"u21"},
    "09bdc373edcd48419e3e2c6d9692b397":{
      "scriptId":"u22"},
    "43b744b731f14177bf6e486771ac4ff1":{
      "scriptId":"u23"},
    "f92514b77c3348efa135f7d1a0f638eb":{
      "scriptId":"u24"},
    "8470c19cebfe46d8901ff59efe52ed62":{
      "scriptId":"u25"},
    "fd3965e7a1fa4773bc6db46e2934e6e0":{
      "scriptId":"u26"},
    "8f65210e71384a76af2bf71c1b47aba2":{
      "scriptId":"u27"},
    "67e7c0333cff4d66bf909cfd4fd2f8df":{
      "scriptId":"u28"},
    "12b78def39154f339c7b33f931eca654":{
      "scriptId":"u29"},
    "21b483c27a31446195a70120bc4e77e2":{
      "scriptId":"u30"},
    "3c84f5e35e7946ebbbaaeee35e331549":{
      "scriptId":"u31"},
    "de17ef2b318a43469e257f3fc4536b6f":{
      "scriptId":"u32"},
    "c7c814286373499fa4ba359b1d1fd34b":{
      "scriptId":"u33"},
    "1bacf68996d94de19364fbca2c3f7269":{
      "scriptId":"u34"},
    "3f181c8aef7b4601994ee081ebca6bc0":{
      "scriptId":"u35"}}});