$axure.loadCurrentPage({
  "url":"我的任务_1.html",
  "generationDate":new Date(1442543005259.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17974ad6b87e40df907607a0c23e3499",
    "type":"Axure:Page",
    "name":"我的任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2eb62bae200242bbb31056cb2b246609",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e9d6738654430aa4339def7b9836bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"4b02ef790f2142ea88a80ae38118b079",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":120},
            "size":{
              "width":173,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"173474bfc24347ab85d9745f2111ce1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":120},
                "size":{
                  "width":173,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u35.png"}},
{
          "id":"b1879a5c7524498191d98512da0545b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"350f4488421b4cf79b132cdd1e76c96b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u37.png"}},
{
          "id":"e250745153e4415eb37ffbdb892367c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":59,
              "y":150},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9433a13a30943b9bb29857073d80ee5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":59,
                  "y":150},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0a04c596d7c47c8a0481852aa4cfc1b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":268},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"c72fb85eb95144689d42fff4b370c1e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":278},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78be9e860770411c83b6da09c49f237a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":278},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0023b58d28b940e382509dd0cfad2361",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":56,
              "y":306},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11a51e2270c540a2a4aa2dfa47039d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":306},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0e81e6ccb2a418b945da4ad00980000",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":335},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f7bfca9668b4a4191c91d373b547bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":335},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f162a457ed5e4494aeca58e2d3eab36c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":364},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff7578a68f2470dbd2b5b97989fe90a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":364},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31a8f9acc608411185a15e11c2f3b9ec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":393},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"4c7ff926555b41fcb11ca95b2c238d13",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":411},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b833f2b88d34d338e6cdf208b7e6543",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":411},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9dd0c56d40d48008167b0544ebf760a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":207},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ada492f3b4e4f36b75cbd0c277a101f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":207},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c34a3aa2c1c24eef82d7e488a4639254",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":440},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36407d996f7648fd807964306e4ec55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":440},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9650668494f44f9fab70f732a3c7b882",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":178},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b9f69d0aa8b413c9ca1da80e8a63dc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":178},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b60f12132174c0ca44a98df02d6c956",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":554},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"a02ac55b460c4458a5908f78c14f76ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":467},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a0cf50744cc4327944da75d9a92b170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":467},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"228e70363fd44bedb88200404d09c93d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":527},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12614e833ff940f995147d63b67c0900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":527},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3eefcba35194d76ba00f51ceb7fe4cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":569},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b14b550baf214bfaae5168b2bfd7b0bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":569},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6d172662af74e0b88c228edc91ee369",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":56,
              "y":597},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c89b7818c46456bb0d73b458ddddfeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":597},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a22fb25c0594357ba49d21b2be828e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":58,
              "y":626},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c662bf183e174f62ab7b078ad72af613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":626},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f55a3e32587b4b85a32629a00b96e617",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":58,
              "y":655},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a018e25d724465a93b3238bd53f75ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":655},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62dccfb81c4743c1a04878c880c65765",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":684},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df62fca743954c00a2852d71c03cd181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":684},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92780aecc1c744dcad3abbef02d7b2e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8e18170595455dabf6d8a8d12c96e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d1d177a260e64d55929fc45b9880ccdc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"22f143f58a2d4a3cadf0dd34b114f759",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":496},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77168d9461548e7b7ed73f7e8cc9438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":496},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8cd3e121ebfa4efa9bb3a74cd10f6060",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca5ee8c4db5f42dd82c3abfa27c80623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"459c38f2dcb149329f9aef1be60e1f02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":236},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd7ea57fa494ef9b6d3c640f6b3bd95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":236},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7818c10237ee4e27af282af28c1cc8d0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":332},
            "size":{
              "width":783,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的账户/u35_line.png"}},
{
          "id":"b318cce8107b440cbee4497bb463feb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":508,
              "y":146},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"509b93e4f72f4ee197fb343becf5ad33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":508,
                  "y":146},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"009054c33a12427fa09fc376a279cc41",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":589,
              "y":143},
            "size":{
              "width":121,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9dc5f8c03698444c8d6accab295bd067",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":148},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caa1ad875d104d54bba3a3c7a6afd78d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":148},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04b57c7adbca4f038b3356625af1f76d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":132},
            "size":{
              "width":202,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c01c4a40544435faa87fdb0c4e6d0ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":132},
                "size":{
                  "width":202,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u13.png"}},
{
          "id":"71186fcdf8204bbb968d1e75fca4ae01",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":143},
            "size":{
              "width":185,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"12aec1e54bf445118602e3577c7aa168",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":913,
              "y":143},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"766e965e0e7a4d508e718436857ce666",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":196},
            "size":{
              "width":783,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u17_line.png"}},
{
          "id":"3b1c1c8e5d6941e98d953e25285944f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":925,
              "y":478},
            "size":{
              "width":103,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90245cf417fe4d87b9711adf3e38a210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":925,
                  "y":478},
                "size":{
                  "width":103,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u18.png"}},
{
          "id":"7fb15e4f61564e418d026c81587371f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":460,
              "y":527},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"594e34c5c0d04db6a5b6a423aa41e17e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":527},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fdb735595b044e7ae8e6b0cccd66d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":479},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"227ee16b7abf44d0aafd93639cf1a269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":479},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e8aed571594643d7bfc4b01c7bd1a49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":950,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9ae05c35ec14d389aa98c0c087bea2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4fe23b5dda024a359a6856d4ab0c3a17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":951,
              "y":250},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63fdb03ae8ec4e87b32db107a2669f52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":951,
                  "y":250},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dae15164ad948f6b722eef177d2462e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":212},
            "size":{
              "width":23,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afb4703ef4bc4f9382a4305e84eab0e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":212},
                "size":{
                  "width":23,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u23.png"}},
{
          "id":"f3c4f4c3f1d64e488fa9c9380ea4ea57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":215},
            "size":{
              "width":230,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"525aba29394c4a748acb01e557e52395",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":215},
                "size":{
                  "width":230,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c2d37dfc5d4559878c480db824d816",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":212},
            "size":{
              "width":94,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15d66881f07547ae864ab0176183f908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":212},
                "size":{
                  "width":94,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u90.png"}},
{
          "id":"9d19dac58f5f4784a350adfa51953062",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":241},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89469e5c6eb14d36b74a2e9e71f76ce0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":241},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"394549b64342446780f7007dbf82e3a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":237},
            "size":{
              "width":15,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bc7656538de427ea3f551b7f84bd2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":237},
                "size":{
                  "width":15,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u94.png"}},
{
          "id":"d252b3d6de9d43c29bb345b0e6eaf138",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":325,
              "y":241},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39d315bafcd0445bb2ff44d86208ce00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":241},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1eb7ebf0f00146408feb3f4e7f9d7c7a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":244},
            "size":{
              "width":18,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u98_line.png"}},
{
          "id":"4199feacb1764f93ab3fa2090351ae89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":241},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5175f54b7ffc404bbc62dbca6329a271",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":241},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f55063d424c421c99b59c5aa71189fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":285},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36bff5129d354f049c3797531becb40b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":285},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u101.png"}},
{
          "id":"1481aef22dc74c4b83db5ea0a913e6c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":263},
            "size":{
              "width":181,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd09e3fb65ed46f5be2992ff9cc498d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":263},
                "size":{
                  "width":181,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a86ad70385a640fbba3f39c9a721a28f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":288},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"571811b7765d4b9c9671a9b096040ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":288},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efa0416849c84c71bc1affa09ccfda2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":950,
              "y":364},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6bf9786d7364374af512e2ec429eaf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":364},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f703313d03454207b3aa6fb9ae3ad783",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":951,
              "y":390},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991f34897c8447058deca3d14dae0e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":951,
                  "y":390},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a1660648cf14d3d927e5f99e7a9f62b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":352},
            "size":{
              "width":23,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d376bc409b7f40529513fcf470a85d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":352},
                "size":{
                  "width":23,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u23.png"}},
{
          "id":"41895975d5ed403db456fffae321bd17",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":355},
            "size":{
              "width":230,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2ec9c7041044991b9696a314683cdb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":355},
                "size":{
                  "width":230,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5727cab537904c01898c558a35346871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":352},
            "size":{
              "width":94,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"034b3cd8cac64b3395f8d26accca044d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":352},
                "size":{
                  "width":94,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u90.png"}},
{
          "id":"528fe8dbedd84bd18162f17ec90eee34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":381},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4217011727344cc9c2472595394498a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":381},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e05df4a62cd04fb4b15ef8cb87272ae8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":377},
            "size":{
              "width":15,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57ca704eef0f4ab7aaace01038cd7a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":377},
                "size":{
                  "width":15,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u94.png"}},
{
          "id":"4a58be2d34d54f89aeb8acd76a5f0982",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":325,
              "y":381},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4564be140ee942c8bee7dcb8ff0fb16d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":381},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d45fe7bfc3c4777805bf0ccfa4cbc59",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":384},
            "size":{
              "width":18,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u98_line.png"}},
{
          "id":"9127e857524142eeae206c79e0a88222",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":381},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3b9c5560aa749f0b4c62be2a0ba92a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":381},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dee2702d2b8c457e9c3d53a7f7f535ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":425},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96d5d8c7e7049ea93cc9f5f62f2408e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":425},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u101.png"}},
{
          "id":"839294f90d5d44bb8519f4ddc9df16a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":403},
            "size":{
              "width":181,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1533243f5c5746478f9d01b681402e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":403},
                "size":{
                  "width":181,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"119dbf0c6d44427cb80bbf09fdb6c455",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":428},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3a1092184f4bd0afcd4755756e7b73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":428},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2eb62bae200242bbb31056cb2b246609":{
      "scriptId":"u0"},
    "56e9d6738654430aa4339def7b9836bb":{
      "scriptId":"u1"},
    "4b02ef790f2142ea88a80ae38118b079":{
      "scriptId":"u2"},
    "173474bfc24347ab85d9745f2111ce1f":{
      "scriptId":"u3"},
    "b1879a5c7524498191d98512da0545b1":{
      "scriptId":"u4"},
    "350f4488421b4cf79b132cdd1e76c96b":{
      "scriptId":"u5"},
    "e250745153e4415eb37ffbdb892367c1":{
      "scriptId":"u6"},
    "f9433a13a30943b9bb29857073d80ee5":{
      "scriptId":"u7"},
    "a0a04c596d7c47c8a0481852aa4cfc1b":{
      "scriptId":"u8"},
    "c72fb85eb95144689d42fff4b370c1e8":{
      "scriptId":"u9"},
    "78be9e860770411c83b6da09c49f237a":{
      "scriptId":"u10"},
    "0023b58d28b940e382509dd0cfad2361":{
      "scriptId":"u11"},
    "11a51e2270c540a2a4aa2dfa47039d5e":{
      "scriptId":"u12"},
    "a0e81e6ccb2a418b945da4ad00980000":{
      "scriptId":"u13"},
    "8f7bfca9668b4a4191c91d373b547bd8":{
      "scriptId":"u14"},
    "f162a457ed5e4494aeca58e2d3eab36c":{
      "scriptId":"u15"},
    "0ff7578a68f2470dbd2b5b97989fe90a":{
      "scriptId":"u16"},
    "31a8f9acc608411185a15e11c2f3b9ec":{
      "scriptId":"u17"},
    "4c7ff926555b41fcb11ca95b2c238d13":{
      "scriptId":"u18"},
    "8b833f2b88d34d338e6cdf208b7e6543":{
      "scriptId":"u19"},
    "b9dd0c56d40d48008167b0544ebf760a":{
      "scriptId":"u20"},
    "1ada492f3b4e4f36b75cbd0c277a101f":{
      "scriptId":"u21"},
    "c34a3aa2c1c24eef82d7e488a4639254":{
      "scriptId":"u22"},
    "36407d996f7648fd807964306e4ec55e":{
      "scriptId":"u23"},
    "9650668494f44f9fab70f732a3c7b882":{
      "scriptId":"u24"},
    "2b9f69d0aa8b413c9ca1da80e8a63dc4":{
      "scriptId":"u25"},
    "1b60f12132174c0ca44a98df02d6c956":{
      "scriptId":"u26"},
    "a02ac55b460c4458a5908f78c14f76ea":{
      "scriptId":"u27"},
    "8a0cf50744cc4327944da75d9a92b170":{
      "scriptId":"u28"},
    "228e70363fd44bedb88200404d09c93d":{
      "scriptId":"u29"},
    "12614e833ff940f995147d63b67c0900":{
      "scriptId":"u30"},
    "e3eefcba35194d76ba00f51ceb7fe4cf":{
      "scriptId":"u31"},
    "b14b550baf214bfaae5168b2bfd7b0bd":{
      "scriptId":"u32"},
    "c6d172662af74e0b88c228edc91ee369":{
      "scriptId":"u33"},
    "8c89b7818c46456bb0d73b458ddddfeb":{
      "scriptId":"u34"},
    "4a22fb25c0594357ba49d21b2be828e7":{
      "scriptId":"u35"},
    "c662bf183e174f62ab7b078ad72af613":{
      "scriptId":"u36"},
    "f55a3e32587b4b85a32629a00b96e617":{
      "scriptId":"u37"},
    "7a018e25d724465a93b3238bd53f75ea":{
      "scriptId":"u38"},
    "62dccfb81c4743c1a04878c880c65765":{
      "scriptId":"u39"},
    "df62fca743954c00a2852d71c03cd181":{
      "scriptId":"u40"},
    "92780aecc1c744dcad3abbef02d7b2e2":{
      "scriptId":"u41"},
    "dc8e18170595455dabf6d8a8d12c96e3":{
      "scriptId":"u42"},
    "d1d177a260e64d55929fc45b9880ccdc":{
      "scriptId":"u43"},
    "22f143f58a2d4a3cadf0dd34b114f759":{
      "scriptId":"u44"},
    "d77168d9461548e7b7ed73f7e8cc9438":{
      "scriptId":"u45"},
    "8cd3e121ebfa4efa9bb3a74cd10f6060":{
      "scriptId":"u46"},
    "ca5ee8c4db5f42dd82c3abfa27c80623":{
      "scriptId":"u47"},
    "459c38f2dcb149329f9aef1be60e1f02":{
      "scriptId":"u48"},
    "0fd7ea57fa494ef9b6d3c640f6b3bd95":{
      "scriptId":"u49"},
    "7818c10237ee4e27af282af28c1cc8d0":{
      "scriptId":"u50"},
    "b318cce8107b440cbee4497bb463feb8":{
      "scriptId":"u51"},
    "509b93e4f72f4ee197fb343becf5ad33":{
      "scriptId":"u52"},
    "009054c33a12427fa09fc376a279cc41":{
      "scriptId":"u53"},
    "9dc5f8c03698444c8d6accab295bd067":{
      "scriptId":"u54"},
    "caa1ad875d104d54bba3a3c7a6afd78d":{
      "scriptId":"u55"},
    "04b57c7adbca4f038b3356625af1f76d":{
      "scriptId":"u56"},
    "4c01c4a40544435faa87fdb0c4e6d0ec":{
      "scriptId":"u57"},
    "71186fcdf8204bbb968d1e75fca4ae01":{
      "scriptId":"u58"},
    "12aec1e54bf445118602e3577c7aa168":{
      "scriptId":"u59"},
    "766e965e0e7a4d508e718436857ce666":{
      "scriptId":"u60"},
    "3b1c1c8e5d6941e98d953e25285944f3":{
      "scriptId":"u61"},
    "90245cf417fe4d87b9711adf3e38a210":{
      "scriptId":"u62"},
    "7fb15e4f61564e418d026c81587371f4":{
      "scriptId":"u63"},
    "594e34c5c0d04db6a5b6a423aa41e17e":{
      "scriptId":"u64"},
    "7fdb735595b044e7ae8e6b0cccd66d51":{
      "scriptId":"u65"},
    "227ee16b7abf44d0aafd93639cf1a269":{
      "scriptId":"u66"},
    "e8aed571594643d7bfc4b01c7bd1a49d":{
      "scriptId":"u67"},
    "d9ae05c35ec14d389aa98c0c087bea2a":{
      "scriptId":"u68"},
    "4fe23b5dda024a359a6856d4ab0c3a17":{
      "scriptId":"u69"},
    "63fdb03ae8ec4e87b32db107a2669f52":{
      "scriptId":"u70"},
    "0dae15164ad948f6b722eef177d2462e":{
      "scriptId":"u71"},
    "afb4703ef4bc4f9382a4305e84eab0e8":{
      "scriptId":"u72"},
    "f3c4f4c3f1d64e488fa9c9380ea4ea57":{
      "scriptId":"u73"},
    "525aba29394c4a748acb01e557e52395":{
      "scriptId":"u74"},
    "08c2d37dfc5d4559878c480db824d816":{
      "scriptId":"u75"},
    "15d66881f07547ae864ab0176183f908":{
      "scriptId":"u76"},
    "9d19dac58f5f4784a350adfa51953062":{
      "scriptId":"u77"},
    "89469e5c6eb14d36b74a2e9e71f76ce0":{
      "scriptId":"u78"},
    "394549b64342446780f7007dbf82e3a3":{
      "scriptId":"u79"},
    "6bc7656538de427ea3f551b7f84bd2bb":{
      "scriptId":"u80"},
    "d252b3d6de9d43c29bb345b0e6eaf138":{
      "scriptId":"u81"},
    "39d315bafcd0445bb2ff44d86208ce00":{
      "scriptId":"u82"},
    "1eb7ebf0f00146408feb3f4e7f9d7c7a":{
      "scriptId":"u83"},
    "4199feacb1764f93ab3fa2090351ae89":{
      "scriptId":"u84"},
    "5175f54b7ffc404bbc62dbca6329a271":{
      "scriptId":"u85"},
    "1f55063d424c421c99b59c5aa71189fb":{
      "scriptId":"u86"},
    "36bff5129d354f049c3797531becb40b":{
      "scriptId":"u87"},
    "1481aef22dc74c4b83db5ea0a913e6c7":{
      "scriptId":"u88"},
    "dd09e3fb65ed46f5be2992ff9cc498d0":{
      "scriptId":"u89"},
    "a86ad70385a640fbba3f39c9a721a28f":{
      "scriptId":"u90"},
    "571811b7765d4b9c9671a9b096040ec8":{
      "scriptId":"u91"},
    "efa0416849c84c71bc1affa09ccfda2d":{
      "scriptId":"u92"},
    "b6bf9786d7364374af512e2ec429eaf3":{
      "scriptId":"u93"},
    "f703313d03454207b3aa6fb9ae3ad783":{
      "scriptId":"u94"},
    "991f34897c8447058deca3d14dae0e4f":{
      "scriptId":"u95"},
    "4a1660648cf14d3d927e5f99e7a9f62b":{
      "scriptId":"u96"},
    "d376bc409b7f40529513fcf470a85d07":{
      "scriptId":"u97"},
    "41895975d5ed403db456fffae321bd17":{
      "scriptId":"u98"},
    "e2ec9c7041044991b9696a314683cdb2":{
      "scriptId":"u99"},
    "5727cab537904c01898c558a35346871":{
      "scriptId":"u100"},
    "034b3cd8cac64b3395f8d26accca044d":{
      "scriptId":"u101"},
    "528fe8dbedd84bd18162f17ec90eee34":{
      "scriptId":"u102"},
    "a4217011727344cc9c2472595394498a":{
      "scriptId":"u103"},
    "e05df4a62cd04fb4b15ef8cb87272ae8":{
      "scriptId":"u104"},
    "57ca704eef0f4ab7aaace01038cd7a1c":{
      "scriptId":"u105"},
    "4a58be2d34d54f89aeb8acd76a5f0982":{
      "scriptId":"u106"},
    "4564be140ee942c8bee7dcb8ff0fb16d":{
      "scriptId":"u107"},
    "0d45fe7bfc3c4777805bf0ccfa4cbc59":{
      "scriptId":"u108"},
    "9127e857524142eeae206c79e0a88222":{
      "scriptId":"u109"},
    "d3b9c5560aa749f0b4c62be2a0ba92a2":{
      "scriptId":"u110"},
    "dee2702d2b8c457e9c3d53a7f7f535ca":{
      "scriptId":"u111"},
    "e96d5d8c7e7049ea93cc9f5f62f2408e":{
      "scriptId":"u112"},
    "839294f90d5d44bb8519f4ddc9df16a1":{
      "scriptId":"u113"},
    "1533243f5c5746478f9d01b681402e28":{
      "scriptId":"u114"},
    "119dbf0c6d44427cb80bbf09fdb6c455":{
      "scriptId":"u115"},
    "6d3a1092184f4bd0afcd4755756e7b73":{
      "scriptId":"u116"}}});