$axure.loadCurrentPage({
  "url":"需求详情页.html",
  "generationDate":new Date(1442542995261.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e1c1e822b9246f7adcedd73c0bff3b8",
    "type":"Axure:Page",
    "name":"需求详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c5c83184112145dc818171c24bb861ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":14},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00a6510678524c048ad31d5afb042209",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":14},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dff609679c2449dbaa6a509c42799225",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":6},
            "size":{
              "width":120,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fca5198b3a54ce282bf21e3f871381d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":6},
                "size":{
                  "width":120,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺详情页/u2.png"}},
{
          "id":"2dcc6cf3b0dd4eada93f11a9ce568795",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":17},
            "size":{
              "width":294,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124e0ed049364788b800502fb846a26c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":17},
                "size":{
                  "width":294,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"088fb7629cb64d75ba2bd613d3db19b9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":43},
            "size":{
              "width":1070,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商铺详情页/u6_line.png"}},
{
          "id":"ecacd5601b774254b4bab4661825905a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":63},
            "size":{
              "width":217,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"417c7868b2504dcd990ab2372e343366",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":63},
                "size":{
                  "width":217,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"542961017718435c951de6d06f4fbb47",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":85},
            "size":{
              "width":1060,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商铺详情页/u19_line.png"}},
{
          "id":"55247a5e19dc4dc99711eb4c2ca3abfd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":51,
              "y":153},
            "size":{
              "width":211,
              "height":133}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"222195794167403783dc47375e9bd2c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":51,
                  "y":153},
                "size":{
                  "width":211,
                  "height":133}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d651c8389111486d8c55e9bf5cee196e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":51,
              "y":294},
            "size":{
              "width":179,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2ec29a384c4764bd8c0797b1715ba9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":51,
                  "y":294},
                "size":{
                  "width":179,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺详情页/u34.png"}},
{
          "id":"3baef7f49c2a4488a950e2d7b8b9c5ba",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":384},
            "size":{
              "width":620,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商铺详情页/u36_line.png"}},
{
          "id":"1ffe917e425041da988ba8f1aa63fb9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":40,
              "y":362},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76d7ba6a297644f0a477cbe72e397c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":362},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45b620ff7ef840748152e4918d2bdbdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":404},
            "size":{
              "width":590,
              "height":227}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"565aa7c2e47f4de2a9820b19149ef7e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":404},
                "size":{
                  "width":590,
                  "height":227}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01488a11e9fc4dfc915079e104e38173",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":554},
            "size":{
              "width":1050,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5ff65f35d824f0c923ec7364bd88dcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":554},
                "size":{
                  "width":1050,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺详情页/u49.png"}},
{
          "id":"f2715e047ec84ae5acd42efa229b0e57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":51,
              "y":111},
            "size":{
              "width":442,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee230d3245cd4b7087c7436619a9b5e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":51,
                  "y":111},
                "size":{
                  "width":442,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c10215304699417daa3cd1471928950b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":814,
              "y":111},
            "size":{
              "width":266,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8815cea8b164c7db4eb10d110303285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":814,
                  "y":111},
                "size":{
                  "width":266,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u28.png"}},
{
          "id":"faa3b5bd46434d08abd0a991f2249eee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6633},
            "location":{
              "x":920,
              "y":121},
            "size":{
              "width":130,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22cc5e6c61194d8fa4af37bbc92832ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6633},
                "location":{
                  "x":920,
                  "y":121},
                "size":{
                  "width":130,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u30.png"}},
{
          "id":"22bd0d682e894ba0b8ad1eb96e66d406",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":927,
              "y":124},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c7daab8d8014b8d86ff5b1a8d814e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":927,
                  "y":124},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7fca12ebe0f4200a204d3402f3844d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":823,
              "y":161},
            "size":{
              "width":249,
              "height":209}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"175a400cca19428c97bfdfd48c1395d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":823,
                  "y":161},
                "size":{
                  "width":249,
                  "height":209}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/需求/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c5c83184112145dc818171c24bb861ba":{
      "scriptId":"u0"},
    "00a6510678524c048ad31d5afb042209":{
      "scriptId":"u1"},
    "dff609679c2449dbaa6a509c42799225":{
      "scriptId":"u2"},
    "3fca5198b3a54ce282bf21e3f871381d":{
      "scriptId":"u3"},
    "2dcc6cf3b0dd4eada93f11a9ce568795":{
      "scriptId":"u4"},
    "124e0ed049364788b800502fb846a26c":{
      "scriptId":"u5"},
    "088fb7629cb64d75ba2bd613d3db19b9":{
      "scriptId":"u6"},
    "ecacd5601b774254b4bab4661825905a":{
      "scriptId":"u7"},
    "417c7868b2504dcd990ab2372e343366":{
      "scriptId":"u8"},
    "542961017718435c951de6d06f4fbb47":{
      "scriptId":"u9"},
    "55247a5e19dc4dc99711eb4c2ca3abfd":{
      "scriptId":"u10"},
    "222195794167403783dc47375e9bd2c2":{
      "scriptId":"u11"},
    "d651c8389111486d8c55e9bf5cee196e":{
      "scriptId":"u12"},
    "1e2ec29a384c4764bd8c0797b1715ba9":{
      "scriptId":"u13"},
    "3baef7f49c2a4488a950e2d7b8b9c5ba":{
      "scriptId":"u14"},
    "1ffe917e425041da988ba8f1aa63fb9b":{
      "scriptId":"u15"},
    "76d7ba6a297644f0a477cbe72e397c09":{
      "scriptId":"u16"},
    "45b620ff7ef840748152e4918d2bdbdf":{
      "scriptId":"u17"},
    "565aa7c2e47f4de2a9820b19149ef7e2":{
      "scriptId":"u18"},
    "01488a11e9fc4dfc915079e104e38173":{
      "scriptId":"u19"},
    "e5ff65f35d824f0c923ec7364bd88dcf":{
      "scriptId":"u20"},
    "f2715e047ec84ae5acd42efa229b0e57":{
      "scriptId":"u21"},
    "ee230d3245cd4b7087c7436619a9b5e6":{
      "scriptId":"u22"},
    "c10215304699417daa3cd1471928950b":{
      "scriptId":"u23"},
    "f8815cea8b164c7db4eb10d110303285":{
      "scriptId":"u24"},
    "faa3b5bd46434d08abd0a991f2249eee":{
      "scriptId":"u25"},
    "22cc5e6c61194d8fa4af37bbc92832ad":{
      "scriptId":"u26"},
    "22bd0d682e894ba0b8ad1eb96e66d406":{
      "scriptId":"u27"},
    "9c7daab8d8014b8d86ff5b1a8d814e28":{
      "scriptId":"u28"},
    "e7fca12ebe0f4200a204d3402f3844d4":{
      "scriptId":"u29"},
    "175a400cca19428c97bfdfd48c1395d9":{
      "scriptId":"u30"}}});