
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ApplyBrand
{

    public int Id { get; set; }

    public int BrandId { get; set; }

    public string Phone { get; set; }

    public byte Status { get; set; }

    public int ApplyUser { get; set; }

    public string Contract { get; set; }

    public System.DateTime ApplyTime { get; set; }

    public Nullable<System.DateTime> AuditTime { get; set; }

    public string RejectReason { get; set; }



    public virtual ShopBrand ShopBrand { get; set; }

}

}
