
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class C_File
{

    public int Id { get; set; }

    public int FileType { get; set; }

    public string FileName { get; set; }

    public string FileName1 { get; set; }

    public string FileName2 { get; set; }

    public string FileName3 { get; set; }

    public string FileName4 { get; set; }

    public string FileName5 { get; set; }

}

}
