
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class C_Object
{

    public C_Object()
    {

        this.Subset = new HashSet<C_Object>();

    }


    public int Id { get; set; }

    public int Type { get; set; }

    public string Name { get; set; }

    public int ParentId { get; set; }

    public string ParentChain { get; set; }

    public string ChildrenSet { get; set; }

    public string Description { get; set; }

    public int Creater { get; set; }

    public System.DateTime CreateTime { get; set; }

    public int LastModifyUser { get; set; }

    public System.DateTime LastModifyTime { get; set; }

    public Nullable<int> Status { get; set; }

    public bool IsDelete { get; set; }

    public int Sort { get; set; }



    public virtual ICollection<C_Object> Subset { get; set; }

    public virtual C_Object Parent { get; set; }

    public virtual G_Name G_Name { get; set; }

    public virtual G_Goods G_Goods { get; set; }

}

}
