
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerLog
{

    public long id { get; set; }

    public int Customer { get; set; }

    public string ip { get; set; }

    public string logmsg { get; set; }

    public Nullable<System.DateTime> addtime { get; set; }

    public Nullable<int> ProjectId { get; set; }

    public Nullable<int> Targetsubject { get; set; }

    public string Modulid { get; set; }

    public string Equipment { get; set; }

    public Nullable<bool> ismanage { get; set; }

    public string url { get; set; }

}

}
