
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public Customer()
    {

        this.Companyid = 0;

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Password { get; set; }

    public string Mobile { get; set; }

    public string Address { get; set; }

    public Nullable<bool> Online { get; set; }

    public string LoginName { get; set; }

    public string Email { get; set; }

    public bool Property { get; set; }

    public Nullable<int> GroupId { get; set; }

    public int Companyid { get; set; }

    public Nullable<System.DateTime> registertime { get; set; }

    public string portrait { get; set; }



    public virtual OpenShop FkOpenShop { get; set; }

}

}
