
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerDiscipline
{

    public long Id { get; set; }

    public Nullable<int> Customerid { get; set; }

    public bool Property { get; set; }

    public Nullable<System.DateTime> Begintime { get; set; }

    public Nullable<System.DateTime> Endtime { get; set; }

    public Nullable<int> Disciplinetype { get; set; }

    public Nullable<System.DateTime> Disciplinetime { get; set; }

}

}
