
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Grouppurchase
{

    public Grouppurchase()
    {

        this.ApplyActivities = new HashSet<ApplyActivity>();

    }


    public int Id { get; set; }

    public int ShopProjectId { get; set; }

    public string Name { get; set; }

    public Nullable<int> Llimit { get; set; }

    public Nullable<System.DateTime> Begintime { get; set; }

    public Nullable<System.DateTime> Endtime { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<System.DateTime> Addtime { get; set; }

    public Nullable<System.DateTime> Lastupdate { get; set; }

    public Nullable<int> progress { get; set; }



    public virtual ICollection<ApplyActivity> ApplyActivities { get; set; }

    public virtual ShopProject ShopProject { get; set; }

}

}
