
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class M_Period
{

    public int Id { get; set; }

    public int Period { get; set; }

    public string Standard { get; set; }

    public decimal Price { get; set; }

    public Nullable<System.DateTime> StartTime { get; set; }

    public Nullable<System.DateTime> FirstApplyCheckTime { get; set; }

    public Nullable<System.DateTime> PassTime { get; set; }

    public Nullable<System.DateTime> PayStartTime { get; set; }

    public Nullable<System.DateTime> FinishTime { get; set; }

    public bool IsDelete { get; set; }

    public int MissionId { get; set; }

    public int Status { get; set; }

    public string FailedReasion { get; set; }



    public virtual M_Mission FkMission { get; set; }

}

}
