
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class O_CartGoods
{

    public int Id { get; set; }

    public int CartId { get; set; }

    public int GoodsId { get; set; }

    public decimal GoodsCount { get; set; }

    public decimal Price { get; set; }



    public virtual C_Object FKgoods { get; set; }

}

}
