
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class O_Cart
{

    public O_Cart()
    {

        this.FKCartGoods = new HashSet<O_CartGoods>();

        this.FKOrder = new HashSet<O_Order>();

    }


    public int Id { get; set; }

    public int Creater { get; set; }

    public System.DateTime CreateTime { get; set; }

    public int Flag { get; set; }



    public virtual ICollection<O_CartGoods> FKCartGoods { get; set; }

    public virtual ICollection<O_Order> FKOrder { get; set; }

}

}
