
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class O_Order
{

    public int OrderId { get; set; }

    public decimal TotalPrice { get; set; }

    public int Status { get; set; }

    public int Saler { get; set; }

    public int Buyer { get; set; }

    public System.DateTime OrderTime { get; set; }

    public Nullable<int> Method { get; set; }

    public string BuyerName { get; set; }

    public string BuyerMobile { get; set; }

    public string BuyerAddress { get; set; }

    public Nullable<int> ExpressCompany { get; set; }

    public string ExpressNumber { get; set; }

    public string SalerName { get; set; }

    public string SalerMobile { get; set; }

    public string SalerAddress { get; set; }

    public Nullable<System.DateTime> PaymentTime { get; set; }

    public Nullable<System.DateTime> ColseTime { get; set; }

    public bool IsDelete { get; set; }

    public int OrderType { get; set; }

    public int BusinessDataType { get; set; }

    public int BusinessDataId { get; set; }

    public string Title { get; set; }

    public string Remark { get; set; }

    public string DetailUrl { get; set; }

    public int CartId { get; set; }



    public virtual Customer FkBuyer { get; set; }

    public virtual Customer FkSaler { get; set; }

    public virtual O_Cart FKCart { get; set; }

}

}
