
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class OpenShopAttributeValues
{

    public int Id { get; set; }

    public int OpenShopId { get; set; }

    public int AttributesId { get; set; }

    public int Recsts { get; set; }

    public int AttributeValuesId { get; set; }



    public virtual OpenShop OpenShop { get; set; }

    public virtual ShopAttributes ShopAttributes { get; set; }

    public virtual ShopAttributeValues ShopAttributeValues { get; set; }

}

}
