
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class OpenShop
{

    public OpenShop()
    {

        this.OpenShopPhoto = new HashSet<OpenShopPhoto>();

        this.OpenShopShopProject = new HashSet<OpenShopShopProject>();

        this.OpenShopAttributeValues = new HashSet<OpenShopAttributeValues>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Rmark { get; set; }

    public string Logo { get; set; }

    public string Url { get; set; }

    public string VidoUrl { get; set; }

    public int Recsts { get; set; }

    public System.DateTime CreateTime { get; set; }

    public int Type { get; set; }

    public int viewclick { get; set; }

    public string Address { get; set; }

    public bool Isguarantee { get; set; }

    public string Size { get; set; }

    public string TypeId { get; set; }

    public Nullable<int> RegionId { get; set; }

    public Nullable<decimal> Accountbalance { get; set; }

    public string email { get; set; }

    public string Abbreviation { get; set; }

    public string Introduction { get; set; }

    public string photo { get; set; }

    public string QRcode { get; set; }

    public string Industry { get; set; }

    public string Distribution { get; set; }

    public string Contactname { get; set; }

    public string Contactphone { get; set; }

    public string BLS { get; set; }

    public string OCC { get; set; }

    public string OPC { get; set; }

    public string CIC { get; set; }

    public string AC { get; set; }

    public string TRC { get; set; }

    public Nullable<decimal> lat { get; set; }

    public Nullable<decimal> Long { get; set; }

    public Nullable<int> isaudit { get; set; }

    public int Districtid { get; set; }

    public int Rangeid { get; set; }



    public virtual ICollection<OpenShopPhoto> OpenShopPhoto { get; set; }

    public virtual ICollection<OpenShopShopProject> OpenShopShopProject { get; set; }

    public virtual ICollection<OpenShopAttributeValues> OpenShopAttributeValues { get; set; }

    public virtual ShopAttributeValues FkType { get; set; }

    public virtual hotarea Fkhotarea { get; set; }

    public virtual C_Object FKObject { get; set; }

}

}
