

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities : DbContext
{
    public Entities()
        : base("name=Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CustomerGroupOn> CustomerGroupOn { get; set; }

    public virtual DbSet<Link> Link { get; set; }

    public virtual DbSet<OpenShopPhoto> OpenShopPhoto { get; set; }

    public virtual DbSet<OpenShopShopProject> OpenShopShopProject { get; set; }

    public virtual DbSet<ProjectPhoto> ProjectPhoto { get; set; }

    public virtual DbSet<ProjectService> ProjectService { get; set; }

    public virtual DbSet<ShopAttributes> ShopAttributes { get; set; }

    public virtual DbSet<ShopAttributeValues> ShopAttributeValues { get; set; }

    public virtual DbSet<ShopBasAcrRange> ShopBasAcrRange { get; set; }

    public virtual DbSet<ShopBasOpeningTime> ShopBasOpeningTime { get; set; }

    public virtual DbSet<ShopBasPriceRentRange> ShopBasPriceRentRange { get; set; }

    public virtual DbSet<ShopBasPriceSaleRange> ShopBasPriceSaleRange { get; set; }

    public virtual DbSet<ShopBrand> ShopBrand { get; set; }

    public virtual DbSet<ShopBrandAttributeValues> ShopBrandAttributeValues { get; set; }

    public virtual DbSet<ShopBrandBranch> ShopBrandBranch { get; set; }

    public virtual DbSet<ShopBrandPhoto> ShopBrandPhoto { get; set; }

    public virtual DbSet<ShopProject> ShopProject { get; set; }

    public virtual DbSet<ShopProjectMain> ShopProjectMain { get; set; }

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<ApplyActivity> ApplyActivity { get; set; }

    public virtual DbSet<ShopAdPosition> ShopAdPosition { get; set; }

    public virtual DbSet<ShopAdPositionDetails> ShopAdPositionDetails { get; set; }

    public virtual DbSet<ShopDemo> ShopDemo { get; set; }

    public virtual DbSet<JobMinute> JobMinute { get; set; }

    public virtual DbSet<ShopPostings> ShopPostings { get; set; }

    public virtual DbSet<ShopRoom> ShopRoom { get; set; }

    public virtual DbSet<OpenShop> OpenShop { get; set; }

    public virtual DbSet<ShopProjectAttributesValues> ShopProjectAttributesValues { get; set; }

    public virtual DbSet<OpenShopAttributeValues> OpenShopAttributeValues { get; set; }

    public virtual DbSet<ApplyBrand> ApplyBrands { get; set; }

    public virtual DbSet<SmsLog> SmsLogs { get; set; }

    public virtual DbSet<CustomerLog> CustomerLogs { get; set; }

    public virtual DbSet<C_File> C_File { get; set; }

    public virtual DbSet<C_Object> C_Object { get; set; }

    public virtual DbSet<CustomerDiscipline> CustomerDisciplines { get; set; }

    public virtual DbSet<G_Category> G_Category { get; set; }

    public virtual DbSet<G_Goods> G_Goods { get; set; }

    public virtual DbSet<G_Name> G_Name { get; set; }

    public virtual DbSet<G_NameCategoryMapping> G_NameCategoryMapping { get; set; }

    public virtual DbSet<G_Pricing> G_Pricing { get; set; }

    public virtual DbSet<O_Cart> O_Cart { get; set; }

    public virtual DbSet<O_CartGoods> O_CartGoods { get; set; }

    public virtual DbSet<O_Order> O_Order { get; set; }

    public virtual DbSet<O_SalerBuyerMapping> O_SalerBuyerMapping { get; set; }

    public virtual DbSet<P_Account> P_Account { get; set; }

    public virtual DbSet<P_Trade> P_Trade { get; set; }

    public virtual DbSet<M_Contract> M_Contract { get; set; }

    public virtual DbSet<M_Period> M_Period { get; set; }

    public virtual DbSet<M_Mission> M_Mission { get; set; }

    public virtual DbSet<S_Message> S_Message { get; set; }

    public virtual DbSet<Grouppurchase> Grouppurchases { get; set; }

    public virtual DbSet<JoinProject> JoinProjects { get; set; }

    public virtual DbSet<hotarea> hotareas { get; set; }

}

}

