
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class P_Account
{

    public int Id { get; set; }

    public int ObjId { get; set; }

    public int ObjType { get; set; }

    public string RealName { get; set; }

    public string Mobile { get; set; }

    public decimal Balance { get; set; }

    public int Creater { get; set; }

    public System.DateTime CreateTime { get; set; }

}

}
