
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectPhoto
{

    public int Id { get; set; }

    public int ShopProjectId { get; set; }

    public string PhotoName { get; set; }

    public string PhotoUrl { get; set; }

    public string PhotoUrlSmall { get; set; }

    public Nullable<int> Sort { get; set; }

    public int Recsts { get; set; }

    public System.DateTime CreatTime { get; set; }

    public Nullable<int> Type { get; set; }



    public virtual ShopProject ShopProject { get; set; }

}

}
