
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectService
{

    public int Id { get; set; }

    public Nullable<int> ShopProjectId { get; set; }

    public string Name { get; set; }

    public string PicUrl { get; set; }

    public Nullable<bool> IsMvp { get; set; }

    public Nullable<byte> Status { get; set; }

    public string Job { get; set; }

    public string Phone { get; set; }



    public virtual ShopProject ShopProject { get; set; }

}

}
