
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class S_Message
{

    public int Id { get; set; }

    public int Sender { get; set; }

    public int Receiver { get; set; }

    public string Message { get; set; }

    public bool HasShortMessage { get; set; }

    public System.DateTime SendTime { get; set; }

    public string DetailsUrl { get; set; }

    public Nullable<System.DateTime> ReceiveTime { get; set; }

    public string SenderNumber { get; set; }

    public string ReceiverNumber { get; set; }

    public int MessageType { get; set; }



    public virtual Customer FkReceiver { get; set; }

    public virtual Customer FkSender { get; set; }

}

}
