
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopPostings
{

    public int Id { get; set; }

    public string PName { get; set; }

    public string city { get; set; }

    public string district { get; set; }

    public string hotarea { get; set; }

    public string PIntent { get; set; }

    public string Format { get; set; }

    public string price { get; set; }

    public string square { get; set; }

    public string Ptype { get; set; }

    public string Contacts { get; set; }

    public string Mobile { get; set; }

    public string Pinfo { get; set; }

    public Nullable<System.DateTime> Addtiem { get; set; }

    public Nullable<System.DateTime> Endtiem { get; set; }

}

}
