
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopBasOpeningTime
{

    public int Id { get; set; }

    public string OpeningName { get; set; }

    public Nullable<int> OpeningTimeDay { get; set; }

    public Nullable<int> CustomOrder { get; set; }

    public Nullable<System.DateTime> CreateTime { get; set; }

}

}
