
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopProjectMain
{

    public int Id { get; set; }

    public int ShopProjectId { get; set; }

    public string Name { get; set; }

    public string TradeId { get; set; }

    public Nullable<int> RegionId { get; set; }

    public Nullable<int> TradingAreaId { get; set; }

    public Nullable<int> CircleLineId { get; set; }

    public Nullable<decimal> SalePrice { get; set; }

    public Nullable<decimal> RentalPrice { get; set; }

    public string MetroId { get; set; }

    public string StateId { get; set; }

    public Nullable<System.DateTime> OpenDate { get; set; }

    public Nullable<int> Recsts { get; set; }

    public Nullable<System.DateTime> CreatTime { get; set; }

    public string TypeOfOperationId { get; set; }



    public virtual ShopProject ShopProject { get; set; }

}

}
