
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopRoom
{

    public int Id { get; set; }

    public string ShopId { get; set; }

    public string RName { get; set; }

    public string city { get; set; }

    public string district { get; set; }

    public string hotarea { get; set; }

    public string address { get; set; }

    public string sale { get; set; }

    public Nullable<decimal> price { get; set; }

    public Nullable<decimal> square { get; set; }

    public string type { get; set; }

    public string Face { get; set; }

    public string Contacts { get; set; }

    public string Mobile { get; set; }

    public string Rinfo { get; set; }

    public string Rimg { get; set; }

    public Nullable<System.DateTime> AddTime { get; set; }

    public string source { get; set; }

    public Nullable<int> from { get; set; }

    public Nullable<long> fetchDate { get; set; }

    public Nullable<int> CustomerId { get; set; }

    public Nullable<int> isCert { get; set; }

}

}
