
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopBasPriceRentRange
{

    public int Id { get; set; }

    public string RPName { get; set; }

    public double RPFrom { get; set; }

    public double RPEnd { get; set; }

    public int RPCustomerOrder { get; set; }

    public System.DateTime RPCreatedtime { get; set; }

}

}
