
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopBranch
{

    public int Id { get; set; }

    public int ShopBrandId { get; set; }

    public string BrachName { get; set; }

    public string BranchAddress { get; set; }

    public string BranchPhone { get; set; }

    public int Recsts { get; set; }

}

}
