
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopAdPosition
{

    public int Id { get; set; }

    public int TypesId { get; set; }

    public int PositionId { get; set; }

    public System.DateTime StartDate { get; set; }

    public string AdWords { get; set; }

    public string Url { get; set; }

    public string AdPicSmall { get; set; }

    public string AdPic { get; set; }

    public int Status { get; set; }

    public Nullable<int> Sort { get; set; }

    public Nullable<int> KeyId { get; set; }

}

}
