
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopProject
{

    public ShopProject()
    {

        this.OpenShopShopProject = new HashSet<OpenShopShopProject>();

        this.ProjectPhoto = new HashSet<ProjectPhoto>();

        this.ProjectService = new HashSet<ProjectService>();

        this.ShopProjectMain = new HashSet<ShopProjectMain>();

        this.ShopProjectAttributesValues = new HashSet<ShopProjectAttributesValues>();

        this.Grouppurchases = new HashSet<Grouppurchase>();

    }


    public int Id { get; set; }

    public string NAME { get; set; }

    public string AddressLine { get; set; }

    public string TeShe { get; set; }

    public string TuanDuiInfo { get; set; }

    public string YouShi { get; set; }

    public string BQuanShu { get; set; }

    public string BWaiLiMian { get; set; }

    public string BJieGou { get; set; }

    public Nullable<decimal> JZongJianZhuMianJi { get; set; }

    public Nullable<int> JZongChengShu { get; set; }

    public Nullable<decimal> JChengGao { get; set; }

    public Nullable<decimal> PChengMianJi { get; set; }

    public string PZhuLiHuxing { get; set; }

    public string PWindowOpen { get; set; }

    public string PChengZhongZhu { get; set; }

    public string PHeXinTong { get; set; }

    public string PHeiFangJian { get; set; }

    public string YLiftBrand { get; set; }

    public string YLiftIntro { get; set; }

    public string YLiftFenQu { get; set; }

    public string YLiftSpeed { get; set; }

    public string YAirConditoningBrand { get; set; }

    public string YAirConditoningControl { get; set; }

    public string YPrkingSpace { get; set; }

    public string TeaIntroduction { get; set; }

    public Nullable<decimal> Lat { get; set; }

    public Nullable<decimal> Long { get; set; }

    public Nullable<byte> Status { get; set; }

    public string CoverPhoto { get; set; }

    public Nullable<int> ViewClick { get; set; }

    public string ShangQuan { get; set; }

    public string ContactPhone { get; set; }

    public string ProjectIntro { get; set; }

    public Nullable<int> Projecthot { get; set; }

    public string Listings { get; set; }



    public virtual ICollection<OpenShopShopProject> OpenShopShopProject { get; set; }

    public virtual ICollection<ProjectPhoto> ProjectPhoto { get; set; }

    public virtual ICollection<ProjectService> ProjectService { get; set; }

    public virtual ICollection<ShopProjectMain> ShopProjectMain { get; set; }

    public virtual ICollection<ShopProjectAttributesValues> ShopProjectAttributesValues { get; set; }

    public virtual ICollection<Grouppurchase> Grouppurchases { get; set; }

}

}
