
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace YG.SC.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class ShopBrand
{

    public ShopBrand()
    {

        this.ShopBrandAttributeValues = new HashSet<ShopBrandAttributeValues>();

        this.ShopBrandBranch = new HashSet<ShopBrandBranch>();

        this.ShopBrandPhoto = new HashSet<ShopBrandPhoto>();

        this.ApplyBrands = new HashSet<ApplyBrand>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Rmark { get; set; }

    public string Logo { get; set; }

    public string Url { get; set; }

    public string VidoUrl { get; set; }

    public int Recsts { get; set; }

    public string QRCode { get; set; }

    public Nullable<System.DateTime> CreatTime { get; set; }

    public string BrandAD { get; set; }

    public Nullable<bool> JoinIn { get; set; }

    public Nullable<int> ViewClick { get; set; }

    public string Abbreviation { get; set; }

    public string photo { get; set; }

    public string Contactname { get; set; }

    public string Contactphone { get; set; }

    public string BLS { get; set; }

    public string OCC { get; set; }

    public string OPC { get; set; }

    public string CIC { get; set; }

    public string AC { get; set; }

    public string TRC { get; set; }

    public int IsAudited { get; set; }

    public string Address { get; set; }



    public virtual ICollection<ShopBrandAttributeValues> ShopBrandAttributeValues { get; set; }

    public virtual ICollection<ShopBrandBranch> ShopBrandBranch { get; set; }

    public virtual ICollection<ShopBrandPhoto> ShopBrandPhoto { get; set; }

    public virtual ICollection<ApplyBrand> ApplyBrands { get; set; }

}

}
