$axure.loadCurrentPage({
  "url":"商家注册.html",
  "generationDate":new Date(1442542996810.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"41f5a79c4c7d4b15a7cfc6678983a5b5",
    "type":"Axure:Page",
    "name":"商家注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"00bb9a5e5e5548b6af421a94157647cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-93,
              "y":0},
            "size":{
              "width":1413,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c05a31781ac4279ae36047205e05533",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-93,
                  "y":0},
                "size":{
                  "width":1413,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u0.png"}},
{
          "id":"fb5b546024ce4e4bae5502030f804650",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":10},
            "size":{
              "width":440,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efbac53c28ed470092824dcc11679dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":10},
                "size":{
                  "width":440,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u2.png"}},
{
          "id":"e6ab955b18874dc1acada721f07aaa6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":21},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbbc437b7d1f4ca586e5b8da63dd3c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":21},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cb06e20638c4f9abb725157bb283e0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":60,
              "y":79},
            "size":{
              "width":200,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be16f38d152441db26b51a8a443fc27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":60,
                  "y":79},
                "size":{
                  "width":200,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u6.png"}},
{
          "id":"fa983e3977cc4bd486a04af17baf1372",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":79},
            "size":{
              "width":160,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f02d44fbef11466a88fa3c78f7a5213f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492,
                  "y":79},
                "size":{
                  "width":160,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u8.png"}},
{
          "id":"b2a2ae80eca74a0aaa63ac90b697dc2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":673,
              "y":79},
            "size":{
              "width":160,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf35389bb0554535b4fe207b06289162",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":673,
                  "y":79},
                "size":{
                  "width":160,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u8.png"}},
{
          "id":"60749bda73284efa87b51e0e20672f94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":79},
            "size":{
              "width":170,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df23fc59b6bf45e39b3d7473f240af76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":79},
                "size":{
                  "width":170,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u12.png"}},
{
          "id":"f28a434e64414fde95a2658cd03be7c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":170},
            "size":{
              "width":960,
              "height":1160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a830fcd5977c476087cb5b6b75b29adc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":170},
                "size":{
                  "width":960,
                  "height":1160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u14.png"}},
{
          "id":"b400b43bffc24aa5846481018a50fd32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":60,
              "y":141},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"468e8f28563549a7af71e123e9a5eb53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":60,
                  "y":141},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e53fe3ccbc54b48885fc2d3d054dbb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":437,
              "y":190},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a52962e36c9495892c18970f9632dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":437,
                  "y":190},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82734ea140bd4f9e88f4d8644c4c3fce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":240},
            "size":{
              "width":910,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家注册/u20_line.png"}},
{
          "id":"20916157f5be457187f07077e9609bac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":194,
              "y":280},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1901ba2112ad4108ac9d640d4510b0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":194,
                  "y":280},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2006d7e48ae44ffb0c425c096964a49",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":279},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"530a5e29891c4e089092324c0b8e9503",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":274},
            "size":{
              "width":355,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c41db308a9d4277955f4f2350fc0dcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":274},
                "size":{
                  "width":355,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u24.png"}},
{
          "id":"c993d8d6ab424ad19192218e58d65459",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":194,
              "y":359},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec08e76af172438d8987e9cb64f781da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":194,
                  "y":359},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a927fd6f26cb40a19e29d09639bba507",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":358},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b83224428fb846bc81fd7652353e156d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":194,
              "y":400},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55428f8f73574ba6b810034f1b032454",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":194,
                  "y":400},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7b886f4fd3944a7a963be94ca5f44e6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":399},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"95592563b90545428f4d63e6e7d1a3e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":194,
              "y":320},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d848643386e1453a9b1c267e865f4976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":194,
                  "y":320},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f3a96f39a5b464bbaeb20282393ebcf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":327},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"45cd3c9aa4934cb9abab3bd681d0a665",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":194,
              "y":441},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad1a6fcbeb7345eb8c52bfbade7d1267",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":194,
                  "y":441},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3498fd20537c4087b74f136d4e1f18c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":441},
            "size":{
              "width":705,
              "height":206}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5321d04364f24317bd6b1da76dc32e8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":441},
                "size":{
                  "width":705,
                  "height":206}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u37.png"}},
{
          "id":"0c10a42a1dda499fb1fa0eff8af47b91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":79},
            "size":{
              "width":160,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed0a9dbf2f6460a8f1fbb30ed931640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":79},
                "size":{
                  "width":160,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u8.png"}},
{
          "id":"9cedbb8781e143c4ad31756381184ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":670},
            "size":{
              "width":789,
              "height":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e835b826005b475e9c8a7b2e69ee8cf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":670},
                "size":{
                  "width":789,
                  "height":300}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u41.png"}},
{
          "id":"ebf9572253ad4a8bbc6b82aa7514bfe8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":740},
            "size":{
              "width":150,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f333fc7281646fba3aea4ca3d226e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":740},
                "size":{
                  "width":150,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u43.png"}},
{
          "id":"5af7b53d585e439c92d84400bb01a9df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":328,
              "y":713},
            "size":{
              "width":63,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03154aab0e3d43989cb3c35c63c41e5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":328,
                  "y":713},
                "size":{
                  "width":63,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95b4fd9d30b24b2a9027f7d600e08291",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":740},
            "size":{
              "width":150,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab80c7095bdb42fdbe5449012ae62ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":740},
                "size":{
                  "width":150,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u43.png"}},
{
          "id":"a98de6c28b2e4cf897b0012f42ee2cdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":582,
              "y":712},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1645e267edee496bb43242580f403ec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":582,
                  "y":712},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5d9411b7f904ecba00dcb190770a31f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":749},
            "size":{
              "width":126,
              "height":121}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99de31cce7684fd7b8a5dc88f6564b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":749},
                "size":{
                  "width":126,
                  "height":121}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u51.png"}},
{
          "id":"d87d99fe6e744c72ac17362383dd5716",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":147,
              "y":1040},
            "size":{
              "width":833,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商家注册/u53_line.png"}},
{
          "id":"39c96b0470b340d98e28e5711dc17ad6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":437,
              "y":1009},
            "size":{
              "width":121,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d8d6280465e4514b10e86b5ffb3fba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":437,
                  "y":1009},
                "size":{
                  "width":121,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0113bae68424dca90f160c130f6c391",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":210,
              "y":1075},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5df7edccb98417583f6ae99154f6969",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":210,
                  "y":1075},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d35fd6c4fc2b4a1fb8d6a8131fc4602b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":1074},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4ad10687231c4b7f84e69858744682fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":210,
              "y":1116},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d023e2edc1c47dc9f811f7fd4d8975b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":210,
                  "y":1116},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b210af1b7d04470b8eeccd92d77d115",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":1115},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b2803d8859e74a5d8e02172c0ef31d0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":210,
              "y":1161},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"125b6bdbb28f4f8292deb8192f9b0614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":210,
                  "y":1161},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2018f01dcc154565a9b8c6107afa4b0a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":1160},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a4acf24e34df4c50899e3638169113e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":210,
              "y":1202},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8ad18fde37a4aacb5ba2bf3dbfc9a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":210,
                  "y":1202},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"211c0354350944449bcf893b1b16f14c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":1201},
            "size":{
              "width":240,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0de97971566b43eba577b7e1ed40053d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":328,
              "y":1380},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a286c977ffac444da01a152391a15087",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":1354},
            "size":{
              "width":256,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33171daf5f65479da78832f384de7532",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":1354},
                "size":{
                  "width":256,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "00bb9a5e5e5548b6af421a94157647cf":{
      "scriptId":"u0"},
    "1c05a31781ac4279ae36047205e05533":{
      "scriptId":"u1"},
    "fb5b546024ce4e4bae5502030f804650":{
      "scriptId":"u2"},
    "efbac53c28ed470092824dcc11679dd8":{
      "scriptId":"u3"},
    "e6ab955b18874dc1acada721f07aaa6e":{
      "scriptId":"u4"},
    "cbbc437b7d1f4ca586e5b8da63dd3c00":{
      "scriptId":"u5"},
    "3cb06e20638c4f9abb725157bb283e0b":{
      "scriptId":"u6"},
    "4be16f38d152441db26b51a8a443fc27":{
      "scriptId":"u7"},
    "fa983e3977cc4bd486a04af17baf1372":{
      "scriptId":"u8"},
    "f02d44fbef11466a88fa3c78f7a5213f":{
      "scriptId":"u9"},
    "b2a2ae80eca74a0aaa63ac90b697dc2e":{
      "scriptId":"u10"},
    "cf35389bb0554535b4fe207b06289162":{
      "scriptId":"u11"},
    "60749bda73284efa87b51e0e20672f94":{
      "scriptId":"u12"},
    "df23fc59b6bf45e39b3d7473f240af76":{
      "scriptId":"u13"},
    "f28a434e64414fde95a2658cd03be7c1":{
      "scriptId":"u14"},
    "a830fcd5977c476087cb5b6b75b29adc":{
      "scriptId":"u15"},
    "b400b43bffc24aa5846481018a50fd32":{
      "scriptId":"u16"},
    "468e8f28563549a7af71e123e9a5eb53":{
      "scriptId":"u17"},
    "9e53fe3ccbc54b48885fc2d3d054dbb3":{
      "scriptId":"u18"},
    "9a52962e36c9495892c18970f9632dab":{
      "scriptId":"u19"},
    "82734ea140bd4f9e88f4d8644c4c3fce":{
      "scriptId":"u20"},
    "20916157f5be457187f07077e9609bac":{
      "scriptId":"u21"},
    "1901ba2112ad4108ac9d640d4510b0f3":{
      "scriptId":"u22"},
    "e2006d7e48ae44ffb0c425c096964a49":{
      "scriptId":"u23"},
    "530a5e29891c4e089092324c0b8e9503":{
      "scriptId":"u24"},
    "7c41db308a9d4277955f4f2350fc0dcd":{
      "scriptId":"u25"},
    "c993d8d6ab424ad19192218e58d65459":{
      "scriptId":"u26"},
    "ec08e76af172438d8987e9cb64f781da":{
      "scriptId":"u27"},
    "a927fd6f26cb40a19e29d09639bba507":{
      "scriptId":"u28"},
    "b83224428fb846bc81fd7652353e156d":{
      "scriptId":"u29"},
    "55428f8f73574ba6b810034f1b032454":{
      "scriptId":"u30"},
    "b7b886f4fd3944a7a963be94ca5f44e6":{
      "scriptId":"u31"},
    "95592563b90545428f4d63e6e7d1a3e2":{
      "scriptId":"u32"},
    "d848643386e1453a9b1c267e865f4976":{
      "scriptId":"u33"},
    "0f3a96f39a5b464bbaeb20282393ebcf":{
      "scriptId":"u34"},
    "45cd3c9aa4934cb9abab3bd681d0a665":{
      "scriptId":"u35"},
    "ad1a6fcbeb7345eb8c52bfbade7d1267":{
      "scriptId":"u36"},
    "3498fd20537c4087b74f136d4e1f18c6":{
      "scriptId":"u37"},
    "5321d04364f24317bd6b1da76dc32e8b":{
      "scriptId":"u38"},
    "0c10a42a1dda499fb1fa0eff8af47b91":{
      "scriptId":"u39"},
    "7ed0a9dbf2f6460a8f1fbb30ed931640":{
      "scriptId":"u40"},
    "9cedbb8781e143c4ad31756381184ffe":{
      "scriptId":"u41"},
    "e835b826005b475e9c8a7b2e69ee8cf5":{
      "scriptId":"u42"},
    "ebf9572253ad4a8bbc6b82aa7514bfe8":{
      "scriptId":"u43"},
    "5f333fc7281646fba3aea4ca3d226e5a":{
      "scriptId":"u44"},
    "5af7b53d585e439c92d84400bb01a9df":{
      "scriptId":"u45"},
    "03154aab0e3d43989cb3c35c63c41e5a":{
      "scriptId":"u46"},
    "95b4fd9d30b24b2a9027f7d600e08291":{
      "scriptId":"u47"},
    "ab80c7095bdb42fdbe5449012ae62ed2":{
      "scriptId":"u48"},
    "a98de6c28b2e4cf897b0012f42ee2cdc":{
      "scriptId":"u49"},
    "1645e267edee496bb43242580f403ec5":{
      "scriptId":"u50"},
    "a5d9411b7f904ecba00dcb190770a31f":{
      "scriptId":"u51"},
    "99de31cce7684fd7b8a5dc88f6564b81":{
      "scriptId":"u52"},
    "d87d99fe6e744c72ac17362383dd5716":{
      "scriptId":"u53"},
    "39c96b0470b340d98e28e5711dc17ad6":{
      "scriptId":"u54"},
    "1d8d6280465e4514b10e86b5ffb3fba4":{
      "scriptId":"u55"},
    "d0113bae68424dca90f160c130f6c391":{
      "scriptId":"u56"},
    "a5df7edccb98417583f6ae99154f6969":{
      "scriptId":"u57"},
    "d35fd6c4fc2b4a1fb8d6a8131fc4602b":{
      "scriptId":"u58"},
    "4ad10687231c4b7f84e69858744682fd":{
      "scriptId":"u59"},
    "9d023e2edc1c47dc9f811f7fd4d8975b":{
      "scriptId":"u60"},
    "8b210af1b7d04470b8eeccd92d77d115":{
      "scriptId":"u61"},
    "b2803d8859e74a5d8e02172c0ef31d0f":{
      "scriptId":"u62"},
    "125b6bdbb28f4f8292deb8192f9b0614":{
      "scriptId":"u63"},
    "2018f01dcc154565a9b8c6107afa4b0a":{
      "scriptId":"u64"},
    "a4acf24e34df4c50899e3638169113e5":{
      "scriptId":"u65"},
    "d8ad18fde37a4aacb5ba2bf3dbfc9a3e":{
      "scriptId":"u66"},
    "211c0354350944449bcf893b1b16f14c":{
      "scriptId":"u67"},
    "0de97971566b43eba577b7e1ed40053d":{
      "scriptId":"u68"},
    "a286c977ffac444da01a152391a15087":{
      "scriptId":"u69"},
    "33171daf5f65479da78832f384de7532":{
      "scriptId":"u70"}}});