$axure.loadCurrentPage({
  "url":"商铺.html",
  "generationDate":new Date(1442542994232.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"566dc2963be3463c937f12ac1d33ab45",
    "type":"Axure:Page",
    "name":"商铺",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"38e3f0314ca84a64b2d06231e8c7e761",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-93,
              "y":0},
            "size":{
              "width":1413,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7808ffc00e724d1a8f8b73c52a606fcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-93,
                  "y":0},
                "size":{
                  "width":1413,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u0.png"}},
{
          "id":"538526c6de334c89a39bd12aa52a5623",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":10},
            "size":{
              "width":440,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9133912df51c421bbc34cfbc53ff3a85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":10},
                "size":{
                  "width":440,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u2.png"}},
{
          "id":"efe545e67e9e46c181b6ec1345d5cec5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-19,
              "y":85},
            "size":{
              "width":576,
              "height":525}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"376de928cd334bada6d326d0b8cf36a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-19,
                  "y":85},
                "size":{
                  "width":576,
                  "height":525}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺/u4.png"}},
{
          "id":"c4f344550b12428ebef707fd672d71d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":98},
            "size":{
              "width":737,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0a9e27073da42c4bce40cf09871b243",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":98},
                "size":{
                  "width":737,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺/u6.png"}},
{
          "id":"b7a8a77af8f24bd0a597f3d6c6aaec35",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":21},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"967d25fe89f24a9f972b9e0a15b90880",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":21},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00fee0c4d9fc488881ef1508f43b7b6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":150},
            "size":{
              "width":611,
              "height":487}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ab04732fd44729812f427387e26f10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":150},
                "size":{
                  "width":611,
                  "height":487}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "38e3f0314ca84a64b2d06231e8c7e761":{
      "scriptId":"u0"},
    "7808ffc00e724d1a8f8b73c52a606fcb":{
      "scriptId":"u1"},
    "538526c6de334c89a39bd12aa52a5623":{
      "scriptId":"u2"},
    "9133912df51c421bbc34cfbc53ff3a85":{
      "scriptId":"u3"},
    "efe545e67e9e46c181b6ec1345d5cec5":{
      "scriptId":"u4"},
    "376de928cd334bada6d326d0b8cf36a2":{
      "scriptId":"u5"},
    "c4f344550b12428ebef707fd672d71d2":{
      "scriptId":"u6"},
    "e0a9e27073da42c4bce40cf09871b243":{
      "scriptId":"u7"},
    "b7a8a77af8f24bd0a597f3d6c6aaec35":{
      "scriptId":"u8"},
    "967d25fe89f24a9f972b9e0a15b90880":{
      "scriptId":"u9"},
    "00fee0c4d9fc488881ef1508f43b7b6a":{
      "scriptId":"u10"},
    "53ab04732fd44729812f427387e26f10":{
      "scriptId":"u11"}}});