$axure.loadCurrentPage({
  "url":"我的任务.html",
  "generationDate":new Date(1442542999325.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7748a7f425e34985b3914aca2d9cd7a2",
    "type":"Axure:Page",
    "name":"我的任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1dc9248bf4254ddda0718a6c00558981",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"260021c3253848ba903afa79f2dd7370",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"b21a30089f3b4adeaf2716ae882a8be0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a74c9acc4874e5cbef205b6cf38eb9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc1e634486d4f4ba9d649ab81975f6f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"6d0bac281755456da696365f7ae8ddd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4501c7560ec64eb0965e23e11b48723f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"309940be69ea47ed99fd1d56022fa97e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":332},
            "size":{
              "width":783,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的账户/u35_line.png"}},
{
          "id":"d8c3281279104bb48ba31ff5bbd45d5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":508,
              "y":146},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bd233d2077041c59187253e9e8567b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":508,
                  "y":146},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab304076622c4b04ac847d201641fa8b",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":589,
              "y":143},
            "size":{
              "width":121,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"8dff635d4cd64adb8ef5de1ce28c7f6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":148},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"858c96ddb1074c039b5eb32d343356d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":148},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba4233cbc05c4a96a02cfefb1391e680",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":132},
            "size":{
              "width":202,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07138b2ad3e04ffbade62b059d5dd5d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":132},
                "size":{
                  "width":202,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u13.png"}},
{
          "id":"ac42ba1ac13e4cba9ff831e7c1630d8b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":143},
            "size":{
              "width":185,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3bde3a36f03c4e3993a9e73c51b24028",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":913,
              "y":143},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6035bf984c5b42cfa8e536484f78e033",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":196},
            "size":{
              "width":783,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u17_line.png"}},
{
          "id":"b739de0f02404223b35b43b3c49fce5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":925,
              "y":478},
            "size":{
              "width":103,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e79444b5bc4e648e9bdec0b0a244d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":925,
                  "y":478},
                "size":{
                  "width":103,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u18.png"}},
{
          "id":"c453618bcf4a4b6db52d8af757986862",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":460,
              "y":527},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d283f7013a24482b88947d1e24489e12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":527},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f8c89a2622a49aeae5e35c3a42b8b6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":479},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8c4b2fc31bf49609a8ab09f766a43bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":479},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8cbbb6c095c4072b7a0252695be1be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":124},
            "size":{
              "width":173,
              "height":736}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c906ffc0126465f8a3af5a1dd884cff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":124},
                "size":{
                  "width":173,
                  "height":736}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u53.png"}},
{
          "id":"7b8ac252ff2f4abeb613e8fc028831d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"603987d9c2624711b88bdceab7cb49f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u55.png"}},
{
          "id":"ba6483674dbf4085b7918e2b7cdf01c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":157},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927d3725e4944d08bffa0157ac019d50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":157},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0319451c05645058f16f6659065c129",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":365},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"48aafe33318742698b0c06890c37c22d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":383},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a57447b2d64076b10dee8b02de6ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":383},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88d59811714d4f8381f5d6d2c06197c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":412},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9592ba20517e47b2a981b7e0d5e9beed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":412},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d9c5afa978c4ee18e0f5d9c0f03a157",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":189},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c122d0f0ae6d4eaabc7e0a0c785d43be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":189},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0675b0861a8643f9a99a7090244715a0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":522},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"db36ffe8320e45eaa356b05321ef5bea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":439},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"616c3624dd714b8ebca8d11227e093ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":439},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"627235ee040f44b1b606b7d5b24ef8aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":499},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b067dcacea104d1ba080ad4717bfd006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":499},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86ab2910b08a46079e6a7c54cc039c90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":537},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc1871c230c2452e8604db4f360bc026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":537},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b856e0c54414cd5aba2b2987d4593ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":565},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef66b22bfe454327a841741bc751ba16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":565},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7cb32c7c8ec460194cc230af406fbe2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":594},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"862f64e369264843a8c92c1e776a1ba6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":594},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d691b252436148699f7e1ff59a493283",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":623},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a52295da480f447cb0f9b44371b68ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":623},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbb38db213cd4c038561bcd304dfe7da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":468},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a9b68c7c534a3d8545afdb34362bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":468},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de43ba58297b423fa954c91412f26d4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":240},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b3464f4f62d48bdacc6928312fc8824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":240},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"658ed0c90d314746857a21b8691fff6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":265},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18477650a093453d87c3c4d226f4e892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":265},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9e6a098e43d4828b1a3c670e81ecba1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"8020c6e451e341558c6ff81ef973afb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":308},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cf19e0d38854e71847de2bf5d92772e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":308},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"97c9a62e40e14e559918f5aa6191ac30",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":61,
              "y":214},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3c9de3597e4869949e3ea69cc48684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":214},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cb06d76e1d7478182e145d363f3c3ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":61,
              "y":337},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06a201729493439991071b6731c9dc40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":337},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81f44ec8fc074ac2a13a30f54e38033c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":651},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"204f7b9ea8e64384a89b8f50b20734bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":666},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e04f501797c4b40af573088a7bb8497",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":666},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75e6c3a6b1654344976ea6913e1837b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":694},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b6c19729bc46d290f116218e68b4ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":694},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bf7b3c24fdd4feeb4eb45bd219764dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":723},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2777f30137f4cdc896b7e49b2d9fa58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":723},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd8bc546e78e420d8b580305d86f4dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":752},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b7582445a034698ab794e1920bb0938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":752},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27ece46c283040ba9e9615c7a90dcbd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":781},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51c65b93356b42f59888fe2e50ad14d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":781},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9e76382bc2749f08d493c693b55ede8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":809},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3351cc29d8144a86a2396f97caaaa3d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":809},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61a529db00ee4589aa3ba09fa1d633de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":950,
              "y":224},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f66850ab40436f9fa98ef6d44c0063",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":224},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8061411c8e64c3f8e79ffb37c7040d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":951,
              "y":250},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5f47048ee0464a82079bd328873dad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":951,
                  "y":250},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f17130c6d57d4fa0973f82bb5bf1982d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":456.5,
              "y":613},
            "size":{
              "width":330,
              "height":247},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"303d5d831ff542cd804bb988f7061b4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":456.5,
                  "y":613},
                "size":{
                  "width":330,
                  "height":247},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u80.png"}},
{
          "id":"7cc4431ede9d49cbb8f9892b5b99f571",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":714},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d3d92ae530c488b8a76643b919fbb6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":714},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f35744005f814597a77dd84d3642b76e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":809},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c16757ef882645f1b2234dd9eb1dab64",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":809},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7c2def4aed9a49b282ce28c2b468d36e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":212},
            "size":{
              "width":23,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7285b742136d4c9ba547245e1541bf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":212},
                "size":{
                  "width":23,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u23.png"}},
{
          "id":"0b3ead18242f40b887497fe689d9cdec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":215},
            "size":{
              "width":230,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"383df96069ba47b58ebcff855e6c2183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":215},
                "size":{
                  "width":230,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6945a5d3a824bea935274a79dae9798",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":212},
            "size":{
              "width":94,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42d53452a11d42388d898376ee9f1cfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":212},
                "size":{
                  "width":94,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u90.png"}},
{
          "id":"2b2f2dcbffb24f67b0295e034998aa8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":241},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c93d1eec014216ad241cfd479bb9fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":241},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12e32d113ca942ef8536f4c2922e756c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":237},
            "size":{
              "width":15,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9caf51edbd64ffc95c8e934d8a33715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":237},
                "size":{
                  "width":15,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u94.png"}},
{
          "id":"3338a939aca94810880759c4b9c9e9d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":325,
              "y":241},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02aa6525e04d4fcaae81f28bc165419e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":241},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80853d61b49d4003a62b2dc6fdca15f6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":387,
              "y":244},
            "size":{
              "width":18,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u98_line.png"}},
{
          "id":"5a134b26c197450cbd7f6f5c67e41ec0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":241},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454b788c97484b8cbc81cb512fc268e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":241},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df2c94a12a394254a8a101caa686b00d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":285},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"775ea13018de4c62ba93d965727ddd8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":285},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u101.png"}},
{
          "id":"5890da6527434cdabaa41af9136f6df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":271,
              "y":263},
            "size":{
              "width":196,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8af0f9ce87f243f89390331864acb508",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":271,
                  "y":263},
                "size":{
                  "width":196,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31380ad3b4a14df19e7df0aaaf78b31d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":288},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90df8ebc150e4f23b8d01ab8fb78712a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":288},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebca00e9c2ed4da697aea366924c47e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":950,
              "y":383},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50fcd62fff6c422480bd3470984b2432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":383},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f423e98d5d243e9839dded3d4ebfd4c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":237,
              "y":352},
            "size":{
              "width":23,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a80fdca8778d486e977ac019037878f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":237,
                  "y":352},
                "size":{
                  "width":23,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u23.png"}},
{
          "id":"33d53764bbf94b4098debd1f564fa7ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":355},
            "size":{
              "width":230,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2bccbbcaf4645aba619b984a751598c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":355},
                "size":{
                  "width":230,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cf0965a4f9d4c9e8127ba75fb9492b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":352},
            "size":{
              "width":94,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82e0814a431d4b8eb48c33c17e116c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":510,
                  "y":352},
                "size":{
                  "width":94,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u90.png"}},
{
          "id":"dffb42f4437f4929ad27979db7860491",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":381},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f5baeeb41a4b52a1c9c8fc9713166d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":381},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f92d25ff5964d01a513df3a49d63aa6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":377},
            "size":{
              "width":15,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e0dd828bdf04e4e826681b29ff79257",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":310,
                  "y":377},
                "size":{
                  "width":15,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u94.png"}},
{
          "id":"9682dc8e6a5246409b0c82a3d5f7e051",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":325,
              "y":381},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afef1c6d6f8745a285667ec2ea811cf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":325,
                  "y":381},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1723799d548848b68d6391ff6e461757",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":382,
              "y":384},
            "size":{
              "width":18,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u98_line.png"}},
{
          "id":"69b9a80338da41ff96c094fd938e4029",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":381},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b97d986ef8b747f6b1b15da979495d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":410,
                  "y":381},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f58d0e5f766946d5b564c36da473bff6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":267,
              "y":425},
            "size":{
              "width":24,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c863e74e2244a609f26d7b8c949e151",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":267,
                  "y":425},
                "size":{
                  "width":24,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u101.png"}},
{
          "id":"c9ff35fbd71449cfa3e226be87d83783",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":293,
              "y":428},
            "size":{
              "width":51,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8702758e82341b0bd166204a93fecfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":293,
                  "y":428},
                "size":{
                  "width":51,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8889c4c165b94a1f8b16bc1b5d3baa9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":950,
              "y":409},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc592f3d8f04015adb960344364aafb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":950,
                  "y":409},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1dc9248bf4254ddda0718a6c00558981":{
      "scriptId":"u0"},
    "260021c3253848ba903afa79f2dd7370":{
      "scriptId":"u1"},
    "b21a30089f3b4adeaf2716ae882a8be0":{
      "scriptId":"u2"},
    "4a74c9acc4874e5cbef205b6cf38eb9b":{
      "scriptId":"u3"},
    "7dc1e634486d4f4ba9d649ab81975f6f":{
      "scriptId":"u4"},
    "6d0bac281755456da696365f7ae8ddd4":{
      "scriptId":"u5"},
    "4501c7560ec64eb0965e23e11b48723f":{
      "scriptId":"u6"},
    "309940be69ea47ed99fd1d56022fa97e":{
      "scriptId":"u7"},
    "d8c3281279104bb48ba31ff5bbd45d5c":{
      "scriptId":"u8"},
    "1bd233d2077041c59187253e9e8567b1":{
      "scriptId":"u9"},
    "ab304076622c4b04ac847d201641fa8b":{
      "scriptId":"u10"},
    "8dff635d4cd64adb8ef5de1ce28c7f6e":{
      "scriptId":"u11"},
    "858c96ddb1074c039b5eb32d343356d3":{
      "scriptId":"u12"},
    "ba4233cbc05c4a96a02cfefb1391e680":{
      "scriptId":"u13"},
    "07138b2ad3e04ffbade62b059d5dd5d9":{
      "scriptId":"u14"},
    "ac42ba1ac13e4cba9ff831e7c1630d8b":{
      "scriptId":"u15"},
    "3bde3a36f03c4e3993a9e73c51b24028":{
      "scriptId":"u16"},
    "6035bf984c5b42cfa8e536484f78e033":{
      "scriptId":"u17"},
    "b739de0f02404223b35b43b3c49fce5e":{
      "scriptId":"u18"},
    "99e79444b5bc4e648e9bdec0b0a244d7":{
      "scriptId":"u19"},
    "c453618bcf4a4b6db52d8af757986862":{
      "scriptId":"u20"},
    "d283f7013a24482b88947d1e24489e12":{
      "scriptId":"u21"},
    "6f8c89a2622a49aeae5e35c3a42b8b6d":{
      "scriptId":"u22"},
    "c8c4b2fc31bf49609a8ab09f766a43bd":{
      "scriptId":"u23"},
    "c8cbbb6c095c4072b7a0252695be1be3":{
      "scriptId":"u24"},
    "1c906ffc0126465f8a3af5a1dd884cff":{
      "scriptId":"u25"},
    "7b8ac252ff2f4abeb613e8fc028831d3":{
      "scriptId":"u26"},
    "603987d9c2624711b88bdceab7cb49f6":{
      "scriptId":"u27"},
    "ba6483674dbf4085b7918e2b7cdf01c3":{
      "scriptId":"u28"},
    "927d3725e4944d08bffa0157ac019d50":{
      "scriptId":"u29"},
    "c0319451c05645058f16f6659065c129":{
      "scriptId":"u30"},
    "48aafe33318742698b0c06890c37c22d":{
      "scriptId":"u31"},
    "75a57447b2d64076b10dee8b02de6ecc":{
      "scriptId":"u32"},
    "88d59811714d4f8381f5d6d2c06197c0":{
      "scriptId":"u33"},
    "9592ba20517e47b2a981b7e0d5e9beed":{
      "scriptId":"u34"},
    "5d9c5afa978c4ee18e0f5d9c0f03a157":{
      "scriptId":"u35"},
    "c122d0f0ae6d4eaabc7e0a0c785d43be":{
      "scriptId":"u36"},
    "0675b0861a8643f9a99a7090244715a0":{
      "scriptId":"u37"},
    "db36ffe8320e45eaa356b05321ef5bea":{
      "scriptId":"u38"},
    "616c3624dd714b8ebca8d11227e093ea":{
      "scriptId":"u39"},
    "627235ee040f44b1b606b7d5b24ef8aa":{
      "scriptId":"u40"},
    "b067dcacea104d1ba080ad4717bfd006":{
      "scriptId":"u41"},
    "86ab2910b08a46079e6a7c54cc039c90":{
      "scriptId":"u42"},
    "bc1871c230c2452e8604db4f360bc026":{
      "scriptId":"u43"},
    "6b856e0c54414cd5aba2b2987d4593ab":{
      "scriptId":"u44"},
    "ef66b22bfe454327a841741bc751ba16":{
      "scriptId":"u45"},
    "f7cb32c7c8ec460194cc230af406fbe2":{
      "scriptId":"u46"},
    "862f64e369264843a8c92c1e776a1ba6":{
      "scriptId":"u47"},
    "d691b252436148699f7e1ff59a493283":{
      "scriptId":"u48"},
    "a52295da480f447cb0f9b44371b68ed3":{
      "scriptId":"u49"},
    "dbb38db213cd4c038561bcd304dfe7da":{
      "scriptId":"u50"},
    "59a9b68c7c534a3d8545afdb34362bdc":{
      "scriptId":"u51"},
    "de43ba58297b423fa954c91412f26d4f":{
      "scriptId":"u52"},
    "5b3464f4f62d48bdacc6928312fc8824":{
      "scriptId":"u53"},
    "658ed0c90d314746857a21b8691fff6d":{
      "scriptId":"u54"},
    "18477650a093453d87c3c4d226f4e892":{
      "scriptId":"u55"},
    "b9e6a098e43d4828b1a3c670e81ecba1":{
      "scriptId":"u56"},
    "8020c6e451e341558c6ff81ef973afb8":{
      "scriptId":"u57"},
    "0cf19e0d38854e71847de2bf5d92772e":{
      "scriptId":"u58"},
    "97c9a62e40e14e559918f5aa6191ac30":{
      "scriptId":"u59"},
    "1d3c9de3597e4869949e3ea69cc48684":{
      "scriptId":"u60"},
    "5cb06d76e1d7478182e145d363f3c3ae":{
      "scriptId":"u61"},
    "06a201729493439991071b6731c9dc40":{
      "scriptId":"u62"},
    "81f44ec8fc074ac2a13a30f54e38033c":{
      "scriptId":"u63"},
    "204f7b9ea8e64384a89b8f50b20734bb":{
      "scriptId":"u64"},
    "0e04f501797c4b40af573088a7bb8497":{
      "scriptId":"u65"},
    "75e6c3a6b1654344976ea6913e1837b1":{
      "scriptId":"u66"},
    "71b6c19729bc46d290f116218e68b4ff":{
      "scriptId":"u67"},
    "9bf7b3c24fdd4feeb4eb45bd219764dd":{
      "scriptId":"u68"},
    "d2777f30137f4cdc896b7e49b2d9fa58":{
      "scriptId":"u69"},
    "dd8bc546e78e420d8b580305d86f4dc8":{
      "scriptId":"u70"},
    "3b7582445a034698ab794e1920bb0938":{
      "scriptId":"u71"},
    "27ece46c283040ba9e9615c7a90dcbd5":{
      "scriptId":"u72"},
    "51c65b93356b42f59888fe2e50ad14d6":{
      "scriptId":"u73"},
    "f9e76382bc2749f08d493c693b55ede8":{
      "scriptId":"u74"},
    "3351cc29d8144a86a2396f97caaaa3d4":{
      "scriptId":"u75"},
    "61a529db00ee4589aa3ba09fa1d633de":{
      "scriptId":"u76"},
    "54f66850ab40436f9fa98ef6d44c0063":{
      "scriptId":"u77"},
    "d8061411c8e64c3f8e79ffb37c7040d1":{
      "scriptId":"u78"},
    "7e5f47048ee0464a82079bd328873dad":{
      "scriptId":"u79"},
    "f17130c6d57d4fa0973f82bb5bf1982d":{
      "scriptId":"u80"},
    "303d5d831ff542cd804bb988f7061b4a":{
      "scriptId":"u81"},
    "7cc4431ede9d49cbb8f9892b5b99f571":{
      "scriptId":"u82"},
    "0d3d92ae530c488b8a76643b919fbb6f":{
      "scriptId":"u83"},
    "f35744005f814597a77dd84d3642b76e":{
      "scriptId":"u84"},
    "c16757ef882645f1b2234dd9eb1dab64":{
      "scriptId":"u85"},
    "7c2def4aed9a49b282ce28c2b468d36e":{
      "scriptId":"u86"},
    "7285b742136d4c9ba547245e1541bf99":{
      "scriptId":"u87"},
    "0b3ead18242f40b887497fe689d9cdec":{
      "scriptId":"u88"},
    "383df96069ba47b58ebcff855e6c2183":{
      "scriptId":"u89"},
    "b6945a5d3a824bea935274a79dae9798":{
      "scriptId":"u90"},
    "42d53452a11d42388d898376ee9f1cfe":{
      "scriptId":"u91"},
    "2b2f2dcbffb24f67b0295e034998aa8c":{
      "scriptId":"u92"},
    "58c93d1eec014216ad241cfd479bb9fb":{
      "scriptId":"u93"},
    "12e32d113ca942ef8536f4c2922e756c":{
      "scriptId":"u94"},
    "c9caf51edbd64ffc95c8e934d8a33715":{
      "scriptId":"u95"},
    "3338a939aca94810880759c4b9c9e9d7":{
      "scriptId":"u96"},
    "02aa6525e04d4fcaae81f28bc165419e":{
      "scriptId":"u97"},
    "80853d61b49d4003a62b2dc6fdca15f6":{
      "scriptId":"u98"},
    "5a134b26c197450cbd7f6f5c67e41ec0":{
      "scriptId":"u99"},
    "454b788c97484b8cbc81cb512fc268e8":{
      "scriptId":"u100"},
    "df2c94a12a394254a8a101caa686b00d":{
      "scriptId":"u101"},
    "775ea13018de4c62ba93d965727ddd8f":{
      "scriptId":"u102"},
    "5890da6527434cdabaa41af9136f6df3":{
      "scriptId":"u103"},
    "8af0f9ce87f243f89390331864acb508":{
      "scriptId":"u104"},
    "31380ad3b4a14df19e7df0aaaf78b31d":{
      "scriptId":"u105"},
    "90df8ebc150e4f23b8d01ab8fb78712a":{
      "scriptId":"u106"},
    "ebca00e9c2ed4da697aea366924c47e9":{
      "scriptId":"u107"},
    "50fcd62fff6c422480bd3470984b2432":{
      "scriptId":"u108"},
    "9f423e98d5d243e9839dded3d4ebfd4c":{
      "scriptId":"u109"},
    "a80fdca8778d486e977ac019037878f6":{
      "scriptId":"u110"},
    "33d53764bbf94b4098debd1f564fa7ab":{
      "scriptId":"u111"},
    "f2bccbbcaf4645aba619b984a751598c":{
      "scriptId":"u112"},
    "0cf0965a4f9d4c9e8127ba75fb9492b2":{
      "scriptId":"u113"},
    "82e0814a431d4b8eb48c33c17e116c65":{
      "scriptId":"u114"},
    "dffb42f4437f4929ad27979db7860491":{
      "scriptId":"u115"},
    "d7f5baeeb41a4b52a1c9c8fc9713166d":{
      "scriptId":"u116"},
    "1f92d25ff5964d01a513df3a49d63aa6":{
      "scriptId":"u117"},
    "9e0dd828bdf04e4e826681b29ff79257":{
      "scriptId":"u118"},
    "9682dc8e6a5246409b0c82a3d5f7e051":{
      "scriptId":"u119"},
    "afef1c6d6f8745a285667ec2ea811cf9":{
      "scriptId":"u120"},
    "1723799d548848b68d6391ff6e461757":{
      "scriptId":"u121"},
    "69b9a80338da41ff96c094fd938e4029":{
      "scriptId":"u122"},
    "b97d986ef8b747f6b1b15da979495d90":{
      "scriptId":"u123"},
    "f58d0e5f766946d5b564c36da473bff6":{
      "scriptId":"u124"},
    "3c863e74e2244a609f26d7b8c949e151":{
      "scriptId":"u125"},
    "c9ff35fbd71449cfa3e226be87d83783":{
      "scriptId":"u126"},
    "c8702758e82341b0bd166204a93fecfb":{
      "scriptId":"u127"},
    "8889c4c165b94a1f8b16bc1b5d3baa9f":{
      "scriptId":"u128"},
    "dfc592f3d8f04015adb960344364aafb":{
      "scriptId":"u129"}}});