$axure.loadCurrentPage({
  "url":"消费统计.html",
  "generationDate":new Date(1442543000916.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dd270f35636841ed9704a59b415f074c",
    "type":"Axure:Page",
    "name":"消费统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3d485ee6ed684eada08bf34eab9cf50f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"251a49808b114d66831237710d271f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"53f59b13dbf545d984c6eb293bbd5f9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62f509a301e144faa956d5b19725e831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61b42d1244e149c0a46b8baf90791ce2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"a978516bcbbf4d91b3185e7872cb2e61",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"871f01aa15a74b0e8bc97dcb11b42356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"387bbdf22aba474cbf5cb355dee3a302",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":124},
            "size":{
              "width":173,
              "height":736}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d98c4f2848f4dc78e73abba47dd0d00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":124},
                "size":{
                  "width":173,
                  "height":736}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u53.png"}},
{
          "id":"f438a4de5753486588077cedde4a7293",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce5555c9440b48e2a915347ad8baadb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u55.png"}},
{
          "id":"194676f961d54d04959b625e133d2c6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":157},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b51ab061ce49467abe8a242117257e2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":157},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30e634ebb7d74c72864068d5a7446593",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":365},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"b189a37706c44f6b8fbd43c566b58884",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":383},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55b2d22a72054cddbc077ddc3f415e67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":383},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be0c7a9ea0834b19bbf5f3f728e71f37",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":56,
              "y":412},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a010a3c4e6b4bd8ad9a575573be8800",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":412},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b9fb88e0efe43279a657f52e00c6620",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":189},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f12b657b4cf746eda2280212d3a8276f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":189},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebf4eefafadb4e8eb0f6f64dd62e9b97",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":522},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"4f3565d8e572462ab0ff3be20c356f64",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":56,
              "y":439},
            "size":{
              "width":65,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9d9786d1f704af4a946998d1a5326a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":439},
                "size":{
                  "width":65,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a862fd8da02496cb66b9e976130eb1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":499},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ee78862f5e4746900c2c359a98bd57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":499},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26872ca73a0544848bfb57d171a37d79",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":537},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2be00daccc6407c860a806d127eaebf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":537},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8afdc985736a487b84869e4c70c9b21f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":565},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"783a70e0dbec44acbba992203c294294",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":565},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de7f10c0816749c3a0caa5f84e9fe9f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":594},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e98b8f3b964d7797c8a3dc319e216a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":594},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d27cb863a0bc48888e5631a2512fa195",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":623},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e006594e6ab94626a24de7a942f4b4d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":623},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa4d842a1e734c539fc533162590aad4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":468},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6514235bd744e3b577a3539c27156a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":468},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e8da3ec9395402bacbb35941b8f6cb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":240},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4ddc19cac144d5895e22ba82a2db379",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":240},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a0a8dc6db384b758f2df9e3881e4786",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":265},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"431f27efce464c9396c28b359ce0658e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":265},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e7e588c25b141bf9f300a29d70b5704",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"fe36d2e6ca5e4e8e87342381995c3334",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":308},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1843952ce60a4308a49e0493cefcf218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":308},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c16a94072ef419eb2937cbbf7e860ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":61,
              "y":214},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"624d5c6e7e8340f18198812884f23030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":214},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ef792b975664dc7aa21b6812882fb86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":61,
              "y":337},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"149bfb7bf898489988ff4d14589f7df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":337},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f95f5b2135ca44acaae36c9c1e226411",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":651},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"193e2e6d7e774663a6aa8e54fc579c67",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":666},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64e87819aeab4f34804024544e0aaeed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":666},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35e44c47e81e45b4bb11a35d7c0bacc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":694},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2054715100e438f9ddcffea60980176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":694},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e73996ab7634fb7b95bfadec64b7009",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":723},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef2b22406013424db5e86dfad33ac6eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":723},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef0a0e0f933c4237a4cd0e217504d45d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":752},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"503ebac1c7b4477ab15c5af59125f580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":752},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65f11f79c8e14baa9b7118721eaabc90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":781},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd292b4ff74b479b85f7a4ffd0e8c27d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":781},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c3770a5be7b4e2190cfa3ea6a5ea084",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":809},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e56ff96c61ab4f7eb42645987656ecc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":809},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5e2a3e67d58b4609aa507b517a9d7d41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":135},
            "size":{
              "width":820,
              "height":397}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb4f2e0507343d5bb581689ef6dccd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":135},
                "size":{
                  "width":820,
                  "height":397}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u59.png"}},
{
          "id":"74755b58d9cd4259a81c65af0977b7ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":135},
            "size":{
              "width":820,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"018e85f2e3c441e8b6ad813b9134fdc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":135},
                "size":{
                  "width":820,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u61.png"}},
{
          "id":"1c7641337fea4fb2b39c2a4e445e9bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":146},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e4e6769ced049f298835d9d44d72996",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":146},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c681559793f4a85bf60968c8ea1de81",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":137},
            "size":{
              "width":187,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27ba5c7e0a294898a018fee94ab29c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":137},
                "size":{
                  "width":187,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u65.png"}},
{
          "id":"55b8c08ec5074ad1a198cbf5e1f158c2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":646,
              "y":142},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"c579cc0731d44cba8013bd54384ab70d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":226},
            "size":{
              "width":793,
              "height":242}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0bcee8ff947475cbd62354bd320f41f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":247,
                  "y":226},
                "size":{
                  "width":793,
                  "height":242}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u68.png"}},
{
          "id":"b39525350ef74e439a5ec707c0d40beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":626,
              "y":200},
            "size":{
              "width":253,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"882107f9ce4149048619c671a7a99d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":626,
                  "y":200},
                "size":{
                  "width":253,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6474a7c8a5b14bde90bd02212e9f7722",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":200},
            "size":{
              "width":164,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04097bb649ac491db95424b21cda4932",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":200},
                "size":{
                  "width":164,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3d485ee6ed684eada08bf34eab9cf50f":{
      "scriptId":"u0"},
    "251a49808b114d66831237710d271f91":{
      "scriptId":"u1"},
    "53f59b13dbf545d984c6eb293bbd5f9c":{
      "scriptId":"u2"},
    "62f509a301e144faa956d5b19725e831":{
      "scriptId":"u3"},
    "61b42d1244e149c0a46b8baf90791ce2":{
      "scriptId":"u4"},
    "a978516bcbbf4d91b3185e7872cb2e61":{
      "scriptId":"u5"},
    "871f01aa15a74b0e8bc97dcb11b42356":{
      "scriptId":"u6"},
    "387bbdf22aba474cbf5cb355dee3a302":{
      "scriptId":"u7"},
    "3d98c4f2848f4dc78e73abba47dd0d00":{
      "scriptId":"u8"},
    "f438a4de5753486588077cedde4a7293":{
      "scriptId":"u9"},
    "ce5555c9440b48e2a915347ad8baadb0":{
      "scriptId":"u10"},
    "194676f961d54d04959b625e133d2c6b":{
      "scriptId":"u11"},
    "b51ab061ce49467abe8a242117257e2b":{
      "scriptId":"u12"},
    "30e634ebb7d74c72864068d5a7446593":{
      "scriptId":"u13"},
    "b189a37706c44f6b8fbd43c566b58884":{
      "scriptId":"u14"},
    "55b2d22a72054cddbc077ddc3f415e67":{
      "scriptId":"u15"},
    "be0c7a9ea0834b19bbf5f3f728e71f37":{
      "scriptId":"u16"},
    "9a010a3c4e6b4bd8ad9a575573be8800":{
      "scriptId":"u17"},
    "0b9fb88e0efe43279a657f52e00c6620":{
      "scriptId":"u18"},
    "f12b657b4cf746eda2280212d3a8276f":{
      "scriptId":"u19"},
    "ebf4eefafadb4e8eb0f6f64dd62e9b97":{
      "scriptId":"u20"},
    "4f3565d8e572462ab0ff3be20c356f64":{
      "scriptId":"u21"},
    "a9d9786d1f704af4a946998d1a5326a3":{
      "scriptId":"u22"},
    "7a862fd8da02496cb66b9e976130eb1d":{
      "scriptId":"u23"},
    "15ee78862f5e4746900c2c359a98bd57":{
      "scriptId":"u24"},
    "26872ca73a0544848bfb57d171a37d79":{
      "scriptId":"u25"},
    "a2be00daccc6407c860a806d127eaebf":{
      "scriptId":"u26"},
    "8afdc985736a487b84869e4c70c9b21f":{
      "scriptId":"u27"},
    "783a70e0dbec44acbba992203c294294":{
      "scriptId":"u28"},
    "de7f10c0816749c3a0caa5f84e9fe9f1":{
      "scriptId":"u29"},
    "48e98b8f3b964d7797c8a3dc319e216a":{
      "scriptId":"u30"},
    "d27cb863a0bc48888e5631a2512fa195":{
      "scriptId":"u31"},
    "e006594e6ab94626a24de7a942f4b4d8":{
      "scriptId":"u32"},
    "fa4d842a1e734c539fc533162590aad4":{
      "scriptId":"u33"},
    "dc6514235bd744e3b577a3539c27156a":{
      "scriptId":"u34"},
    "2e8da3ec9395402bacbb35941b8f6cb7":{
      "scriptId":"u35"},
    "e4ddc19cac144d5895e22ba82a2db379":{
      "scriptId":"u36"},
    "7a0a8dc6db384b758f2df9e3881e4786":{
      "scriptId":"u37"},
    "431f27efce464c9396c28b359ce0658e":{
      "scriptId":"u38"},
    "6e7e588c25b141bf9f300a29d70b5704":{
      "scriptId":"u39"},
    "fe36d2e6ca5e4e8e87342381995c3334":{
      "scriptId":"u40"},
    "1843952ce60a4308a49e0493cefcf218":{
      "scriptId":"u41"},
    "6c16a94072ef419eb2937cbbf7e860ed":{
      "scriptId":"u42"},
    "624d5c6e7e8340f18198812884f23030":{
      "scriptId":"u43"},
    "6ef792b975664dc7aa21b6812882fb86":{
      "scriptId":"u44"},
    "149bfb7bf898489988ff4d14589f7df5":{
      "scriptId":"u45"},
    "f95f5b2135ca44acaae36c9c1e226411":{
      "scriptId":"u46"},
    "193e2e6d7e774663a6aa8e54fc579c67":{
      "scriptId":"u47"},
    "64e87819aeab4f34804024544e0aaeed":{
      "scriptId":"u48"},
    "35e44c47e81e45b4bb11a35d7c0bacc3":{
      "scriptId":"u49"},
    "b2054715100e438f9ddcffea60980176":{
      "scriptId":"u50"},
    "1e73996ab7634fb7b95bfadec64b7009":{
      "scriptId":"u51"},
    "ef2b22406013424db5e86dfad33ac6eb":{
      "scriptId":"u52"},
    "ef0a0e0f933c4237a4cd0e217504d45d":{
      "scriptId":"u53"},
    "503ebac1c7b4477ab15c5af59125f580":{
      "scriptId":"u54"},
    "65f11f79c8e14baa9b7118721eaabc90":{
      "scriptId":"u55"},
    "fd292b4ff74b479b85f7a4ffd0e8c27d":{
      "scriptId":"u56"},
    "8c3770a5be7b4e2190cfa3ea6a5ea084":{
      "scriptId":"u57"},
    "e56ff96c61ab4f7eb42645987656ecc1":{
      "scriptId":"u58"},
    "5e2a3e67d58b4609aa507b517a9d7d41":{
      "scriptId":"u59"},
    "7eb4f2e0507343d5bb581689ef6dccd8":{
      "scriptId":"u60"},
    "74755b58d9cd4259a81c65af0977b7ee":{
      "scriptId":"u61"},
    "018e85f2e3c441e8b6ad813b9134fdc5":{
      "scriptId":"u62"},
    "1c7641337fea4fb2b39c2a4e445e9bec":{
      "scriptId":"u63"},
    "2e4e6769ced049f298835d9d44d72996":{
      "scriptId":"u64"},
    "2c681559793f4a85bf60968c8ea1de81":{
      "scriptId":"u65"},
    "27ba5c7e0a294898a018fee94ab29c58":{
      "scriptId":"u66"},
    "55b8c08ec5074ad1a198cbf5e1f158c2":{
      "scriptId":"u67"},
    "c579cc0731d44cba8013bd54384ab70d":{
      "scriptId":"u68"},
    "a0bcee8ff947475cbd62354bd320f41f":{
      "scriptId":"u69"},
    "b39525350ef74e439a5ec707c0d40beb":{
      "scriptId":"u70"},
    "882107f9ce4149048619c671a7a99d9b":{
      "scriptId":"u71"},
    "6474a7c8a5b14bde90bd02212e9f7722":{
      "scriptId":"u72"},
    "04097bb649ac491db95424b21cda4932":{
      "scriptId":"u73"}}});