$axure.loadCurrentPage({
  "url":"商家资料.html",
  "generationDate":new Date(1442543003954.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"610890c8461e4dd0b44a83144a0afa41",
    "type":"Axure:Page",
    "name":"商家资料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"60af9bfef0a043ba87ecd8791a715919",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abbb1c4341e54e7d9574446f7ae4c883",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"18af13dea26b4d8084684d5bec68ef4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":120},
            "size":{
              "width":173,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1946a43a8eb547d5b0958475416063ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":120},
                "size":{
                  "width":173,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u35.png"}},
{
          "id":"7b9a033655b649e59c8c46b9da0391c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce641ec2f0242829d812b499b9b1d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u37.png"}},
{
          "id":"67c58d896a1243bea867b2c41e2bc486",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":59,
              "y":150},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5304b6de0f1948ff8d7fca2ebc9d8cae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":59,
                  "y":150},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8275adfa668e4eccbe567d3e24564ec4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":268},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"bc7a18ee54a841a7afb261ace154afde",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":278},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d07088d09154d168cd415280b3af654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":278},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98ff63378efc44edbc4226435f946478",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":306},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f8816d518a43c98d582b33687a65a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":306},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b918528c31d428c80b836910bb57940",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":335},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f9e27e30d6f4d749c819f3e5d6e9fc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":335},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1449efdd4d842298b41e90750d2160f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":364},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5288f2807a4a4ec8b4a841247d9e3464",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":364},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1e08a658b6746d0aefe4dbcf0aa3334",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":393},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"3f66355ab3df4d5fb35fa0655e4753b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":411},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d5778399504f849478e4edab68c45f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":411},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af14f2be12494a9aba53e4dcfb2547f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":207},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5511edd16ba644e8bbd9279d2224d859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":207},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f9669da9b2f4c5b8af561f8a7a74328",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":440},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31ad514adcd432ab215a00935073957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":440},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"41ee0b2e7e2b4bc1893ab2cc20ab468e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":178},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf03d1419c8542c6b08830f02da90cdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":178},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06678ffc3fcb485c9fc292e31dd1bc1e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":554},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"3f8bd12e99fc44d5a8eef4f2b1004618",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":467},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23ffbd697c5f4fc5a789195d67e3b41e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":467},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca77478dfe5e43989f3f0920f0a58b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":527},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84beba620d9a4c92b35dd02d4d9ca761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":527},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fdaf04a360fe4fbdbbb42d1a752c94d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":569},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e914fe4690c44e6a8625dd6a4ef010bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":569},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d42253726bc64cc69a03624a0dd7c756",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":56,
              "y":597},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af90a05e1e9b4daabadc3e633b875072",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":597},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4702c4321d694c1e949264bf71cee486",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":626},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c59110ba3c4e43fea55f1c8b2f55cda3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":626},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8045b0afb884432182cfa3ca68aedf50",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":655},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b20f30f17348758a340d2b78bd23c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":655},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a447e291dd9344559aa7fbdb702ef075",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":684},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f4cf69beaf4ea2a6c2eabb0cca5318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":684},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5631f2ac7cf84d6ea307d6b4869037fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a1a439bf4664eaca960dbfa56a9340c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccdf6a0213b24e7f9dda97df64f9747d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"c23f2d3e285942acaecfa9c871f73610",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":496},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc1b9e6fcdb47e9b41a510a017f5f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":496},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3453c75bd91414592166fda5fee9a66",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64400f53a7f24e579ff6aeb95e071638",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b399b00c2a7d40b392afb242e542497f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":236},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a453a89a7da04ff69ea95c465e90a280",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":236},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"990f7c0c4ee64132ac9a781d693a2b26",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":145},
            "size":{
              "width":797,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f65169b37b484bfa9194c6e9e4c5175a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2923ad8c46054c2a921f7b545580a3e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u29.png"}},
{
              "id":"f35789ea9db44e4cb64dd20b013034cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3d97d7d2bf44d508bdd021b85da309e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u29.png"}},
{
              "id":"ddeebea9bf6b45f395328869240b917b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":0},
                "size":{
                  "width":270,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7bdf435740e04f92ab748f17e8159d03",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":0},
                    "size":{
                      "width":270,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u31.png"}},
{
              "id":"b27693824baa4aad86d8b275ae8d45d5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":30},
                "size":{
                  "width":270,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e648b6a6a78c4c1ea1a223b490be1682",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":30},
                    "size":{
                      "width":270,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u31.png"}},
{
              "id":"5e9a2849964a4ba0a66c7fc5cd3a49ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":396,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"123dd6f748254d4290fad7f352e723e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":396,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u33.png"}},
{
              "id":"cac0c5b2e1054134bbd979b4774f1c28",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":396,
                  "y":30},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dec8c142d5154d508150464a693e03e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":396,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u33.png"}},
{
              "id":"8741a389968040a5b654c2a0c2026dbc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":596,
                  "y":0},
                "size":{
                  "width":201,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b17715eb09343b2a76450763d5311e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":596,
                      "y":0},
                    "size":{
                      "width":201,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u35.png"}},
{
              "id":"56939230e96c4eef933c0f26c866f427",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":596,
                  "y":30},
                "size":{
                  "width":201,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c27795e2f1914ea594738e4eb1eade21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":596,
                      "y":30},
                    "size":{
                      "width":201,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u35.png"}},
{
              "id":"40db6bec972a49f4888863487d397625",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":126,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"067bc9c5c26142d39da1bf25b7553e63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":126,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u29.png"}},
{
              "id":"b85fc0f34e504d6aa11464c657d47747",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":60},
                "size":{
                  "width":270,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7676d8c864e949fbbb2317fc7e7375c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":60},
                    "size":{
                      "width":270,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u31.png"}},
{
              "id":"e50a5d1ec32b450b84f96832f3f66aec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":396,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f659aad0251e4e509949daa17506f2ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":396,
                      "y":60},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u33.png"}},
{
              "id":"6e73553414304bb2a62e3a7eafd7b039",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":596,
                  "y":60},
                "size":{
                  "width":201,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c8d7e55c02274cee98a4f83452df56cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":596,
                      "y":60},
                    "size":{
                      "width":201,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u35.png"}},
{
              "id":"4546368f7d3b4a65828ad9b1fca3a380",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":126,
                  "height":220}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d92ae6191b74eef9dd83c4b25285870",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":126,
                      "height":220}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u61.png"}},
{
              "id":"1cc92b7387b7469fa950c493bbe33686",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":126,
                  "y":90},
                "size":{
                  "width":270,
                  "height":220}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"36af6a238d7e42ef8227785d942725bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":126,
                      "y":90},
                    "size":{
                      "width":270,
                      "height":220}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u63.png"}},
{
              "id":"e9b6ddf6076545089e24148ec2004114",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":396,
                  "y":90},
                "size":{
                  "width":200,
                  "height":220}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"680c288ac9834d6e99e55dfc03fc0573",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":396,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":220}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u65.png"}},
{
              "id":"509897140a7b480fbc2d1d4184d674fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":596,
                  "y":90},
                "size":{
                  "width":201,
                  "height":220}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b08fd7b1cb9243d1914e73e96a7488d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":596,
                      "y":90},
                    "size":{
                      "width":201,
                      "height":220}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/平台审核/u67.png"}}]},
{
          "id":"38a60f778b784e4a862b10799d57551e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":480},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "60af9bfef0a043ba87ecd8791a715919":{
      "scriptId":"u0"},
    "abbb1c4341e54e7d9574446f7ae4c883":{
      "scriptId":"u1"},
    "18af13dea26b4d8084684d5bec68ef4c":{
      "scriptId":"u2"},
    "1946a43a8eb547d5b0958475416063ea":{
      "scriptId":"u3"},
    "7b9a033655b649e59c8c46b9da0391c7":{
      "scriptId":"u4"},
    "fce641ec2f0242829d812b499b9b1d8a":{
      "scriptId":"u5"},
    "67c58d896a1243bea867b2c41e2bc486":{
      "scriptId":"u6"},
    "5304b6de0f1948ff8d7fca2ebc9d8cae":{
      "scriptId":"u7"},
    "8275adfa668e4eccbe567d3e24564ec4":{
      "scriptId":"u8"},
    "bc7a18ee54a841a7afb261ace154afde":{
      "scriptId":"u9"},
    "7d07088d09154d168cd415280b3af654":{
      "scriptId":"u10"},
    "98ff63378efc44edbc4226435f946478":{
      "scriptId":"u11"},
    "d2f8816d518a43c98d582b33687a65a6":{
      "scriptId":"u12"},
    "7b918528c31d428c80b836910bb57940":{
      "scriptId":"u13"},
    "7f9e27e30d6f4d749c819f3e5d6e9fc7":{
      "scriptId":"u14"},
    "f1449efdd4d842298b41e90750d2160f":{
      "scriptId":"u15"},
    "5288f2807a4a4ec8b4a841247d9e3464":{
      "scriptId":"u16"},
    "a1e08a658b6746d0aefe4dbcf0aa3334":{
      "scriptId":"u17"},
    "3f66355ab3df4d5fb35fa0655e4753b9":{
      "scriptId":"u18"},
    "19d5778399504f849478e4edab68c45f":{
      "scriptId":"u19"},
    "af14f2be12494a9aba53e4dcfb2547f2":{
      "scriptId":"u20"},
    "5511edd16ba644e8bbd9279d2224d859":{
      "scriptId":"u21"},
    "7f9669da9b2f4c5b8af561f8a7a74328":{
      "scriptId":"u22"},
    "e31ad514adcd432ab215a00935073957":{
      "scriptId":"u23"},
    "41ee0b2e7e2b4bc1893ab2cc20ab468e":{
      "scriptId":"u24"},
    "cf03d1419c8542c6b08830f02da90cdb":{
      "scriptId":"u25"},
    "06678ffc3fcb485c9fc292e31dd1bc1e":{
      "scriptId":"u26"},
    "3f8bd12e99fc44d5a8eef4f2b1004618":{
      "scriptId":"u27"},
    "23ffbd697c5f4fc5a789195d67e3b41e":{
      "scriptId":"u28"},
    "ca77478dfe5e43989f3f0920f0a58b7f":{
      "scriptId":"u29"},
    "84beba620d9a4c92b35dd02d4d9ca761":{
      "scriptId":"u30"},
    "fdaf04a360fe4fbdbbb42d1a752c94d0":{
      "scriptId":"u31"},
    "e914fe4690c44e6a8625dd6a4ef010bc":{
      "scriptId":"u32"},
    "d42253726bc64cc69a03624a0dd7c756":{
      "scriptId":"u33"},
    "af90a05e1e9b4daabadc3e633b875072":{
      "scriptId":"u34"},
    "4702c4321d694c1e949264bf71cee486":{
      "scriptId":"u35"},
    "c59110ba3c4e43fea55f1c8b2f55cda3":{
      "scriptId":"u36"},
    "8045b0afb884432182cfa3ca68aedf50":{
      "scriptId":"u37"},
    "b3b20f30f17348758a340d2b78bd23c1":{
      "scriptId":"u38"},
    "a447e291dd9344559aa7fbdb702ef075":{
      "scriptId":"u39"},
    "65f4cf69beaf4ea2a6c2eabb0cca5318":{
      "scriptId":"u40"},
    "5631f2ac7cf84d6ea307d6b4869037fd":{
      "scriptId":"u41"},
    "6a1a439bf4664eaca960dbfa56a9340c":{
      "scriptId":"u42"},
    "ccdf6a0213b24e7f9dda97df64f9747d":{
      "scriptId":"u43"},
    "c23f2d3e285942acaecfa9c871f73610":{
      "scriptId":"u44"},
    "adc1b9e6fcdb47e9b41a510a017f5f56":{
      "scriptId":"u45"},
    "d3453c75bd91414592166fda5fee9a66":{
      "scriptId":"u46"},
    "64400f53a7f24e579ff6aeb95e071638":{
      "scriptId":"u47"},
    "b399b00c2a7d40b392afb242e542497f":{
      "scriptId":"u48"},
    "a453a89a7da04ff69ea95c465e90a280":{
      "scriptId":"u49"},
    "990f7c0c4ee64132ac9a781d693a2b26":{
      "scriptId":"u50"},
    "f65169b37b484bfa9194c6e9e4c5175a":{
      "scriptId":"u51"},
    "2923ad8c46054c2a921f7b545580a3e5":{
      "scriptId":"u52"},
    "ddeebea9bf6b45f395328869240b917b":{
      "scriptId":"u53"},
    "7bdf435740e04f92ab748f17e8159d03":{
      "scriptId":"u54"},
    "5e9a2849964a4ba0a66c7fc5cd3a49ea":{
      "scriptId":"u55"},
    "123dd6f748254d4290fad7f352e723e6":{
      "scriptId":"u56"},
    "8741a389968040a5b654c2a0c2026dbc":{
      "scriptId":"u57"},
    "0b17715eb09343b2a76450763d5311e5":{
      "scriptId":"u58"},
    "f35789ea9db44e4cb64dd20b013034cb":{
      "scriptId":"u59"},
    "d3d97d7d2bf44d508bdd021b85da309e":{
      "scriptId":"u60"},
    "b27693824baa4aad86d8b275ae8d45d5":{
      "scriptId":"u61"},
    "e648b6a6a78c4c1ea1a223b490be1682":{
      "scriptId":"u62"},
    "cac0c5b2e1054134bbd979b4774f1c28":{
      "scriptId":"u63"},
    "dec8c142d5154d508150464a693e03e3":{
      "scriptId":"u64"},
    "56939230e96c4eef933c0f26c866f427":{
      "scriptId":"u65"},
    "c27795e2f1914ea594738e4eb1eade21":{
      "scriptId":"u66"},
    "40db6bec972a49f4888863487d397625":{
      "scriptId":"u67"},
    "067bc9c5c26142d39da1bf25b7553e63":{
      "scriptId":"u68"},
    "b85fc0f34e504d6aa11464c657d47747":{
      "scriptId":"u69"},
    "7676d8c864e949fbbb2317fc7e7375c0":{
      "scriptId":"u70"},
    "e50a5d1ec32b450b84f96832f3f66aec":{
      "scriptId":"u71"},
    "f659aad0251e4e509949daa17506f2ca":{
      "scriptId":"u72"},
    "6e73553414304bb2a62e3a7eafd7b039":{
      "scriptId":"u73"},
    "c8d7e55c02274cee98a4f83452df56cb":{
      "scriptId":"u74"},
    "4546368f7d3b4a65828ad9b1fca3a380":{
      "scriptId":"u75"},
    "5d92ae6191b74eef9dd83c4b25285870":{
      "scriptId":"u76"},
    "1cc92b7387b7469fa950c493bbe33686":{
      "scriptId":"u77"},
    "36af6a238d7e42ef8227785d942725bd":{
      "scriptId":"u78"},
    "e9b6ddf6076545089e24148ec2004114":{
      "scriptId":"u79"},
    "680c288ac9834d6e99e55dfc03fc0573":{
      "scriptId":"u80"},
    "509897140a7b480fbc2d1d4184d674fd":{
      "scriptId":"u81"},
    "b08fd7b1cb9243d1914e73e96a7488d2":{
      "scriptId":"u82"},
    "38a60f778b784e4a862b10799d57551e":{
      "scriptId":"u83"}}});