$axure.loadCurrentPage({
  "url":"上传案例图片.html",
  "generationDate":new Date(1442542997512.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"17a5463ab0164d15957329fd56c715fc",
    "type":"Axure:Page",
    "name":"上传案例图片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bb400e54b9ec482db33e75bbd0a4e431",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-93,
              "y":0},
            "size":{
              "width":1413,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af5c7261a2b432b9937c7885ec702a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-93,
                  "y":0},
                "size":{
                  "width":1413,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u0.png"}},
{
          "id":"bfff47cbd5504c04a44304d96c7f7904",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":10},
            "size":{
              "width":440,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe288c8d51b1426b9165c3827fd907cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":10},
                "size":{
                  "width":440,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u2.png"}},
{
          "id":"0b57ade1334c4eb99933c167158c46e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":21},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5548472aecdc4c5f9d34dcda71cdb781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":21},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"915de08a3f274c7eb99bc5d983dae6e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":79},
            "size":{
              "width":200,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"010a43a53e4c492aab9bedf33f739dfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":79},
                "size":{
                  "width":200,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u6.png"}},
{
          "id":"cab9c39e00ef4fa38d84a04717ae531c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":492,
              "y":79},
            "size":{
              "width":160,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97edc26eb5a446d3b89f5ab134b0d2e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":492,
                  "y":79},
                "size":{
                  "width":160,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u8.png"}},
{
          "id":"a9b8a731a0e34d4c9ed23ca3e0501e7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":673,
              "y":79},
            "size":{
              "width":160,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef2c89782a514d3ea5249879a5f0dc57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":673,
                  "y":79},
                "size":{
                  "width":160,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u8.png"}},
{
          "id":"3744c812fabc4395a46ef573fe214f72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":79},
            "size":{
              "width":170,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eab575bb40ef4ef2bc604d3a84a36348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":79},
                "size":{
                  "width":170,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家注册/u12.png"}},
{
          "id":"b14cf286cc6e407ca3c08dc898be3beb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":60,
              "y":141},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccad9ff75a1c4349b1b3f23013159367",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":60,
                  "y":141},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76834c6220d242779759c1d27fbb7f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":294,
              "y":79},
            "size":{
              "width":160,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c73c39e326994b4b911b2d6fdf6bee3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":294,
                  "y":79},
                "size":{
                  "width":160,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u16.png"}},
{
          "id":"d1b198e9894148f7a2064e9ed8769f5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":180},
            "size":{
              "width":960,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f6ab4895e248d4a616df533295afde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":180},
                "size":{
                  "width":960,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u18.png"}},
{
          "id":"3e161a20c56342769168fd216b8a577b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":267,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b054b9801a40ae9ace0d4e4927e12e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":267,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u20.png"}},
{
          "id":"471bf421fea748fb8baea5becffb835e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":404},
            "size":{
              "width":157,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cf221f96a654be8b1cdf1d71cc772b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":404},
                "size":{
                  "width":157,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3314b3d862c8426f8f4e6ff6653ab1d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":430},
            "size":{
              "width":195,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"043ecfcf4bf749269126e4c1c4ad8bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":430},
                "size":{
                  "width":195,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1c283c3fdd6544e1b5874b3beee979db",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":157.5,
              "y":465},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"91dd02be37034cada0d7a64b8416b849",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":200},
            "size":{
              "width":267,
              "height":194}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"796e55d7f8b047728c1e05d570ee18f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":200},
                "size":{
                  "width":267,
                  "height":194}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u20.png"}},
{
          "id":"9ce3b44381e5463286e9e2a4e713b9c9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":412.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0cf615ea357444e4bed1b79da3247a16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":200},
            "size":{
              "width":267,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"843666918ae04d46ab5ddc033efead81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":200},
                "size":{
                  "width":267,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u30.png"}},
{
          "id":"7e21a9c2dbae4889981c4abf48c8f829",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":137},
            "size":{
              "width":438,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e0a1212d254a2aac283ca6db6e917d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":137},
                "size":{
                  "width":438,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/上传案例图片/u32.png"}},
{
          "id":"974bb61b1ca14c608b7bd33fb1eeef8e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":247,
              "y":710},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4e0925eec4b245b9aaf6759fc42914c9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":710},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "bb400e54b9ec482db33e75bbd0a4e431":{
      "scriptId":"u0"},
    "1af5c7261a2b432b9937c7885ec702a6":{
      "scriptId":"u1"},
    "bfff47cbd5504c04a44304d96c7f7904":{
      "scriptId":"u2"},
    "fe288c8d51b1426b9165c3827fd907cb":{
      "scriptId":"u3"},
    "0b57ade1334c4eb99933c167158c46e0":{
      "scriptId":"u4"},
    "5548472aecdc4c5f9d34dcda71cdb781":{
      "scriptId":"u5"},
    "915de08a3f274c7eb99bc5d983dae6e6":{
      "scriptId":"u6"},
    "010a43a53e4c492aab9bedf33f739dfe":{
      "scriptId":"u7"},
    "cab9c39e00ef4fa38d84a04717ae531c":{
      "scriptId":"u8"},
    "97edc26eb5a446d3b89f5ab134b0d2e3":{
      "scriptId":"u9"},
    "a9b8a731a0e34d4c9ed23ca3e0501e7f":{
      "scriptId":"u10"},
    "ef2c89782a514d3ea5249879a5f0dc57":{
      "scriptId":"u11"},
    "3744c812fabc4395a46ef573fe214f72":{
      "scriptId":"u12"},
    "eab575bb40ef4ef2bc604d3a84a36348":{
      "scriptId":"u13"},
    "b14cf286cc6e407ca3c08dc898be3beb":{
      "scriptId":"u14"},
    "ccad9ff75a1c4349b1b3f23013159367":{
      "scriptId":"u15"},
    "76834c6220d242779759c1d27fbb7f00":{
      "scriptId":"u16"},
    "c73c39e326994b4b911b2d6fdf6bee3c":{
      "scriptId":"u17"},
    "d1b198e9894148f7a2064e9ed8769f5d":{
      "scriptId":"u18"},
    "d7f6ab4895e248d4a616df533295afde":{
      "scriptId":"u19"},
    "3e161a20c56342769168fd216b8a577b":{
      "scriptId":"u20"},
    "45b054b9801a40ae9ace0d4e4927e12e":{
      "scriptId":"u21"},
    "471bf421fea748fb8baea5becffb835e":{
      "scriptId":"u22"},
    "1cf221f96a654be8b1cdf1d71cc772b3":{
      "scriptId":"u23"},
    "3314b3d862c8426f8f4e6ff6653ab1d0":{
      "scriptId":"u24"},
    "043ecfcf4bf749269126e4c1c4ad8bab":{
      "scriptId":"u25"},
    "1c283c3fdd6544e1b5874b3beee979db":{
      "scriptId":"u26"},
    "91dd02be37034cada0d7a64b8416b849":{
      "scriptId":"u27"},
    "796e55d7f8b047728c1e05d570ee18f6":{
      "scriptId":"u28"},
    "9ce3b44381e5463286e9e2a4e713b9c9":{
      "scriptId":"u29"},
    "0cf615ea357444e4bed1b79da3247a16":{
      "scriptId":"u30"},
    "843666918ae04d46ab5ddc033efead81":{
      "scriptId":"u31"},
    "7e21a9c2dbae4889981c4abf48c8f829":{
      "scriptId":"u32"},
    "19e0a1212d254a2aac283ca6db6e917d":{
      "scriptId":"u33"},
    "974bb61b1ca14c608b7bd33fb1eeef8e":{
      "scriptId":"u34"},
    "4e0925eec4b245b9aaf6759fc42914c9":{
      "scriptId":"u35"}}});