$axure.loadCurrentPage({
  "url":"消费分布.html",
  "generationDate":new Date(1442543001978.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3de7c732e5c24e75b7fadeecf270e47f",
    "type":"Axure:Page",
    "name":"消费分布",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7eecad3adbf74024ba5ec19451d93bf4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72b1d5bd589f40f09dd5d273e771128d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"fbe47dbdd3154105929c6f799ec1adcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97b262d6ff91498db5d847a774c90d07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6fad2fd54aff4188a1aaa7736cc298aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"4adb153efbe744f09c00c3c3b2286d27",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263729c84982434d9def458428e1142c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77015ca1a435492da968396964cb6d92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":124},
            "size":{
              "width":173,
              "height":736}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8554197841d64f76834f970161a0f719",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":124},
                "size":{
                  "width":173,
                  "height":736}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u53.png"}},
{
          "id":"97e7e3e78fe14bc58edabb2f5b7db800",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fa5c0fdb1dc4282b86c41458f6fa62f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u55.png"}},
{
          "id":"906f5c6a1fe04a2b8833bf6d0c3a2ce0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":157},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4afd86c09b8e497d8b0e2dba7868d01d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":157},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eacfd7a92b904a6d9c6b5c1b7fc970f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":365},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"f693b4bd555f44098ac2f59722975ea9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":383},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e34bf17539884b2aa77acbe86bd3df91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":383},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d656dcc89c643fd84469636b4ccd794",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":56,
              "y":412},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98e61340f1bc4c4e9f105fba6eaae051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":412},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99803cefa3f64dc6b8d3b0d6ffcf66e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":189},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1beb2ca1edc74cfaaf6d82cd277cfa49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":189},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af394fa2028449fd85cdf447194a58ac",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":522},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"571bcb418f864b4da1bb855ecb756f39",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":56,
              "y":439},
            "size":{
              "width":65,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6695d3320f342e8bd9ceaac805cc671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":56,
                  "y":439},
                "size":{
                  "width":65,
                  "height":19},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1b735dc478e49069af4efa23998189a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":499},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d72f6164358248ec98fa350fc34480f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":499},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b49bbab645eb48c18b886e4650b7ca09",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":537},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da6a376e93849e28c08df82e94a8977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":537},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf315b9eddf74d708e53495f42213022",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":565},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b54c2aa6d8470bb243c30a449d6fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":565},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd3eca2c50ea45a291d8715baae18ba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":594},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e4a2b620d6419fb23cf0345906af9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":594},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ba6869c09e74322be13ecb6e4b08a51",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":623},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97ba1e4c6b1243a586382dc27642b6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":623},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48fe2d6f1bbc4eefa7ad57acf26accd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":468},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efde019e86e14e02b3f009c58d4e9901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":468},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd5401e3f0bd4dca9d7d378db3d4f690",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":240},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7074e925cad47d8a63ab11554eb29d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":240},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e9cd003ca1643958c8d57ab6efeacf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":265},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74a616ab4a6f4b75a5c165dc12cca033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":265},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53d200e54f804d0ab20d5553ca3f8d12",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"14e7a2254242401f96190d930cb7e731",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":308},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b32fd97328b4dcaa3f553e66f0134c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":308},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28ef787e398d4975be3eb8ee63eb7c5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":61,
              "y":214},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9352eab25b8648be9bc4e5132ad5545c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":214},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68217973106f472cad72da8412dabb96",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":61,
              "y":337},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d50716af9a47a2916219304b6d8358",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":337},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f84d5dfb85a44b4dbaf3053ac9c07756",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":651},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"1ca1fc8eee4f4922ad638681d62b2b00",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":666},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"588e612f28234cc3aaa49c55342e4b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":666},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c0998c620f394c97b6744f64d2800642",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":694},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be61ad01217e4fb38791eb6481cbf3a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":694},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2ebd4b7ec12401fadcc40156730a495",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":723},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8848165d3949436ea0832d2ccc56779e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":723},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"312eb2cb1c8c4a55979063904c290846",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":752},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1e961c1e12c4162b59b3dab8c3fea8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":752},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4826cc3bed13421e9613c4d9eb02512e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":781},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd8213fea6884f4c939247c87488489f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":781},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"567481040a394212a79b3bf3b761155e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":809},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91a4b88b55d641eb82d710774e09bdbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":809},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebb09d25ac3246488b1f33adcdfa7e66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":135},
            "size":{
              "width":820,
              "height":397}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d22e19b65c6d4bbfb3a8b6e0ff2c5b76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":135},
                "size":{
                  "width":820,
                  "height":397}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u59.png"}},
{
          "id":"999e9e7cc68440378f241364dd569e88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":230,
              "y":135},
            "size":{
              "width":820,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d9a01cfc8f44bd18be27e0574ea7ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":230,
                  "y":135},
                "size":{
                  "width":820,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u61.png"}},
{
          "id":"1b8c2a5dd8074b8c87f32a35946789c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":146},
            "size":{
              "width":112,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d9575e594064fd5a839150b1137ef03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":146},
                "size":{
                  "width":112,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5901b76516a5423a8150bfe348cb7e2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":449,
              "y":137},
            "size":{
              "width":187,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"443282418d2c4b72922c79107119280b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":449,
                  "y":137},
                "size":{
                  "width":187,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费统计/u65.png"}},
{
          "id":"412fef71ea7e41dca32cc3644204e136",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":180},
            "size":{
              "width":820,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64e285e1b4344614929db6299360d9b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":180},
                "size":{
                  "width":820,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费分布/u67.png"}},
{
          "id":"797dcce2ae094a83905cb6f73e64bb8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":190},
            "size":{
              "width":49,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f71281935cd74c539c64c67fb6fbeb2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":190},
                "size":{
                  "width":49,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc8f3d2c2f474bac92350e1e50017507",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":190},
            "size":{
              "width":87,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beeeb9e0f8ac4531b0356e97a26fe4d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":190},
                "size":{
                  "width":87,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"551374b809a14d4786d778ca147cfcca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":189},
            "size":{
              "width":87,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0052c37e94254729ab84d60bdf71dadd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":189},
                "size":{
                  "width":87,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adb49f35df894768873c9f803ea2c8b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":596,
              "y":189},
            "size":{
              "width":87,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeda429775894c1a8578ed421059c831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":596,
                  "y":189},
                "size":{
                  "width":87,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eb9261a5cab40b79ef9e232255efcf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":722,
              "y":189},
            "size":{
              "width":87,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"049281a7e7034ad591c316c42015b92b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":722,
                  "y":189},
                "size":{
                  "width":87,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6b3cbbcf8f044d4a426d00075a7d7c8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":244},
            "size":{
              "width":800,
              "height":267}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0d9d3bad7c944318e1ea5492034cbfe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":244},
                "size":{
                  "width":800,
                  "height":267}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消费分布/u79.png"}},
{
          "id":"fe358d1238474332a5c6cdba5b26f022",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":550},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c7a7490b5d1436d9829f2041bdfa8d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":550},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"973daf1f81c4479ca53cc5ecf8c7ff54",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":587.5},
            "size":{
              "width":500,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b0e69f2e43f4ab48f3bfe47d8665583",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fbb33595ca642889957056a9ae7c355",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u84.png"}},
{
              "id":"dedccc87583f4d588e21750d3214840c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":29},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e7b5a2e69d244621a8c453aefd245b08",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":29},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u94.png"}},
{
              "id":"5b99579f042145ec95e417d20879f72c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":59},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"671a4ad0e69e4a7483663415e88bd49a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u104.png"}},
{
              "id":"55e980e62b514c3fbfd1ec056557203f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49dfc4ec3c9646358d97d3f5f2cbd106",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u84.png"}},
{
              "id":"37c3eff0812a428abfc5b513f4cff0a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":29},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8ee1a84fff8425c857e11437d6207bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":29},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u94.png"}},
{
              "id":"60ccaba150c147a1a903f6ca2ee71945",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":59},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"37e8d6fb716b4051bf891b94c3ee625f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":59},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u104.png"}},
{
              "id":"c9fc121554344e9c9c8249bda90f3b1a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"934a6ef95c3d409ba550fcb4801ac02d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u84.png"}},
{
              "id":"c920dd8c4ea34acb885f674771b84360",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":29},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"472b3b1f994948c7969d3325e37258b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":29},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u94.png"}},
{
              "id":"c107a6e909a1446bb6bba055f29c594e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":59},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ddd4cfbcfea54e869644beb6f7c03864",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":59},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u104.png"}},
{
              "id":"58638abc327147e090ec7d4980df17f3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":0},
                "size":{
                  "width":100,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4d9da2dbb4f44314afdcd72cc229894f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u84.png"}},
{
              "id":"34a28c0ab50340a8a95e8e87484d9875",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":29},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f55fdc7168a54ea7805ff9c6a1f3f8c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":29},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u94.png"}},
{
              "id":"d1e0e67319a54145b152301568dd807c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":300,
                  "y":59},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f9c4375708d4cd2a743e97224ef34c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":300,
                      "y":59},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u104.png"}},
{
              "id":"902e74015a7c47079e2a85c3ae2a5010",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":0},
                "size":{
                  "width":100,
                  "height":29}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8162f49acd445ae8fbd4ee42614fafe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":29}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u92.png"}},
{
              "id":"d911f9385fbd48b9a36226e3a4c459f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":29},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de0414abc5a447e9bb97383a30b7f93e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":29},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u102.png"}},
{
              "id":"0e2e21954864433ca7b91da728e35375",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":59},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"61164a74734d42728ea29e336ccd9562",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":59},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/消费分布/u112.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "7eecad3adbf74024ba5ec19451d93bf4":{
      "scriptId":"u0"},
    "72b1d5bd589f40f09dd5d273e771128d":{
      "scriptId":"u1"},
    "fbe47dbdd3154105929c6f799ec1adcf":{
      "scriptId":"u2"},
    "97b262d6ff91498db5d847a774c90d07":{
      "scriptId":"u3"},
    "6fad2fd54aff4188a1aaa7736cc298aa":{
      "scriptId":"u4"},
    "4adb153efbe744f09c00c3c3b2286d27":{
      "scriptId":"u5"},
    "263729c84982434d9def458428e1142c":{
      "scriptId":"u6"},
    "77015ca1a435492da968396964cb6d92":{
      "scriptId":"u7"},
    "8554197841d64f76834f970161a0f719":{
      "scriptId":"u8"},
    "97e7e3e78fe14bc58edabb2f5b7db800":{
      "scriptId":"u9"},
    "8fa5c0fdb1dc4282b86c41458f6fa62f":{
      "scriptId":"u10"},
    "906f5c6a1fe04a2b8833bf6d0c3a2ce0":{
      "scriptId":"u11"},
    "4afd86c09b8e497d8b0e2dba7868d01d":{
      "scriptId":"u12"},
    "eacfd7a92b904a6d9c6b5c1b7fc970f1":{
      "scriptId":"u13"},
    "f693b4bd555f44098ac2f59722975ea9":{
      "scriptId":"u14"},
    "e34bf17539884b2aa77acbe86bd3df91":{
      "scriptId":"u15"},
    "7d656dcc89c643fd84469636b4ccd794":{
      "scriptId":"u16"},
    "98e61340f1bc4c4e9f105fba6eaae051":{
      "scriptId":"u17"},
    "99803cefa3f64dc6b8d3b0d6ffcf66e8":{
      "scriptId":"u18"},
    "1beb2ca1edc74cfaaf6d82cd277cfa49":{
      "scriptId":"u19"},
    "af394fa2028449fd85cdf447194a58ac":{
      "scriptId":"u20"},
    "571bcb418f864b4da1bb855ecb756f39":{
      "scriptId":"u21"},
    "e6695d3320f342e8bd9ceaac805cc671":{
      "scriptId":"u22"},
    "f1b735dc478e49069af4efa23998189a":{
      "scriptId":"u23"},
    "d72f6164358248ec98fa350fc34480f7":{
      "scriptId":"u24"},
    "b49bbab645eb48c18b886e4650b7ca09":{
      "scriptId":"u25"},
    "5da6a376e93849e28c08df82e94a8977":{
      "scriptId":"u26"},
    "bf315b9eddf74d708e53495f42213022":{
      "scriptId":"u27"},
    "87b54c2aa6d8470bb243c30a449d6fbb":{
      "scriptId":"u28"},
    "bd3eca2c50ea45a291d8715baae18ba3":{
      "scriptId":"u29"},
    "14e4a2b620d6419fb23cf0345906af9b":{
      "scriptId":"u30"},
    "3ba6869c09e74322be13ecb6e4b08a51":{
      "scriptId":"u31"},
    "97ba1e4c6b1243a586382dc27642b6d0":{
      "scriptId":"u32"},
    "48fe2d6f1bbc4eefa7ad57acf26accd2":{
      "scriptId":"u33"},
    "efde019e86e14e02b3f009c58d4e9901":{
      "scriptId":"u34"},
    "fd5401e3f0bd4dca9d7d378db3d4f690":{
      "scriptId":"u35"},
    "a7074e925cad47d8a63ab11554eb29d9":{
      "scriptId":"u36"},
    "4e9cd003ca1643958c8d57ab6efeacf2":{
      "scriptId":"u37"},
    "74a616ab4a6f4b75a5c165dc12cca033":{
      "scriptId":"u38"},
    "53d200e54f804d0ab20d5553ca3f8d12":{
      "scriptId":"u39"},
    "14e7a2254242401f96190d930cb7e731":{
      "scriptId":"u40"},
    "1b32fd97328b4dcaa3f553e66f0134c2":{
      "scriptId":"u41"},
    "28ef787e398d4975be3eb8ee63eb7c5f":{
      "scriptId":"u42"},
    "9352eab25b8648be9bc4e5132ad5545c":{
      "scriptId":"u43"},
    "68217973106f472cad72da8412dabb96":{
      "scriptId":"u44"},
    "c4d50716af9a47a2916219304b6d8358":{
      "scriptId":"u45"},
    "f84d5dfb85a44b4dbaf3053ac9c07756":{
      "scriptId":"u46"},
    "1ca1fc8eee4f4922ad638681d62b2b00":{
      "scriptId":"u47"},
    "588e612f28234cc3aaa49c55342e4b91":{
      "scriptId":"u48"},
    "c0998c620f394c97b6744f64d2800642":{
      "scriptId":"u49"},
    "be61ad01217e4fb38791eb6481cbf3a5":{
      "scriptId":"u50"},
    "f2ebd4b7ec12401fadcc40156730a495":{
      "scriptId":"u51"},
    "8848165d3949436ea0832d2ccc56779e":{
      "scriptId":"u52"},
    "312eb2cb1c8c4a55979063904c290846":{
      "scriptId":"u53"},
    "a1e961c1e12c4162b59b3dab8c3fea8b":{
      "scriptId":"u54"},
    "4826cc3bed13421e9613c4d9eb02512e":{
      "scriptId":"u55"},
    "bd8213fea6884f4c939247c87488489f":{
      "scriptId":"u56"},
    "567481040a394212a79b3bf3b761155e":{
      "scriptId":"u57"},
    "91a4b88b55d641eb82d710774e09bdbe":{
      "scriptId":"u58"},
    "ebb09d25ac3246488b1f33adcdfa7e66":{
      "scriptId":"u59"},
    "d22e19b65c6d4bbfb3a8b6e0ff2c5b76":{
      "scriptId":"u60"},
    "999e9e7cc68440378f241364dd569e88":{
      "scriptId":"u61"},
    "9d9a01cfc8f44bd18be27e0574ea7ae1":{
      "scriptId":"u62"},
    "1b8c2a5dd8074b8c87f32a35946789c6":{
      "scriptId":"u63"},
    "5d9575e594064fd5a839150b1137ef03":{
      "scriptId":"u64"},
    "5901b76516a5423a8150bfe348cb7e2a":{
      "scriptId":"u65"},
    "443282418d2c4b72922c79107119280b":{
      "scriptId":"u66"},
    "412fef71ea7e41dca32cc3644204e136":{
      "scriptId":"u67"},
    "64e285e1b4344614929db6299360d9b1":{
      "scriptId":"u68"},
    "797dcce2ae094a83905cb6f73e64bb8b":{
      "scriptId":"u69"},
    "f71281935cd74c539c64c67fb6fbeb2d":{
      "scriptId":"u70"},
    "cc8f3d2c2f474bac92350e1e50017507":{
      "scriptId":"u71"},
    "beeeb9e0f8ac4531b0356e97a26fe4d3":{
      "scriptId":"u72"},
    "551374b809a14d4786d778ca147cfcca":{
      "scriptId":"u73"},
    "0052c37e94254729ab84d60bdf71dadd":{
      "scriptId":"u74"},
    "adb49f35df894768873c9f803ea2c8b1":{
      "scriptId":"u75"},
    "aeda429775894c1a8578ed421059c831":{
      "scriptId":"u76"},
    "5eb9261a5cab40b79ef9e232255efcf2":{
      "scriptId":"u77"},
    "049281a7e7034ad591c316c42015b92b":{
      "scriptId":"u78"},
    "b6b3cbbcf8f044d4a426d00075a7d7c8":{
      "scriptId":"u79"},
    "c0d9d3bad7c944318e1ea5492034cbfe":{
      "scriptId":"u80"},
    "fe358d1238474332a5c6cdba5b26f022":{
      "scriptId":"u81"},
    "7c7a7490b5d1436d9829f2041bdfa8d9":{
      "scriptId":"u82"},
    "973daf1f81c4479ca53cc5ecf8c7ff54":{
      "scriptId":"u83"},
    "6b0e69f2e43f4ab48f3bfe47d8665583":{
      "scriptId":"u84"},
    "1fbb33595ca642889957056a9ae7c355":{
      "scriptId":"u85"},
    "55e980e62b514c3fbfd1ec056557203f":{
      "scriptId":"u86"},
    "49dfc4ec3c9646358d97d3f5f2cbd106":{
      "scriptId":"u87"},
    "c9fc121554344e9c9c8249bda90f3b1a":{
      "scriptId":"u88"},
    "934a6ef95c3d409ba550fcb4801ac02d":{
      "scriptId":"u89"},
    "58638abc327147e090ec7d4980df17f3":{
      "scriptId":"u90"},
    "4d9da2dbb4f44314afdcd72cc229894f":{
      "scriptId":"u91"},
    "902e74015a7c47079e2a85c3ae2a5010":{
      "scriptId":"u92"},
    "d8162f49acd445ae8fbd4ee42614fafe":{
      "scriptId":"u93"},
    "dedccc87583f4d588e21750d3214840c":{
      "scriptId":"u94"},
    "e7b5a2e69d244621a8c453aefd245b08":{
      "scriptId":"u95"},
    "37c3eff0812a428abfc5b513f4cff0a7":{
      "scriptId":"u96"},
    "b8ee1a84fff8425c857e11437d6207bb":{
      "scriptId":"u97"},
    "c920dd8c4ea34acb885f674771b84360":{
      "scriptId":"u98"},
    "472b3b1f994948c7969d3325e37258b4":{
      "scriptId":"u99"},
    "34a28c0ab50340a8a95e8e87484d9875":{
      "scriptId":"u100"},
    "f55fdc7168a54ea7805ff9c6a1f3f8c3":{
      "scriptId":"u101"},
    "d911f9385fbd48b9a36226e3a4c459f7":{
      "scriptId":"u102"},
    "de0414abc5a447e9bb97383a30b7f93e":{
      "scriptId":"u103"},
    "5b99579f042145ec95e417d20879f72c":{
      "scriptId":"u104"},
    "671a4ad0e69e4a7483663415e88bd49a":{
      "scriptId":"u105"},
    "60ccaba150c147a1a903f6ca2ee71945":{
      "scriptId":"u106"},
    "37e8d6fb716b4051bf891b94c3ee625f":{
      "scriptId":"u107"},
    "c107a6e909a1446bb6bba055f29c594e":{
      "scriptId":"u108"},
    "ddd4cfbcfea54e869644beb6f7c03864":{
      "scriptId":"u109"},
    "d1e0e67319a54145b152301568dd807c":{
      "scriptId":"u110"},
    "3f9c4375708d4cd2a743e97224ef34c9":{
      "scriptId":"u111"},
    "0e2e21954864433ca7b91da728e35375":{
      "scriptId":"u112"},
    "61164a74734d42728ea29e336ccd9562":{
      "scriptId":"u113"}}});