$axure.loadCurrentPage({
  "url":"商家登陆.html",
  "generationDate":new Date(1442542995933.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2bbf65630b774bb581b3e10b90383b2c",
    "type":"Axure:Page",
    "name":"商家登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6499b52c216d460ca3404bd693f98c87",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-93,
              "y":0},
            "size":{
              "width":1413,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad06aa34d7c449d28ea2c87b81cb88e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-93,
                  "y":0},
                "size":{
                  "width":1413,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u0.png"}},
{
          "id":"5508f195a559468ab134c4deff2c3a4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":10},
            "size":{
              "width":440,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea26c91c94e64458ba14ed7e5e4f3e8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":10},
                "size":{
                  "width":440,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u2.png"}},
{
          "id":"26275ce4a96c49f48ccf6c8d1e1244eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":247,
              "y":21},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edf09f5d2684410e8636c0b40153930b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":247,
                  "y":21},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30aa987afea94972837b2789ef953c62",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":100},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4debfeb79cdb441bb6b3e78fc8fdb7ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":100},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64a95e2c571d45f2b30e5d7c012d57ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":300,
              "y":190},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0e677d655e4bb6aa4019d7e72c9287",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":300,
                  "y":190},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ad2d6dd186048589542219aec2f023e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":186},
            "size":{
              "width":313,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1a3aa7e31ae3438cab81a7a4716a375e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":300,
              "y":225},
            "size":{
              "width":59,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"666eeca0ac9f47e5bce5d00cac2b0d47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":300,
                  "y":225},
                "size":{
                  "width":59,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"43ad6e2117c84194b112d2bcad78dcfc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":221},
            "size":{
              "width":313,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"02225c9b23c64402ac3bc85dae3f488a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":295},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"969d33925f4149e084f69e09050d2439",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":563.5,
              "y":295},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dd33c85bca974eb19d60386ac3cd2cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":608,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec13a89cfa944b4cad1def8c803c9de2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":608,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6499b52c216d460ca3404bd693f98c87":{
      "scriptId":"u0"},
    "ad06aa34d7c449d28ea2c87b81cb88e8":{
      "scriptId":"u1"},
    "5508f195a559468ab134c4deff2c3a4f":{
      "scriptId":"u2"},
    "ea26c91c94e64458ba14ed7e5e4f3e8b":{
      "scriptId":"u3"},
    "26275ce4a96c49f48ccf6c8d1e1244eb":{
      "scriptId":"u4"},
    "edf09f5d2684410e8636c0b40153930b":{
      "scriptId":"u5"},
    "30aa987afea94972837b2789ef953c62":{
      "scriptId":"u6"},
    "4debfeb79cdb441bb6b3e78fc8fdb7ee":{
      "scriptId":"u7"},
    "64a95e2c571d45f2b30e5d7c012d57ac":{
      "scriptId":"u8"},
    "ce0e677d655e4bb6aa4019d7e72c9287":{
      "scriptId":"u9"},
    "7ad2d6dd186048589542219aec2f023e":{
      "scriptId":"u10"},
    "1a3aa7e31ae3438cab81a7a4716a375e":{
      "scriptId":"u11"},
    "666eeca0ac9f47e5bce5d00cac2b0d47":{
      "scriptId":"u12"},
    "43ad6e2117c84194b112d2bcad78dcfc":{
      "scriptId":"u13"},
    "02225c9b23c64402ac3bc85dae3f488a":{
      "scriptId":"u14"},
    "969d33925f4149e084f69e09050d2439":{
      "scriptId":"u15"},
    "dd33c85bca974eb19d60386ac3cd2cb2":{
      "scriptId":"u16"},
    "ec13a89cfa944b4cad1def8c803c9de2":{
      "scriptId":"u17"}}});