$axure.loadCurrentPage({
  "url":"我的订单.html",
  "generationDate":new Date(1442543003141.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4912832ab8474a88b9e5c1bde5315f75",
    "type":"Axure:Page",
    "name":"我的订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab9d185bfd934bc1918eae1b51c79fd8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1795ee845ccb46278f35f07c83523573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"7a50e2af01a24361a2e38a82978b9e13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":120},
            "size":{
              "width":173,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5806b1de4acb4da1a8a1e4a171bca58d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":120},
                "size":{
                  "width":173,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u35.png"}},
{
          "id":"84aa12796c4042f8bda75f0082ebef67",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"104c7f4164ee41e5adeb5c42f532289a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u37.png"}},
{
          "id":"07038b6967f34dbdb8a92b79c5429537",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":59,
              "y":150},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7103e02d84914514af57f629c43eb9bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":59,
                  "y":150},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38848eb70ce042398f6a7ab03392f44f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":268},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"f7a7d7b0fbec44808388ec733f6a5051",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":278},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"075c712b0b9b4a00a259d1f8a327e199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":278},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8714849733414347bb6b4bf084362294",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":306},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10dd43ec100b4d7b8cd28a9cf6fe0c46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":306},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cb69ebcf8504c4b9416834a54d9d0ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":335},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9ef7ec9a6f74ba59d2e61bb32ad790a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":335},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ae8eb55a42d4a51b66126529e79803a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":364},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457cb31a167d49cda8aa2cd5489e23c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":364},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f22ad1697efb4f02b7f03eafcd18ba90",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":393},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"39a321cf34634915a93e1b88cca02214",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":411},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3d95f11b4444208b87c995be48a4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":411},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83eba40e464f4b04be050ca8490f8419",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":61,
              "y":207},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fde42b9bde740798e0d6ddf9712a96d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":207},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5454a657a47b4a9cb28b7c26cf220710",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":440},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f43b315a4fc4836b215922948cd51ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":440},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30cf0c0f27fd40de9aeb4e415f1d830a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":178},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"840c45afdadd4441a76732d22960e42e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":178},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44038e95afda47dfa94527e54eb59474",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":554},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"67a121e659534a1e8ee68233931c0db4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":467},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d6651b83ec41e7b414ad2acb2d6cb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":467},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c91a10f6d1142ca87b4035ad68763a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":527},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38f80b4dc4ed4cb49818e2f63bd9b8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":527},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9d91ee90cf443379679d5c29952602a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":569},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62d2fd8d06204c88920c8dc75c064fcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":569},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aac36535e8ae4d86a6f55c3371063506",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":597},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab1f32428e2a492298f17b1a24a3ed13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":597},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b2ed652dbc84498942a47fce9fd7868",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":626},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73bdfd536f4542b893b843676f5cf8fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":626},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7112afc64ecb4315905f663e15292b17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":655},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9180974e33814f3a826248c6f7c04445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":655},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a3daca83fe04006a718b5492ec8851e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":684},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5adccd0d966849249888c1c153bd422e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":684},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d95e3e86563446493f7845e177b7ed4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8e91fb5e09d475197f30d709b039582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88d937df56e74e80ba393f2907c5ae9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"57f92082a8714fd196bbe09737b12746",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":496},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15fa8fe16cd41c7b6987531ac596fe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":496},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a326e03498be43dfa5b1fd08810b7055",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":232,
              "y":284},
            "size":{
              "width":143,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f016bca19c39473fa338df6574ffd966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":232,
                  "y":284},
                "size":{
                  "width":143,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e326083ee0e24e16b7433156fa28b1f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84e7d69415a2429fa568450547850f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f09684ca78a542869ea4393097232d54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":277},
            "size":{
              "width":23,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181732be1a3b4d4d88b61c4bee66af06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":277},
                "size":{
                  "width":23,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u23.png"}},
{
          "id":"1e647bca1ae443aebeac2e95d46567a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":418,
              "y":280},
            "size":{
              "width":240,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb642bca53b342139030e7ad15670c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":418,
                  "y":280},
                "size":{
                  "width":240,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94b90c47fa524411a5ec4817290dd137",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":304},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad314ac1e6e435c96dc0653da6ffe26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":304},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"675c30f836e74755816147da87899af2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":688,
              "y":284},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d223c67f013460798289963681d4e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":688,
                  "y":284},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b14c5731390477898f3beb7e75f5bb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":816,
              "y":287},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da4525ccc7f04ede8af9c95c1dd928d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":816,
                  "y":287},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87634589df1e4f17b5fbb3c5cfa108bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":986,
              "y":286},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faff2aae65574f3a909f9289052026b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":986,
                  "y":286},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"382856a0072947139f8a0b8fb32ac2e4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":332},
            "size":{
              "width":783,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的账户/u35_line.png"}},
{
          "id":"6e5155427d494b619738ae02fa642abf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":418,
              "y":363},
            "size":{
              "width":9,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c7651658224f9d8ae141adf6fcc4b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":418,
                  "y":363},
                "size":{
                  "width":9,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74ba10961b514f13b66465503ff1238d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":387},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966dd7b8b7b943fdb01e8fc6d89d0dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":387},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55d197d08cfc4127b0cc78a6f9d21b78",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":688,
              "y":367},
            "size":{
              "width":62,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e150ebedab7d4b8d92b9600b66091c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":688,
                  "y":367},
                "size":{
                  "width":62,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4238be098024aa6b08ca61f363e5124",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":816,
              "y":370},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"016436ac18924b8f91a80b484ce133c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":816,
                  "y":370},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2d56d053504499f98f782bb53ec9495",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":986,
              "y":369},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"febde3238cac4b079205e9b9f540f55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":986,
                  "y":369},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e9ef32f00c34f41a18223cada9aa8fe",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":415},
            "size":{
              "width":783,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的账户/u35_line.png"}},
{
          "id":"5e11563d04444351870db148d310edda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":390,
              "y":359},
            "size":{
              "width":19,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506a8c050a0d4f37b91316556f07ebc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":390,
                  "y":359},
                "size":{
                  "width":19,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u49.png"}},
{
          "id":"7981728207594a91bffccf08cb4a1d24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":419,
              "y":361},
            "size":{
              "width":212,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2992086504b94b56a0fbdba9ca870d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":419,
                  "y":361},
                "size":{
                  "width":212,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3596cbd176ce4f7cbf5c9227687ebba4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":236},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6197b09edd874b26b8a09ebd6900a609",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":236},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a994b82db1ec413998c77b83b77698d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":450,
              "y":144},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8694873240294369863459e59a32c369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":450,
                  "y":144},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c5774182bf4447b3975bb08f85f02cf8",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":531,
              "y":141},
            "size":{
              "width":121,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"873a61eafbd54ca1b53152fe0f7fe797",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":230,
              "y":143},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34c26aad91d943d1b6029025ffdfba44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":230,
                  "y":143},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23f1c058840c4191bfd5fb19c5479d07",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":311,
              "y":140},
            "size":{
              "width":121,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"d1e7facc2a2a470088ca8c38fd3cb55b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":145},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"791b724402a74bb4a4737830d98fb7e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":145},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"818f48006c0046f0a29d6aa2888327c0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":736,
              "y":129},
            "size":{
              "width":202,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cd424231c3640f39e1a2f40bbabc4c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":736,
                  "y":129},
                "size":{
                  "width":202,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u13.png"}},
{
          "id":"ecfa671a555646369bdb874258a4de10",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":232,
              "y":175},
            "size":{
              "width":420,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9309bf55882f40a69981c8bbc3163cfe",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":174},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fba90f92e1e84ce8ba7f98581ec68aef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":237,
              "y":358},
            "size":{
              "width":143,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f64ba2512ebd4d239a32336d817b3ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":237,
                  "y":358},
                "size":{
                  "width":143,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93865013f85d4d9cb2a8af5982bcb310",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":216},
            "size":{
              "width":783,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的任务/u17_line.png"}},
{
          "id":"4ca84f73f248496b94c9a1f3ecb19390",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":250,
              "y":227},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce2011ce46e64e9486daa0aada57d72e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":250,
                  "y":227},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"326232c03e3747abaae8d7f1a0c07565",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":485,
              "y":227},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c6e893dec604a0a9eb23e43adb43409",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":485,
                  "y":227},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"512482a48c0e453aa5d7eb380c755b8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":717,
              "y":227},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c729e379b9f04d04998cd4a85d697202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":717,
                  "y":227},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a8af3c275d4bb08a6b9f692fdd5bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":830,
              "y":227},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f05a509eb0884e5289dea7f0fcb3554a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":830,
                  "y":227},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11c1f95301fc4c14b7244d2d308b4e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":980,
              "y":227},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6545c64259d544cf926c85f338493a3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":980,
                  "y":227},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aab0254815e4f41bf45bf1cb9e71b08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":434},
            "size":{
              "width":257,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9452e844d34f492088c8b8eefeb15ef2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":434},
                "size":{
                  "width":257,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的订单/u105.png"}},
{
          "id":"ff0c59d3998a40a9af1b9b1112419286",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":925,
              "y":435},
            "size":{
              "width":103,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd4f9e282669480db728ffebd2eff964",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":925,
                  "y":435},
                "size":{
                  "width":103,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u18.png"}},
{
          "id":"0f47b1cebf944ce1bac4ccc599a926da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":460,
              "y":527},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b684154c139e49e5aba136406d24ad6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":527},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ab9d185bfd934bc1918eae1b51c79fd8":{
      "scriptId":"u0"},
    "1795ee845ccb46278f35f07c83523573":{
      "scriptId":"u1"},
    "7a50e2af01a24361a2e38a82978b9e13":{
      "scriptId":"u2"},
    "5806b1de4acb4da1a8a1e4a171bca58d":{
      "scriptId":"u3"},
    "84aa12796c4042f8bda75f0082ebef67":{
      "scriptId":"u4"},
    "104c7f4164ee41e5adeb5c42f532289a":{
      "scriptId":"u5"},
    "07038b6967f34dbdb8a92b79c5429537":{
      "scriptId":"u6"},
    "7103e02d84914514af57f629c43eb9bc":{
      "scriptId":"u7"},
    "38848eb70ce042398f6a7ab03392f44f":{
      "scriptId":"u8"},
    "f7a7d7b0fbec44808388ec733f6a5051":{
      "scriptId":"u9"},
    "075c712b0b9b4a00a259d1f8a327e199":{
      "scriptId":"u10"},
    "8714849733414347bb6b4bf084362294":{
      "scriptId":"u11"},
    "10dd43ec100b4d7b8cd28a9cf6fe0c46":{
      "scriptId":"u12"},
    "4cb69ebcf8504c4b9416834a54d9d0ce":{
      "scriptId":"u13"},
    "f9ef7ec9a6f74ba59d2e61bb32ad790a":{
      "scriptId":"u14"},
    "1ae8eb55a42d4a51b66126529e79803a":{
      "scriptId":"u15"},
    "457cb31a167d49cda8aa2cd5489e23c3":{
      "scriptId":"u16"},
    "f22ad1697efb4f02b7f03eafcd18ba90":{
      "scriptId":"u17"},
    "39a321cf34634915a93e1b88cca02214":{
      "scriptId":"u18"},
    "5a3d95f11b4444208b87c995be48a4f9":{
      "scriptId":"u19"},
    "83eba40e464f4b04be050ca8490f8419":{
      "scriptId":"u20"},
    "9fde42b9bde740798e0d6ddf9712a96d":{
      "scriptId":"u21"},
    "5454a657a47b4a9cb28b7c26cf220710":{
      "scriptId":"u22"},
    "2f43b315a4fc4836b215922948cd51ca":{
      "scriptId":"u23"},
    "30cf0c0f27fd40de9aeb4e415f1d830a":{
      "scriptId":"u24"},
    "840c45afdadd4441a76732d22960e42e":{
      "scriptId":"u25"},
    "44038e95afda47dfa94527e54eb59474":{
      "scriptId":"u26"},
    "67a121e659534a1e8ee68233931c0db4":{
      "scriptId":"u27"},
    "e5d6651b83ec41e7b414ad2acb2d6cb7":{
      "scriptId":"u28"},
    "5c91a10f6d1142ca87b4035ad68763a9":{
      "scriptId":"u29"},
    "38f80b4dc4ed4cb49818e2f63bd9b8d6":{
      "scriptId":"u30"},
    "f9d91ee90cf443379679d5c29952602a":{
      "scriptId":"u31"},
    "62d2fd8d06204c88920c8dc75c064fcd":{
      "scriptId":"u32"},
    "aac36535e8ae4d86a6f55c3371063506":{
      "scriptId":"u33"},
    "ab1f32428e2a492298f17b1a24a3ed13":{
      "scriptId":"u34"},
    "4b2ed652dbc84498942a47fce9fd7868":{
      "scriptId":"u35"},
    "73bdfd536f4542b893b843676f5cf8fd":{
      "scriptId":"u36"},
    "7112afc64ecb4315905f663e15292b17":{
      "scriptId":"u37"},
    "9180974e33814f3a826248c6f7c04445":{
      "scriptId":"u38"},
    "6a3daca83fe04006a718b5492ec8851e":{
      "scriptId":"u39"},
    "5adccd0d966849249888c1c153bd422e":{
      "scriptId":"u40"},
    "1d95e3e86563446493f7845e177b7ed4":{
      "scriptId":"u41"},
    "b8e91fb5e09d475197f30d709b039582":{
      "scriptId":"u42"},
    "88d937df56e74e80ba393f2907c5ae9b":{
      "scriptId":"u43"},
    "57f92082a8714fd196bbe09737b12746":{
      "scriptId":"u44"},
    "e15fa8fe16cd41c7b6987531ac596fe7":{
      "scriptId":"u45"},
    "a326e03498be43dfa5b1fd08810b7055":{
      "scriptId":"u46"},
    "f016bca19c39473fa338df6574ffd966":{
      "scriptId":"u47"},
    "e326083ee0e24e16b7433156fa28b1f3":{
      "scriptId":"u48"},
    "84e7d69415a2429fa568450547850f4c":{
      "scriptId":"u49"},
    "f09684ca78a542869ea4393097232d54":{
      "scriptId":"u50"},
    "181732be1a3b4d4d88b61c4bee66af06":{
      "scriptId":"u51"},
    "1e647bca1ae443aebeac2e95d46567a8":{
      "scriptId":"u52"},
    "eb642bca53b342139030e7ad15670c70":{
      "scriptId":"u53"},
    "94b90c47fa524411a5ec4817290dd137":{
      "scriptId":"u54"},
    "8ad314ac1e6e435c96dc0653da6ffe26":{
      "scriptId":"u55"},
    "675c30f836e74755816147da87899af2":{
      "scriptId":"u56"},
    "7d223c67f013460798289963681d4e76":{
      "scriptId":"u57"},
    "1b14c5731390477898f3beb7e75f5bb9":{
      "scriptId":"u58"},
    "da4525ccc7f04ede8af9c95c1dd928d6":{
      "scriptId":"u59"},
    "87634589df1e4f17b5fbb3c5cfa108bc":{
      "scriptId":"u60"},
    "faff2aae65574f3a909f9289052026b5":{
      "scriptId":"u61"},
    "382856a0072947139f8a0b8fb32ac2e4":{
      "scriptId":"u62"},
    "6e5155427d494b619738ae02fa642abf":{
      "scriptId":"u63"},
    "11c7651658224f9d8ae141adf6fcc4b7":{
      "scriptId":"u64"},
    "74ba10961b514f13b66465503ff1238d":{
      "scriptId":"u65"},
    "966dd7b8b7b943fdb01e8fc6d89d0dc6":{
      "scriptId":"u66"},
    "55d197d08cfc4127b0cc78a6f9d21b78":{
      "scriptId":"u67"},
    "e150ebedab7d4b8d92b9600b66091c58":{
      "scriptId":"u68"},
    "c4238be098024aa6b08ca61f363e5124":{
      "scriptId":"u69"},
    "016436ac18924b8f91a80b484ce133c5":{
      "scriptId":"u70"},
    "e2d56d053504499f98f782bb53ec9495":{
      "scriptId":"u71"},
    "febde3238cac4b079205e9b9f540f55e":{
      "scriptId":"u72"},
    "0e9ef32f00c34f41a18223cada9aa8fe":{
      "scriptId":"u73"},
    "5e11563d04444351870db148d310edda":{
      "scriptId":"u74"},
    "506a8c050a0d4f37b91316556f07ebc3":{
      "scriptId":"u75"},
    "7981728207594a91bffccf08cb4a1d24":{
      "scriptId":"u76"},
    "2992086504b94b56a0fbdba9ca870d10":{
      "scriptId":"u77"},
    "3596cbd176ce4f7cbf5c9227687ebba4":{
      "scriptId":"u78"},
    "6197b09edd874b26b8a09ebd6900a609":{
      "scriptId":"u79"},
    "a994b82db1ec413998c77b83b77698d5":{
      "scriptId":"u80"},
    "8694873240294369863459e59a32c369":{
      "scriptId":"u81"},
    "c5774182bf4447b3975bb08f85f02cf8":{
      "scriptId":"u82"},
    "873a61eafbd54ca1b53152fe0f7fe797":{
      "scriptId":"u83"},
    "34c26aad91d943d1b6029025ffdfba44":{
      "scriptId":"u84"},
    "23f1c058840c4191bfd5fb19c5479d07":{
      "scriptId":"u85"},
    "d1e7facc2a2a470088ca8c38fd3cb55b":{
      "scriptId":"u86"},
    "791b724402a74bb4a4737830d98fb7e4":{
      "scriptId":"u87"},
    "818f48006c0046f0a29d6aa2888327c0":{
      "scriptId":"u88"},
    "5cd424231c3640f39e1a2f40bbabc4c0":{
      "scriptId":"u89"},
    "ecfa671a555646369bdb874258a4de10":{
      "scriptId":"u90"},
    "9309bf55882f40a69981c8bbc3163cfe":{
      "scriptId":"u91"},
    "fba90f92e1e84ce8ba7f98581ec68aef":{
      "scriptId":"u92"},
    "f64ba2512ebd4d239a32336d817b3ddc":{
      "scriptId":"u93"},
    "93865013f85d4d9cb2a8af5982bcb310":{
      "scriptId":"u94"},
    "4ca84f73f248496b94c9a1f3ecb19390":{
      "scriptId":"u95"},
    "ce2011ce46e64e9486daa0aada57d72e":{
      "scriptId":"u96"},
    "326232c03e3747abaae8d7f1a0c07565":{
      "scriptId":"u97"},
    "2c6e893dec604a0a9eb23e43adb43409":{
      "scriptId":"u98"},
    "512482a48c0e453aa5d7eb380c755b8a":{
      "scriptId":"u99"},
    "c729e379b9f04d04998cd4a85d697202":{
      "scriptId":"u100"},
    "16a8af3c275d4bb08a6b9f692fdd5bb7":{
      "scriptId":"u101"},
    "f05a509eb0884e5289dea7f0fcb3554a":{
      "scriptId":"u102"},
    "11c1f95301fc4c14b7244d2d308b4e80":{
      "scriptId":"u103"},
    "6545c64259d544cf926c85f338493a3d":{
      "scriptId":"u104"},
    "0aab0254815e4f41bf45bf1cb9e71b08":{
      "scriptId":"u105"},
    "9452e844d34f492088c8b8eefeb15ef2":{
      "scriptId":"u106"},
    "ff0c59d3998a40a9af1b9b1112419286":{
      "scriptId":"u107"},
    "bd4f9e282669480db728ffebd2eff964":{
      "scriptId":"u108"},
    "0f47b1cebf944ce1bac4ccc599a926da":{
      "scriptId":"u109"},
    "b684154c139e49e5aba136406d24ad6c":{
      "scriptId":"u110"}}});