$axure.loadCurrentPage({
  "url":"会员首页.html",
  "generationDate":new Date(1442542999006.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"864009d54dbe40d79cbf3112be0bddab",
    "type":"Axure:Page",
    "name":"会员首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"315bb7a1f8d34017b018f3fe2a85390d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3227f6d077d84001ab66cfae257d3519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"5ca502ba56794e01a4be294d9fcdf395",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea82da419bfe44e5a02555635a806f49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16abd753e7534c53b13f1692a6f3e187",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"db4a0f12bc62428390b083b2a085192c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":159},
            "size":{
              "width":108,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24aac5a916a04796aff5d25dd15d7774",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":159},
                "size":{
                  "width":108,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u5.png"}},
{
          "id":"43c0bcc295fa4990af7ba3171872a9e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":360,
              "y":196},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35484fbb9c4940418d250d03063eef9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":360,
                  "y":196},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b639393f1f34a2ba0b7f23a6f73defc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":166},
            "size":{
              "width":230,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"320ff13e394b4bff8a7a6a292ffcbd34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":166},
                "size":{
                  "width":230,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u9.png"}},
{
          "id":"6780c499dacb494499b3c6f620adf1ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":236,
              "y":301},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a590ad3a7cd4d5aa68717eed2436a60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":236,
                  "y":301},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf33af878a8e4f7cb4710703e18701b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":509,
              "y":184},
            "size":{
              "width":114,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"482027ffedc64059b70622d4e7c9e534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":509,
                  "y":184},
                "size":{
                  "width":114,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c407821efc64973870acb7fe9458c94",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":168},
            "size":{
              "width":10,
              "height":88}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u15_line.png"}},
{
          "id":"9010e4feb144498393c371c153a2a088",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":168},
            "size":{
              "width":10,
              "height":88}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u15_line.png"}},
{
          "id":"e745136b85ff4a53a198e709308290b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":230},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be00e08c3bc46f5abfe2eba7aa22d45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":230},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce2fa4ead3b6457e9c16855e6eb6b329",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":230},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd717d61e2024398847118a7d402ceb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":230},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e120fea0e43b4d44a42a0b452fb823d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":230},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"006a2a57ad5e4b89aa145bd225be668b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":230},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75a3cadbba22445a896c18ff95b51cbe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":339},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7672a8e498a046e4b3469572291eb426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":339},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u23.png"}},
{
          "id":"4ef94f441bec419ea98b99b0ee135856",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":268,
              "y":344},
            "size":{
              "width":347,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64e32bec2964444184ebf2c1bd412c64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":268,
                  "y":344},
                "size":{
                  "width":347,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e5a41950c4c4fc18f78ec9de79ac107",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":370},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8771f9d288454f25857d97138ed5fbe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":370},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u23.png"}},
{
          "id":"77e3384bd83f4fa08b2c0b3e24a466ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":268,
              "y":375},
            "size":{
              "width":257,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8edc7f757fec414491395704d702a884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":268,
                  "y":375},
                "size":{
                  "width":257,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40817b5a80b947899e071938e292ac97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":402},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70806ad65a634c40aefd65a87412700e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":402},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u23.png"}},
{
          "id":"e4073d9c798d4a85b73a6ec1e3036779",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":407},
            "size":{
              "width":393,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4e448f641054b38a7026b784d779aa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":407},
                "size":{
                  "width":393,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2083995e1ae4a3b80c271cb7c5fb725",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":124},
            "size":{
              "width":173,
              "height":726}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f463562d8a144a98c8b331baee5c38b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":124},
                "size":{
                  "width":173,
                  "height":726}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u35.png"}},
{
          "id":"04c80563ab434c22b9712cae7e9ab493",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc21edb345d43eaafb957e8f000d65e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u37.png"}},
{
          "id":"843dc1a76cd34000a481e5b9683059c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":59,
              "y":157},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8db1b263be764ac688a5e70c294663f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":157},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f12cc94190dd4a3cb5e2fabfc16f9e9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":365},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"c5bff3eecd1b474e8cf1c3ec19c1515e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":383},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d070eaf7f54492a746900c93a39fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":383},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"684461b3f4444108891bf089fef44ddf",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":412},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"306d9820c9fb40339f42e642a3871734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":412},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24ca72ccbbe542e090754fd5acbc1dc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":189},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c66f115f424b73bb1e43acfb645957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":189},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82366a4dd7d740f3927a1f764211e3c3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":522},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"7db5752ba3b54155ab5cf25e76e24183",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":439},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ed5727b47b24ba182824818207bbbf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":439},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7100990c705646049d979ac8b3caba92",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":499},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63d113fc356140d7af1d65fc54179773",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":499},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0990cc29127147f7862aaaa4f2bb66d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":537},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc63fa25b284b16a9d6257b0751f3f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":537},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"038fa61f42b647d290291a37216a27c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":565},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f3b9fa24ca64e41babe128818357d94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":565},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4315f1b17da4bada7ac9e234a6b189e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":594},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3010773183d64f0aac1e62007776ddb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":594},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4b95574a2bc4213854cd578023dbb6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":623},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c714f9bd61bf4a409e101dd9b7bbdd41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":623},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8e9cbc4eff541c79409f8031c0990ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":468},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dc2068bd93e41e88c2d27a1ff1c535d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":468},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71aad76bd066415b86a17dc63669a230",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":240},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"050f166afe854ca9bbe581fd13b69f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":240},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c166be164b53412ebdfbffac9c202c02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":265},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f3c54e6af2f423ba1e786df57b491bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":265},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59ae3baa34fa4f0f85a35f97a7407851",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"7316b7776710445fadd537144ed0fdb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":308},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60744fc4b3244bdfbe1cfe811aafbbae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":308},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fb61b3145204a31a41907140bf9c44c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":214},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa80e6f9b48745f0b2fda120b8bec6c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":214},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d23b24a432ad48b1b99992293765a73a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":337},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f9078c2949547ba811242c6500b0296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":337},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36802ee67d7f4a21b3058ffae80764ca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":651},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"d79371a705a14e79ac248c2a57ddc9e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":666},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5efd5598c74b44e88d784e1284a7a639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":666},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f354e9be8f6e4cd2add113e058fb461f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":694},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2d722d7febf490dac99cfbb831f7d85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":694},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"801b59253b1e4b2d88f486750ebbcd90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":723},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26d99a926fc044a9b7e9e97a3c52c03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":723},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5960b51bb2594894a844b6781aa8ea0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":752},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504af6bb6f8e4746be5bf2e57e3206aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":752},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e366c7e864c74c36bc7b368145f6dd7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":781},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97ea1e3c3e424aa9b5a1c9a5ab186ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":781},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d185c360afc4f7da0c84cf397d7b62f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":809},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe661a9f347342f58400d2fbcd2f5169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":809},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "315bb7a1f8d34017b018f3fe2a85390d":{
      "scriptId":"u0"},
    "3227f6d077d84001ab66cfae257d3519":{
      "scriptId":"u1"},
    "5ca502ba56794e01a4be294d9fcdf395":{
      "scriptId":"u2"},
    "ea82da419bfe44e5a02555635a806f49":{
      "scriptId":"u3"},
    "16abd753e7534c53b13f1692a6f3e187":{
      "scriptId":"u4"},
    "db4a0f12bc62428390b083b2a085192c":{
      "scriptId":"u5"},
    "24aac5a916a04796aff5d25dd15d7774":{
      "scriptId":"u6"},
    "43c0bcc295fa4990af7ba3171872a9e8":{
      "scriptId":"u7"},
    "35484fbb9c4940418d250d03063eef9f":{
      "scriptId":"u8"},
    "2b639393f1f34a2ba0b7f23a6f73defc":{
      "scriptId":"u9"},
    "320ff13e394b4bff8a7a6a292ffcbd34":{
      "scriptId":"u10"},
    "6780c499dacb494499b3c6f620adf1ba":{
      "scriptId":"u11"},
    "9a590ad3a7cd4d5aa68717eed2436a60":{
      "scriptId":"u12"},
    "cf33af878a8e4f7cb4710703e18701b1":{
      "scriptId":"u13"},
    "482027ffedc64059b70622d4e7c9e534":{
      "scriptId":"u14"},
    "9c407821efc64973870acb7fe9458c94":{
      "scriptId":"u15"},
    "9010e4feb144498393c371c153a2a088":{
      "scriptId":"u16"},
    "e745136b85ff4a53a198e709308290b3":{
      "scriptId":"u17"},
    "4be00e08c3bc46f5abfe2eba7aa22d45":{
      "scriptId":"u18"},
    "ce2fa4ead3b6457e9c16855e6eb6b329":{
      "scriptId":"u19"},
    "dd717d61e2024398847118a7d402ceb7":{
      "scriptId":"u20"},
    "e120fea0e43b4d44a42a0b452fb823d6":{
      "scriptId":"u21"},
    "006a2a57ad5e4b89aa145bd225be668b":{
      "scriptId":"u22"},
    "75a3cadbba22445a896c18ff95b51cbe":{
      "scriptId":"u23"},
    "7672a8e498a046e4b3469572291eb426":{
      "scriptId":"u24"},
    "4ef94f441bec419ea98b99b0ee135856":{
      "scriptId":"u25"},
    "64e32bec2964444184ebf2c1bd412c64":{
      "scriptId":"u26"},
    "2e5a41950c4c4fc18f78ec9de79ac107":{
      "scriptId":"u27"},
    "8771f9d288454f25857d97138ed5fbe8":{
      "scriptId":"u28"},
    "77e3384bd83f4fa08b2c0b3e24a466ce":{
      "scriptId":"u29"},
    "8edc7f757fec414491395704d702a884":{
      "scriptId":"u30"},
    "40817b5a80b947899e071938e292ac97":{
      "scriptId":"u31"},
    "70806ad65a634c40aefd65a87412700e":{
      "scriptId":"u32"},
    "e4073d9c798d4a85b73a6ec1e3036779":{
      "scriptId":"u33"},
    "f4e448f641054b38a7026b784d779aa6":{
      "scriptId":"u34"},
    "e2083995e1ae4a3b80c271cb7c5fb725":{
      "scriptId":"u35"},
    "4f463562d8a144a98c8b331baee5c38b":{
      "scriptId":"u36"},
    "04c80563ab434c22b9712cae7e9ab493":{
      "scriptId":"u37"},
    "bbc21edb345d43eaafb957e8f000d65e":{
      "scriptId":"u38"},
    "843dc1a76cd34000a481e5b9683059c3":{
      "scriptId":"u39"},
    "8db1b263be764ac688a5e70c294663f5":{
      "scriptId":"u40"},
    "f12cc94190dd4a3cb5e2fabfc16f9e9b":{
      "scriptId":"u41"},
    "c5bff3eecd1b474e8cf1c3ec19c1515e":{
      "scriptId":"u42"},
    "78d070eaf7f54492a746900c93a39fe1":{
      "scriptId":"u43"},
    "684461b3f4444108891bf089fef44ddf":{
      "scriptId":"u44"},
    "306d9820c9fb40339f42e642a3871734":{
      "scriptId":"u45"},
    "24ca72ccbbe542e090754fd5acbc1dc7":{
      "scriptId":"u46"},
    "29c66f115f424b73bb1e43acfb645957":{
      "scriptId":"u47"},
    "82366a4dd7d740f3927a1f764211e3c3":{
      "scriptId":"u48"},
    "7db5752ba3b54155ab5cf25e76e24183":{
      "scriptId":"u49"},
    "1ed5727b47b24ba182824818207bbbf3":{
      "scriptId":"u50"},
    "7100990c705646049d979ac8b3caba92":{
      "scriptId":"u51"},
    "63d113fc356140d7af1d65fc54179773":{
      "scriptId":"u52"},
    "0990cc29127147f7862aaaa4f2bb66d5":{
      "scriptId":"u53"},
    "bbc63fa25b284b16a9d6257b0751f3f6":{
      "scriptId":"u54"},
    "038fa61f42b647d290291a37216a27c8":{
      "scriptId":"u55"},
    "1f3b9fa24ca64e41babe128818357d94":{
      "scriptId":"u56"},
    "a4315f1b17da4bada7ac9e234a6b189e":{
      "scriptId":"u57"},
    "3010773183d64f0aac1e62007776ddb8":{
      "scriptId":"u58"},
    "d4b95574a2bc4213854cd578023dbb6d":{
      "scriptId":"u59"},
    "c714f9bd61bf4a409e101dd9b7bbdd41":{
      "scriptId":"u60"},
    "d8e9cbc4eff541c79409f8031c0990ea":{
      "scriptId":"u61"},
    "1dc2068bd93e41e88c2d27a1ff1c535d":{
      "scriptId":"u62"},
    "71aad76bd066415b86a17dc63669a230":{
      "scriptId":"u63"},
    "050f166afe854ca9bbe581fd13b69f31":{
      "scriptId":"u64"},
    "c166be164b53412ebdfbffac9c202c02":{
      "scriptId":"u65"},
    "6f3c54e6af2f423ba1e786df57b491bd":{
      "scriptId":"u66"},
    "59ae3baa34fa4f0f85a35f97a7407851":{
      "scriptId":"u67"},
    "7316b7776710445fadd537144ed0fdb2":{
      "scriptId":"u68"},
    "60744fc4b3244bdfbe1cfe811aafbbae":{
      "scriptId":"u69"},
    "2fb61b3145204a31a41907140bf9c44c":{
      "scriptId":"u70"},
    "aa80e6f9b48745f0b2fda120b8bec6c9":{
      "scriptId":"u71"},
    "d23b24a432ad48b1b99992293765a73a":{
      "scriptId":"u72"},
    "0f9078c2949547ba811242c6500b0296":{
      "scriptId":"u73"},
    "36802ee67d7f4a21b3058ffae80764ca":{
      "scriptId":"u74"},
    "d79371a705a14e79ac248c2a57ddc9e7":{
      "scriptId":"u75"},
    "5efd5598c74b44e88d784e1284a7a639":{
      "scriptId":"u76"},
    "f354e9be8f6e4cd2add113e058fb461f":{
      "scriptId":"u77"},
    "a2d722d7febf490dac99cfbb831f7d85":{
      "scriptId":"u78"},
    "801b59253b1e4b2d88f486750ebbcd90":{
      "scriptId":"u79"},
    "26d99a926fc044a9b7e9e97a3c52c03e":{
      "scriptId":"u80"},
    "5960b51bb2594894a844b6781aa8ea0e":{
      "scriptId":"u81"},
    "504af6bb6f8e4746be5bf2e57e3206aa":{
      "scriptId":"u82"},
    "e366c7e864c74c36bc7b368145f6dd7f":{
      "scriptId":"u83"},
    "97ea1e3c3e424aa9b5a1c9a5ab186ee9":{
      "scriptId":"u84"},
    "5d185c360afc4f7da0c84cf397d7b62f":{
      "scriptId":"u85"},
    "fe661a9f347342f58400d2fbcd2f5169":{
      "scriptId":"u86"}}});