$axure.loadCurrentPage({
  "url":"项目团购.html",
  "generationDate":new Date(1442542999806.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a70dbb3bbb74aca9e7995392c92b9f4",
    "type":"Axure:Page",
    "name":"项目团购",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"962dcd02a495491894f16cc3ccae179c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1c8e7bd5244759b1076d18234f5509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"ce42163ae14744a1899eb556613ae3f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32d5e25aceba4e05a4ac6e9fbb7a40cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"170cf7e9f61345e7946e22e5ccbfb002",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"2c005639846e4af4a0c065693c61da86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":388,
              "y":353},
            "size":{
              "width":33,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aea5c3c7670c4706aa60b19414c59352",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":388,
                  "y":353},
                "size":{
                  "width":33,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58feb9c011514cbd9ed3ae0b82de4059",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":508,
              "y":146},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d59611e5fd994cd2bc5762d56962756c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":508,
                  "y":146},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2530097e625d4bbc9ee28b3306725e25",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":589,
              "y":143},
            "size":{
              "width":121,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9c682162f87f40369a6f71a4103f41d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":148},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0861bf8d9314c94818a9356f1cc6ce5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":148},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae7125c4e5d241c0ac29a487b8a223af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":132},
            "size":{
              "width":202,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82175580f7548de97d365a2dee6dc65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":132},
                "size":{
                  "width":202,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u13.png"}},
{
          "id":"0de8569ffc5b42d0bfe6780f76fe80c9",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":143},
            "size":{
              "width":185,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c81c08eee3124b8c96621c7388c087bc",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":913,
              "y":143},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9ffd9ddd1f48403692252e48358426ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":459,
              "y":940},
            "size":{
              "width":221,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7b5310cc27474dba4a1323373a6db0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":459,
                  "y":940},
                "size":{
                  "width":221,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab846e480a2f4110a3511414bc8d853e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":124},
            "size":{
              "width":173,
              "height":736}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53566e20ef554846acf41d35b3ee6d13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":124},
                "size":{
                  "width":173,
                  "height":736}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u53.png"}},
{
          "id":"91d0091fbd284b069e3c83ba4b1be5bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba217a3ff77b4a64a8691cc7691dde92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的账户/u55.png"}},
{
          "id":"a293e889a3be467a9410ddda79decc99",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":59,
              "y":157},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44a60079fd364fa5b25e225d19dc3923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":157},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c14d43b45344ac395a70a180ca5928a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":365},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"9e874dafeec543d0b5b41187ddf022ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":383},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31da2ccfadaa4c08b0edcfd093047bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":383},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7b2cf729d38483fb81d213a55cd7c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":412},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48a2c8b913474c5bafe5c8ff07ae1845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":412},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02a51438ef9c4d14a48cc1a768d477b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":189},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d527cee11c8e4764be7f3647bbc232d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":189},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71f087068a21493989284953ee5c34e6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":522},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"b7692d0ab3324a0eb7ccd8c5952c47d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":439},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f67ed09e6c4935bd88a58d88905d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":439},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"718738625ccb4f3181ea8f841409fad7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":499},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228595af3ebf4a16bb558b81593a8ae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":499},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a704eba88fda4da7a835a671a1ecbe5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":537},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d05b01c0153b4ec08cd3b009a71eca47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":537},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d2305a0865b4c01b378d7977bc788c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":565},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9675f799066418c95f5d7837db5ad6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":565},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbbc7624109b4568a991c84c2becf2a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":594},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a646dd634eb14f6daf7ec190d93f56fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":594},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d12daa7a1fcd45c9a122d3e3eae880ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":623},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37dd805bca6b471e9ca8ee3272a25e35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":623},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f96cfb3c5e624ead898ff573581d1a02",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":468},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37a1f6a7306946f3956e2b3a77def536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":468},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4559d0093304251a517eccb7092e3e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":240},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a175de66686453389f2183fff4c5a7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":240},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"753487d8c5114246827f8186f050367b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":265},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1196b7ca3a074dc39509db1836f27b6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":265},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a187bf15729f408493b831fc9936ca92",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":290},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"88ac67acfe03458ea8a1ec121b02659b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":59,
              "y":308},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eb6e9c636c5425198d2defd6dad4f84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":308},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c661f51a7c640339680e81502b76a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":214},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf6603ede62409fa921bd2d76583e4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":214},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5926807210e4435aace94a98dd7968b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":337},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22b317b636b44d95ab883f9d540da49f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":337},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"051f4e6a87914a5580cd4d0fdf1975aa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":651},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"29081c424c0749379c677fd1ffdf8ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":666},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c7198e42e04efbbba938c353c1d51b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":666},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"282fbf478e3f4180a7ced7f39bde0426",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":694},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ac2b5392c814590aeeedffc2c5cab71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":694},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76872c3fcd404398baba428662c6c25e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":723},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2285d5065f804ca5bd782c34d43ff246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":723},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5911ade5e52c4b31a2f9678914c933da",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":752},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36acd497069146cf92eb62562a64b8b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":752},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90169a1416f6470b84839fd3b0585912",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":781},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9bf909c02e4e0eb1a03faffbab471f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":781},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51a54b0220f34ba7a99e99982fa1d12c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":809},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"799ea6a7b1e248dbaa1c7bee043e3e82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":809},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff837148faaa4fbfb817f0149ace5c69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238.5,
              "y":201},
            "size":{
              "width":317,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e97bdcfa7a3a4feb9af41f064795cabc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238.5,
                  "y":201},
                "size":{
                  "width":317,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目团购/u70.png"}},
{
          "id":"a3470da2b6a94d52bd114d925595a8bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":238,
              "y":412},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea0450bf82b84a68b661f6358826584c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":238,
                  "y":412},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cae3c18707d64dcdb385b35543d76036",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":240,
              "y":435},
            "size":{
              "width":215,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9e7d27aa37e4217a9a764a4813c8367",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":240,
                  "y":435},
                "size":{
                  "width":215,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfe339b667fb48f78510b20f4efde21a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":240,
              "y":458},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65e5093783ee4a7baa44c1238a13d027",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":458},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af77f180880d45b1971cd96d257d5297",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":342},
            "size":{
              "width":85,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"009c8d59015b4b518ebd0f0281e589d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":342},
                "size":{
                  "width":85,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目团购/u78.png"}},
{
          "id":"9176c42e48074f5bad346fabeedf0bed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":473,
              "y":353},
            "size":{
              "width":37,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8f7fe01ea504c6db9ec17db0652a2dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":473,
                  "y":353},
                "size":{
                  "width":37,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5650b7ad100f4e8eabf28e39c432d544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":374},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8fef030fe46411abb2fe73cc765c955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":374},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a70dc3df939f453c8969fa3cf4e390b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":477},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5392eabd72645e7ab0fe451badb58b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":477},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b3c9a7f497c4c779b9971822b3f8a52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":623,
              "y":201},
            "size":{
              "width":317,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"814a64ec008d4b9583914e20e4c06230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":623,
                  "y":201},
                "size":{
                  "width":317,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目团购/u70.png"}},
{
          "id":"f26ce166956c40cca6779fdf88fcb918",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":623,
              "y":412},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a66a242a70184618a6d05a2a5163e546",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":623,
                  "y":412},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bb5aff0e28844ca948258866c7581ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":625,
              "y":435},
            "size":{
              "width":215,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff7479579ad49359fbe63b7ee1d161f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":625,
                  "y":435},
                "size":{
                  "width":215,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4de84492d144a18afaa36f5fbb2a3fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":625,
              "y":458},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c434b107b17d4ceea4808da31200acc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":625,
                  "y":458},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12e07689347341618b8ed63959c9cddb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":855,
              "y":342},
            "size":{
              "width":85,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece4afcb88654a378b775ed34d3f66a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":855,
                  "y":342},
                "size":{
                  "width":85,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目团购/u78.png"}},
{
          "id":"b25141a892604ef7946f9d6a1bff6c3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":858,
              "y":353},
            "size":{
              "width":37,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda9f5f926454583afac06231a6b99dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":858,
                  "y":353},
                "size":{
                  "width":37,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d3c314b26bd4446b751bd91b1f8a678",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":896,
              "y":374},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e3d44f40e2f4f9cb4c656c2a9d19c01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":896,
                  "y":374},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4784c5927a6943138080b7202a96df84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":871,
              "y":477},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bc64c3fdb1c413a9400ec270a408255",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":871,
                  "y":477},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1657c7425185418aa05efe9d034290b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":510},
            "size":{
              "width":317,
              "height":201}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74eb0bd0ad4a4538bc7e1526004d5f42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":510},
                "size":{
                  "width":317,
                  "height":201}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目团购/u70.png"}},
{
          "id":"1c8db788784d475f9f4538de1a0077d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":238,
              "y":721},
            "size":{
              "width":197,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b71622213c484efa841edaf6236fdc5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":238,
                  "y":721},
                "size":{
                  "width":197,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c0f4020bfcb4bf6baad446cf1a862a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":240,
              "y":744},
            "size":{
              "width":215,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c9b978becb941949330032dfa21a2bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":240,
                  "y":744},
                "size":{
                  "width":215,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb07d30e67a14d90a98235762dcc99b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":240,
              "y":767},
            "size":{
              "width":127,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16febf84d96b416a8210f593574e93d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":767},
                "size":{
                  "width":127,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f99846b6c3af4f978b27f7882bd365c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":651},
            "size":{
              "width":85,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66dea4e2dcca4bc0860a9671ee6ca3fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":651},
                "size":{
                  "width":85,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目团购/u78.png"}},
{
          "id":"9ecc65cf1a564eec8fec602bcc7a3bf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":473,
              "y":662},
            "size":{
              "width":37,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffd5c132a9b843d5bd8aec8c4d2d018d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":473,
                  "y":662},
                "size":{
                  "width":37,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2795751077be4942b8bbd545a6b9275c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":683},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29f536838bba476cb024ccd24df74307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":683},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c283da0b7ae446d1becf1c470184e86f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":486,
              "y":786},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc68d45d8638404784b5177d9b4e2e41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":486,
                  "y":786},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b1296b4fd77437abc157174096f3b61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":918,
              "y":836},
            "size":{
              "width":103,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ee98f090d94b5781a5fc81e03d70cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":918,
                  "y":836},
                "size":{
                  "width":103,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的任务/u18.png"}},
{
          "id":"1d81175ba1b1469aadbb2a35685acee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":844},
            "size":{
              "width":86,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed6098aa435a4a0a846fc0ebed169ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":844},
                "size":{
                  "width":86,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "962dcd02a495491894f16cc3ccae179c":{
      "scriptId":"u0"},
    "2c1c8e7bd5244759b1076d18234f5509":{
      "scriptId":"u1"},
    "ce42163ae14744a1899eb556613ae3f0":{
      "scriptId":"u2"},
    "32d5e25aceba4e05a4ac6e9fbb7a40cb":{
      "scriptId":"u3"},
    "170cf7e9f61345e7946e22e5ccbfb002":{
      "scriptId":"u4"},
    "2c005639846e4af4a0c065693c61da86":{
      "scriptId":"u5"},
    "aea5c3c7670c4706aa60b19414c59352":{
      "scriptId":"u6"},
    "58feb9c011514cbd9ed3ae0b82de4059":{
      "scriptId":"u7"},
    "d59611e5fd994cd2bc5762d56962756c":{
      "scriptId":"u8"},
    "2530097e625d4bbc9ee28b3306725e25":{
      "scriptId":"u9"},
    "9c682162f87f40369a6f71a4103f41d5":{
      "scriptId":"u10"},
    "c0861bf8d9314c94818a9356f1cc6ce5":{
      "scriptId":"u11"},
    "ae7125c4e5d241c0ac29a487b8a223af":{
      "scriptId":"u12"},
    "f82175580f7548de97d365a2dee6dc65":{
      "scriptId":"u13"},
    "0de8569ffc5b42d0bfe6780f76fe80c9":{
      "scriptId":"u14"},
    "c81c08eee3124b8c96621c7388c087bc":{
      "scriptId":"u15"},
    "9ffd9ddd1f48403692252e48358426ec":{
      "scriptId":"u16"},
    "6c7b5310cc27474dba4a1323373a6db0":{
      "scriptId":"u17"},
    "ab846e480a2f4110a3511414bc8d853e":{
      "scriptId":"u18"},
    "53566e20ef554846acf41d35b3ee6d13":{
      "scriptId":"u19"},
    "91d0091fbd284b069e3c83ba4b1be5bc":{
      "scriptId":"u20"},
    "ba217a3ff77b4a64a8691cc7691dde92":{
      "scriptId":"u21"},
    "a293e889a3be467a9410ddda79decc99":{
      "scriptId":"u22"},
    "44a60079fd364fa5b25e225d19dc3923":{
      "scriptId":"u23"},
    "2c14d43b45344ac395a70a180ca5928a":{
      "scriptId":"u24"},
    "9e874dafeec543d0b5b41187ddf022ac":{
      "scriptId":"u25"},
    "31da2ccfadaa4c08b0edcfd093047bd8":{
      "scriptId":"u26"},
    "f7b2cf729d38483fb81d213a55cd7c66":{
      "scriptId":"u27"},
    "48a2c8b913474c5bafe5c8ff07ae1845":{
      "scriptId":"u28"},
    "02a51438ef9c4d14a48cc1a768d477b7":{
      "scriptId":"u29"},
    "d527cee11c8e4764be7f3647bbc232d7":{
      "scriptId":"u30"},
    "71f087068a21493989284953ee5c34e6":{
      "scriptId":"u31"},
    "b7692d0ab3324a0eb7ccd8c5952c47d0":{
      "scriptId":"u32"},
    "22f67ed09e6c4935bd88a58d88905d2f":{
      "scriptId":"u33"},
    "718738625ccb4f3181ea8f841409fad7":{
      "scriptId":"u34"},
    "228595af3ebf4a16bb558b81593a8ae0":{
      "scriptId":"u35"},
    "a704eba88fda4da7a835a671a1ecbe5a":{
      "scriptId":"u36"},
    "d05b01c0153b4ec08cd3b009a71eca47":{
      "scriptId":"u37"},
    "1d2305a0865b4c01b378d7977bc788c8":{
      "scriptId":"u38"},
    "f9675f799066418c95f5d7837db5ad6f":{
      "scriptId":"u39"},
    "bbbc7624109b4568a991c84c2becf2a0":{
      "scriptId":"u40"},
    "a646dd634eb14f6daf7ec190d93f56fb":{
      "scriptId":"u41"},
    "d12daa7a1fcd45c9a122d3e3eae880ec":{
      "scriptId":"u42"},
    "37dd805bca6b471e9ca8ee3272a25e35":{
      "scriptId":"u43"},
    "f96cfb3c5e624ead898ff573581d1a02":{
      "scriptId":"u44"},
    "37a1f6a7306946f3956e2b3a77def536":{
      "scriptId":"u45"},
    "d4559d0093304251a517eccb7092e3e9":{
      "scriptId":"u46"},
    "7a175de66686453389f2183fff4c5a7a":{
      "scriptId":"u47"},
    "753487d8c5114246827f8186f050367b":{
      "scriptId":"u48"},
    "1196b7ca3a074dc39509db1836f27b6a":{
      "scriptId":"u49"},
    "a187bf15729f408493b831fc9936ca92":{
      "scriptId":"u50"},
    "88ac67acfe03458ea8a1ec121b02659b":{
      "scriptId":"u51"},
    "8eb6e9c636c5425198d2defd6dad4f84":{
      "scriptId":"u52"},
    "4c661f51a7c640339680e81502b76a71":{
      "scriptId":"u53"},
    "6cf6603ede62409fa921bd2d76583e4f":{
      "scriptId":"u54"},
    "5926807210e4435aace94a98dd7968b5":{
      "scriptId":"u55"},
    "22b317b636b44d95ab883f9d540da49f":{
      "scriptId":"u56"},
    "051f4e6a87914a5580cd4d0fdf1975aa":{
      "scriptId":"u57"},
    "29081c424c0749379c677fd1ffdf8ed0":{
      "scriptId":"u58"},
    "38c7198e42e04efbbba938c353c1d51b":{
      "scriptId":"u59"},
    "282fbf478e3f4180a7ced7f39bde0426":{
      "scriptId":"u60"},
    "1ac2b5392c814590aeeedffc2c5cab71":{
      "scriptId":"u61"},
    "76872c3fcd404398baba428662c6c25e":{
      "scriptId":"u62"},
    "2285d5065f804ca5bd782c34d43ff246":{
      "scriptId":"u63"},
    "5911ade5e52c4b31a2f9678914c933da":{
      "scriptId":"u64"},
    "36acd497069146cf92eb62562a64b8b3":{
      "scriptId":"u65"},
    "90169a1416f6470b84839fd3b0585912":{
      "scriptId":"u66"},
    "4a9bf909c02e4e0eb1a03faffbab471f":{
      "scriptId":"u67"},
    "51a54b0220f34ba7a99e99982fa1d12c":{
      "scriptId":"u68"},
    "799ea6a7b1e248dbaa1c7bee043e3e82":{
      "scriptId":"u69"},
    "ff837148faaa4fbfb817f0149ace5c69":{
      "scriptId":"u70"},
    "e97bdcfa7a3a4feb9af41f064795cabc":{
      "scriptId":"u71"},
    "a3470da2b6a94d52bd114d925595a8bb":{
      "scriptId":"u72"},
    "ea0450bf82b84a68b661f6358826584c":{
      "scriptId":"u73"},
    "cae3c18707d64dcdb385b35543d76036":{
      "scriptId":"u74"},
    "d9e7d27aa37e4217a9a764a4813c8367":{
      "scriptId":"u75"},
    "dfe339b667fb48f78510b20f4efde21a":{
      "scriptId":"u76"},
    "65e5093783ee4a7baa44c1238a13d027":{
      "scriptId":"u77"},
    "af77f180880d45b1971cd96d257d5297":{
      "scriptId":"u78"},
    "009c8d59015b4b518ebd0f0281e589d6":{
      "scriptId":"u79"},
    "9176c42e48074f5bad346fabeedf0bed":{
      "scriptId":"u80"},
    "c8f7fe01ea504c6db9ec17db0652a2dd":{
      "scriptId":"u81"},
    "5650b7ad100f4e8eabf28e39c432d544":{
      "scriptId":"u82"},
    "a8fef030fe46411abb2fe73cc765c955":{
      "scriptId":"u83"},
    "a70dc3df939f453c8969fa3cf4e390b6":{
      "scriptId":"u84"},
    "c5392eabd72645e7ab0fe451badb58b3":{
      "scriptId":"u85"},
    "5b3c9a7f497c4c779b9971822b3f8a52":{
      "scriptId":"u86"},
    "814a64ec008d4b9583914e20e4c06230":{
      "scriptId":"u87"},
    "f26ce166956c40cca6779fdf88fcb918":{
      "scriptId":"u88"},
    "a66a242a70184618a6d05a2a5163e546":{
      "scriptId":"u89"},
    "5bb5aff0e28844ca948258866c7581ad":{
      "scriptId":"u90"},
    "3ff7479579ad49359fbe63b7ee1d161f":{
      "scriptId":"u91"},
    "a4de84492d144a18afaa36f5fbb2a3fd":{
      "scriptId":"u92"},
    "c434b107b17d4ceea4808da31200acc2":{
      "scriptId":"u93"},
    "12e07689347341618b8ed63959c9cddb":{
      "scriptId":"u94"},
    "ece4afcb88654a378b775ed34d3f66a2":{
      "scriptId":"u95"},
    "b25141a892604ef7946f9d6a1bff6c3d":{
      "scriptId":"u96"},
    "eda9f5f926454583afac06231a6b99dc":{
      "scriptId":"u97"},
    "8d3c314b26bd4446b751bd91b1f8a678":{
      "scriptId":"u98"},
    "3e3d44f40e2f4f9cb4c656c2a9d19c01":{
      "scriptId":"u99"},
    "4784c5927a6943138080b7202a96df84":{
      "scriptId":"u100"},
    "1bc64c3fdb1c413a9400ec270a408255":{
      "scriptId":"u101"},
    "1657c7425185418aa05efe9d034290b3":{
      "scriptId":"u102"},
    "74eb0bd0ad4a4538bc7e1526004d5f42":{
      "scriptId":"u103"},
    "1c8db788784d475f9f4538de1a0077d1":{
      "scriptId":"u104"},
    "b71622213c484efa841edaf6236fdc5a":{
      "scriptId":"u105"},
    "7c0f4020bfcb4bf6baad446cf1a862a2":{
      "scriptId":"u106"},
    "2c9b978becb941949330032dfa21a2bf":{
      "scriptId":"u107"},
    "bb07d30e67a14d90a98235762dcc99b8":{
      "scriptId":"u108"},
    "16febf84d96b416a8210f593574e93d3":{
      "scriptId":"u109"},
    "f99846b6c3af4f978b27f7882bd365c1":{
      "scriptId":"u110"},
    "66dea4e2dcca4bc0860a9671ee6ca3fa":{
      "scriptId":"u111"},
    "9ecc65cf1a564eec8fec602bcc7a3bf2":{
      "scriptId":"u112"},
    "ffd5c132a9b843d5bd8aec8c4d2d018d":{
      "scriptId":"u113"},
    "2795751077be4942b8bbd545a6b9275c":{
      "scriptId":"u114"},
    "29f536838bba476cb024ccd24df74307":{
      "scriptId":"u115"},
    "c283da0b7ae446d1becf1c470184e86f":{
      "scriptId":"u116"},
    "fc68d45d8638404784b5177d9b4e2e41":{
      "scriptId":"u117"},
    "0b1296b4fd77437abc157174096f3b61":{
      "scriptId":"u118"},
    "79ee98f090d94b5781a5fc81e03d70cb":{
      "scriptId":"u119"},
    "1d81175ba1b1469aadbb2a35685acee6":{
      "scriptId":"u120"},
    "ed6098aa435a4a0a846fc0ebed169ca6":{
      "scriptId":"u121"}}});