$axure.loadCurrentPage({
  "url":"发布需求.html",
  "generationDate":new Date(1442542995884.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"79e24a78d64947709f0bf97393c979ff",
    "type":"Axure:Page",
    "name":"发布需求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"85d0174f5ce449bcb9eaa957b924b772",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":180,
              "y":14},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"986890d5a94b42f1aed5446b0bc240e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":180,
                  "y":14},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0336519a066143ed86174a6d78322fb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":6},
            "size":{
              "width":120,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"421b920a27f24aa08d0dad847b15f95c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":6},
                "size":{
                  "width":120,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺详情页/u2.png"}},
{
          "id":"499bcf61fdb1476fbc4009e2a280bbfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":17},
            "size":{
              "width":294,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac84f106a55148f5b2e239d24f190d98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":17},
                "size":{
                  "width":294,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"483f208fe343463796167a027a1c88e2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":43},
            "size":{
              "width":1070,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商铺详情页/u6_line.png"}},
{
          "id":"993df3bf74a4466da69f9df197e20ddb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":974},
            "size":{
              "width":1050,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c62b0cacca12434a81d26df43c842af9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":974},
                "size":{
                  "width":1050,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商铺详情页/u49.png"}},
{
          "id":"caf031da061d4344980da5dec132540e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":416,
              "y":79},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"823da5beb2844d4f9ee2d6f59ebf1f89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":416,
                  "y":79},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc42647901fd4607825b0403720cf7c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":371,
              "y":127},
            "size":{
              "width":306,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1cc5adbe6e49bd905199f080028192",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":371,
                  "y":127},
                "size":{
                  "width":306,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a355064440884c368adaba195a2fd5ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":18,
              "y":200},
            "size":{
              "width":1062,
              "height":764},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fdc983a4fc7420fab9d021243b2ff27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":18,
                  "y":200},
                "size":{
                  "width":1062,
                  "height":764},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u13.png"}},
{
          "id":"33554127628b4eaa8c36fbc6e3232863",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":220},
            "size":{
              "width":334,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40d8ee8d6cef4ade9807941217e723c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":220},
                "size":{
                  "width":334,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u15.png"}},
{
          "id":"0e20a833fe7b4a2c9f673ed5a9440398",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":457,
              "y":222.5},
            "size":{
              "width":333,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ece9dea6b2d496597041da0a7ecaf65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":457,
                  "y":222.5},
                "size":{
                  "width":333,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u17.png"}},
{
          "id":"695b3a3fa65c4151a85a85b7f8ebecb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":281},
            "size":{
              "width":710,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"313f78ea383648b6b5ee1f1b68504bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":281},
                "size":{
                  "width":710,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u19.png"}},
{
          "id":"a6ae747b404b4500a39f8452273b6322",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":348},
            "size":{
              "width":337,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc163f4c7e4e4761b09d6425f2f9fcd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":348},
                "size":{
                  "width":337,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u21.png"}},
{
          "id":"993bb3f2482644bd838f42dd1649e36a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":467,
              "y":348},
            "size":{
              "width":333,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d682ca368a3439591cb9db939bdf536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":467,
                  "y":348},
                "size":{
                  "width":333,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u23.png"}},
{
          "id":"06c618bdd1324fe19c0cde33302ed26b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":420},
            "size":{
              "width":333,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67035f9435ce4eb59b8c1f31dfb46fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":420},
                "size":{
                  "width":333,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u25.png"}},
{
          "id":"c3622484564c403e9b7493797f5d0788",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":465,
              "y":421},
            "size":{
              "width":335,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f272bf076d8d43a68e83c2f2a8bfd572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":465,
                  "y":421},
                "size":{
                  "width":335,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u27.png"}},
{
          "id":"48bdfb058ff046ccaff046955c01aa8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":483},
            "size":{
              "width":708,
              "height":153}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d28dc4b2f4946a89299144e145c498c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":483},
                "size":{
                  "width":708,
                  "height":153}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u29.png"}},
{
          "id":"87b60726346e444aa86eb0b25da8e53d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":652},
            "size":{
              "width":346,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9454f94836314ac29ee34b34c6c6a0d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":652},
                "size":{
                  "width":346,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u31.png"}},
{
          "id":"9873eeb8d1d740b78582608cd6b42d1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":670},
            "size":{
              "width":200,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7efb7da91ad47baab79e38ee78678cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":670},
                "size":{
                  "width":200,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u33.png"}},
{
          "id":"92e64e42ebc841eb924514dacf0919ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":676},
            "size":{
              "width":92,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11ea003c81514bc9a26fcec56a69c850",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":676},
                "size":{
                  "width":92,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f75d43ced3fe46b69ce740b82b34673b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":730},
            "size":{
              "width":335,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33a2943f31c74c6abbd745fb369c191f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":730},
                "size":{
                  "width":335,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u37.png"}},
{
          "id":"15252a2fa86543bd8ce9989e688dc434",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":469,
              "y":730},
            "size":{
              "width":331,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea85fd5e7566472183251233a1c66ccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":469,
                  "y":730},
                "size":{
                  "width":331,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u39.png"}},
{
          "id":"ca9141fccc174080aa441cd5bc956d36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":78,
              "y":816},
            "size":{
              "width":428,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe1a670cb17f4b19b37ec431c3d23b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":78,
                  "y":816},
                "size":{
                  "width":428,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/发布需求/u41.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "85d0174f5ce449bcb9eaa957b924b772":{
      "scriptId":"u0"},
    "986890d5a94b42f1aed5446b0bc240e5":{
      "scriptId":"u1"},
    "0336519a066143ed86174a6d78322fb6":{
      "scriptId":"u2"},
    "421b920a27f24aa08d0dad847b15f95c":{
      "scriptId":"u3"},
    "499bcf61fdb1476fbc4009e2a280bbfb":{
      "scriptId":"u4"},
    "ac84f106a55148f5b2e239d24f190d98":{
      "scriptId":"u5"},
    "483f208fe343463796167a027a1c88e2":{
      "scriptId":"u6"},
    "993df3bf74a4466da69f9df197e20ddb":{
      "scriptId":"u7"},
    "c62b0cacca12434a81d26df43c842af9":{
      "scriptId":"u8"},
    "caf031da061d4344980da5dec132540e":{
      "scriptId":"u9"},
    "823da5beb2844d4f9ee2d6f59ebf1f89":{
      "scriptId":"u10"},
    "bc42647901fd4607825b0403720cf7c6":{
      "scriptId":"u11"},
    "2d1cc5adbe6e49bd905199f080028192":{
      "scriptId":"u12"},
    "a355064440884c368adaba195a2fd5ad":{
      "scriptId":"u13"},
    "6fdc983a4fc7420fab9d021243b2ff27":{
      "scriptId":"u14"},
    "33554127628b4eaa8c36fbc6e3232863":{
      "scriptId":"u15"},
    "40d8ee8d6cef4ade9807941217e723c5":{
      "scriptId":"u16"},
    "0e20a833fe7b4a2c9f673ed5a9440398":{
      "scriptId":"u17"},
    "7ece9dea6b2d496597041da0a7ecaf65":{
      "scriptId":"u18"},
    "695b3a3fa65c4151a85a85b7f8ebecb7":{
      "scriptId":"u19"},
    "313f78ea383648b6b5ee1f1b68504bd2":{
      "scriptId":"u20"},
    "a6ae747b404b4500a39f8452273b6322":{
      "scriptId":"u21"},
    "bc163f4c7e4e4761b09d6425f2f9fcd8":{
      "scriptId":"u22"},
    "993bb3f2482644bd838f42dd1649e36a":{
      "scriptId":"u23"},
    "9d682ca368a3439591cb9db939bdf536":{
      "scriptId":"u24"},
    "06c618bdd1324fe19c0cde33302ed26b":{
      "scriptId":"u25"},
    "67035f9435ce4eb59b8c1f31dfb46fd2":{
      "scriptId":"u26"},
    "c3622484564c403e9b7493797f5d0788":{
      "scriptId":"u27"},
    "f272bf076d8d43a68e83c2f2a8bfd572":{
      "scriptId":"u28"},
    "48bdfb058ff046ccaff046955c01aa8b":{
      "scriptId":"u29"},
    "7d28dc4b2f4946a89299144e145c498c":{
      "scriptId":"u30"},
    "87b60726346e444aa86eb0b25da8e53d":{
      "scriptId":"u31"},
    "9454f94836314ac29ee34b34c6c6a0d7":{
      "scriptId":"u32"},
    "9873eeb8d1d740b78582608cd6b42d1d":{
      "scriptId":"u33"},
    "c7efb7da91ad47baab79e38ee78678cd":{
      "scriptId":"u34"},
    "92e64e42ebc841eb924514dacf0919ba":{
      "scriptId":"u35"},
    "11ea003c81514bc9a26fcec56a69c850":{
      "scriptId":"u36"},
    "f75d43ced3fe46b69ce740b82b34673b":{
      "scriptId":"u37"},
    "33a2943f31c74c6abbd745fb369c191f":{
      "scriptId":"u38"},
    "15252a2fa86543bd8ce9989e688dc434":{
      "scriptId":"u39"},
    "ea85fd5e7566472183251233a1c66ccf":{
      "scriptId":"u40"},
    "ca9141fccc174080aa441cd5bc956d36":{
      "scriptId":"u41"},
    "fe1a670cb17f4b19b37ec431c3d23b85":{
      "scriptId":"u42"}}});