$axure.loadCurrentPage({
  "url":"开店网首页.html",
  "generationDate":new Date(1442542993811.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e8346dae18a94f22b840d4601071d9e0",
    "type":"Axure:Page",
    "name":"开店网首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2a9dbd042b394eae9686e0eb59230423",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1413,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a4b6eed4e334195adafb9cbc1d56642",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1413,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u0.png"}},
{
          "id":"423635c5611c45e593c271e3ba26ac0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":10},
            "size":{
              "width":440,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"529070cd1a114be7b84ca9a5dd35988b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":10},
                "size":{
                  "width":440,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u2.png"}},
{
          "id":"9e5ab1f766f64bcbb533aa43d399fc90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":310,
              "y":16},
            "size":{
              "width":313,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3834a4b226d045ca87eaae743c807704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":310,
                  "y":16},
                "size":{
                  "width":313,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b953bf7ef6a846009d01af98888d28ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-130,
              "y":64},
            "size":{
              "width":1416,
              "height":436}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94a4889cd8514650a9b7b2abe31dcc38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-130,
                  "y":64},
                "size":{
                  "width":1416,
                  "height":436}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u6.jpg"}},
{
          "id":"22660c87ccb04fffad94f42e4c212211",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":0,
              "y":187},
            "size":{
              "width":1286,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edb0397387f041669e70a20f4ecb1e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":0,
                  "y":187},
                "size":{
                  "width":1286,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u8.png"}},
{
          "id":"ef120627580b4950b1bb0e65e5a6616a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":500},
            "size":{
              "width":1286,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0ea9e047ba043be8200a4340ac4ff6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":500},
                "size":{
                  "width":1286,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u10.png"}},
{
          "id":"6919f2ead61349ff9d07d017e933fa3e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":517},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d0663918f74cab96043d2df51cdca1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":517},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u12.png"}},
{
          "id":"0007ffe67c3c43368cc1deadbf136466",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":140,
              "y":523},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f8cc6d67494a22be0aba9f8c16f2bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":140,
                  "y":523},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0549c06cd2c641b09616884d46c876c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":557},
            "size":{
              "width":107,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca90b9165eb4f9daaad577a12acef10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":557},
                "size":{
                  "width":107,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64fcfb859d524fca94a8e35b1900d12e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":516},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3ef491ca4864b2fb4a8d46bb223a926",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":516},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u12.png"}},
{
          "id":"1bbb1b608bc9473b855aefca654c78d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":419,
              "y":523},
            "size":{
              "width":114,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5fcbf85971e420389bda207b41c0741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":419,
                  "y":523},
                "size":{
                  "width":114,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdb68bae91494274ba96dba5451c50d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":419,
              "y":556},
            "size":{
              "width":131,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51e058c9e7974051b30d88e5882899ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":419,
                  "y":556},
                "size":{
                  "width":131,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a371fd9168d346b885a0d1ed2b516e94",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":598,
              "y":517},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6aa49ce0fb5f493e888c80816acf76c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":598,
                  "y":517},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u12.png"}},
{
          "id":"8d2f1bc3cb9c462cbe5d885603bed9b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":688,
              "y":524},
            "size":{
              "width":91,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9fa951f631b4ca4a6ec946a69b95651",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":688,
                  "y":524},
                "size":{
                  "width":91,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5450e2bc998b415fa5aa7274a867bfaf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":688,
              "y":552},
            "size":{
              "width":144,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18eaba2e20204cbeb0cd3684d3cf6f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":688,
                  "y":552},
                "size":{
                  "width":144,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5eccb07dafe94a4b9cff85156c1f948a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":899,
              "y":520},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd33e63791734c42bf0350688c980580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":899,
                  "y":520},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开店网首页/u12.png"}},
{
          "id":"92db9f930423474f9b1e49234fa114a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":989,
              "y":527},
            "size":{
              "width":119,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a9d5d1a54845aeb1a5d488616b320d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":989,
                  "y":527},
                "size":{
                  "width":119,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"429c37481f83467d9e95c5c79b4c99dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":989,
              "y":560},
            "size":{
              "width":157,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c7f1f25d8244796aa520c9bbf676827",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":989,
                  "y":560},
                "size":{
                  "width":157,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99e1f76d36444ed1aed55f26a13b4ee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":233,
              "y":263},
            "size":{
              "width":639,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3643b9acdf14408285bc8fa4e4e8618d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":233,
                  "y":263},
                "size":{
                  "width":639,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2a9dbd042b394eae9686e0eb59230423":{
      "scriptId":"u0"},
    "6a4b6eed4e334195adafb9cbc1d56642":{
      "scriptId":"u1"},
    "423635c5611c45e593c271e3ba26ac0c":{
      "scriptId":"u2"},
    "529070cd1a114be7b84ca9a5dd35988b":{
      "scriptId":"u3"},
    "9e5ab1f766f64bcbb533aa43d399fc90":{
      "scriptId":"u4"},
    "3834a4b226d045ca87eaae743c807704":{
      "scriptId":"u5"},
    "b953bf7ef6a846009d01af98888d28ae":{
      "scriptId":"u6"},
    "94a4889cd8514650a9b7b2abe31dcc38":{
      "scriptId":"u7"},
    "22660c87ccb04fffad94f42e4c212211":{
      "scriptId":"u8"},
    "edb0397387f041669e70a20f4ecb1e4e":{
      "scriptId":"u9"},
    "ef120627580b4950b1bb0e65e5a6616a":{
      "scriptId":"u10"},
    "b0ea9e047ba043be8200a4340ac4ff6b":{
      "scriptId":"u11"},
    "6919f2ead61349ff9d07d017e933fa3e":{
      "scriptId":"u12"},
    "50d0663918f74cab96043d2df51cdca1":{
      "scriptId":"u13"},
    "0007ffe67c3c43368cc1deadbf136466":{
      "scriptId":"u14"},
    "18f8cc6d67494a22be0aba9f8c16f2bf":{
      "scriptId":"u15"},
    "0549c06cd2c641b09616884d46c876c0":{
      "scriptId":"u16"},
    "3ca90b9165eb4f9daaad577a12acef10":{
      "scriptId":"u17"},
    "64fcfb859d524fca94a8e35b1900d12e":{
      "scriptId":"u18"},
    "b3ef491ca4864b2fb4a8d46bb223a926":{
      "scriptId":"u19"},
    "1bbb1b608bc9473b855aefca654c78d6":{
      "scriptId":"u20"},
    "e5fcbf85971e420389bda207b41c0741":{
      "scriptId":"u21"},
    "bdb68bae91494274ba96dba5451c50d6":{
      "scriptId":"u22"},
    "51e058c9e7974051b30d88e5882899ca":{
      "scriptId":"u23"},
    "a371fd9168d346b885a0d1ed2b516e94":{
      "scriptId":"u24"},
    "6aa49ce0fb5f493e888c80816acf76c0":{
      "scriptId":"u25"},
    "8d2f1bc3cb9c462cbe5d885603bed9b5":{
      "scriptId":"u26"},
    "d9fa951f631b4ca4a6ec946a69b95651":{
      "scriptId":"u27"},
    "5450e2bc998b415fa5aa7274a867bfaf":{
      "scriptId":"u28"},
    "18eaba2e20204cbeb0cd3684d3cf6f99":{
      "scriptId":"u29"},
    "5eccb07dafe94a4b9cff85156c1f948a":{
      "scriptId":"u30"},
    "bd33e63791734c42bf0350688c980580":{
      "scriptId":"u31"},
    "92db9f930423474f9b1e49234fa114a0":{
      "scriptId":"u32"},
    "01a9d5d1a54845aeb1a5d488616b320d":{
      "scriptId":"u33"},
    "429c37481f83467d9e95c5c79b4c99dc":{
      "scriptId":"u34"},
    "4c7f1f25d8244796aa520c9bbf676827":{
      "scriptId":"u35"},
    "99e1f76d36444ed1aed55f26a13b4ee2":{
      "scriptId":"u36"},
    "3643b9acdf14408285bc8fa4e4e8618d":{
      "scriptId":"u37"}}});