$axure.loadCurrentPage({
  "url":"商家中心首页.html",
  "generationDate":new Date(1442543002583.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ef9bd71beed049a29bccbd67909adbd8",
    "type":"Axure:Page",
    "name":"商家中心首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"80ccc3c553b84561ab04263c9f4299a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1100,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d528104d68b548b28a13a2f6387a1350",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1100,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u0.png"}},
{
          "id":"e3356c74242240309ed338b1be749c32",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":230,
              "y":103},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcf6de890c0b439bb6e34694b02e0ee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":230,
                  "y":103},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44bd651e0a4c4fd3b92191b3e0211692",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":125},
            "size":{
              "width":80,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u4_line.png"}},
{
          "id":"9f2bdde2a55546e58b0adbc26ea20177",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":159},
            "size":{
              "width":108,
              "height":106}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5fbf4d0288e4d808eab3ab03e469c28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":159},
                "size":{
                  "width":108,
                  "height":106}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u5.png"}},
{
          "id":"50e84c666f00481bbabda88939fd117e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":360,
              "y":196},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f09a19526a541149403e056e62e7534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":360,
                  "y":196},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e4b2ecff0d947de824174f5e404697f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":166},
            "size":{
              "width":230,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08328b636dc64e08a9ada6397f31972e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":166},
                "size":{
                  "width":230,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u9.png"}},
{
          "id":"fe8194e27795478a9a2d77374575be9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":236,
              "y":301},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74a2aff0cdb04715bdfad057f6c0ec3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":236,
                  "y":301},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5bd852ddb6a4bbca1e2d142c3bddb3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":509,
              "y":184},
            "size":{
              "width":114,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c205453213a44d48832d3a1442ef7d4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":509,
                  "y":184},
                "size":{
                  "width":114,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0d64a57d6604c9995ffe0390c904f57",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":168},
            "size":{
              "width":10,
              "height":88}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u15_line.png"}},
{
          "id":"edb339d591a04b01bcdf41c3298ef22e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":168},
            "size":{
              "width":10,
              "height":88}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u15_line.png"}},
{
          "id":"523e08f6a28642a7bd5f8c2b377245d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":230},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"236630f3a40e4dc68ee1308ab81053a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":751,
                  "y":230},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75a15c75e5dd4f99911d56ee75adf224",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":835,
              "y":230},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ff79213b5424278b44738df79278e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":835,
                  "y":230},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c50988cffaa24f71ba43c4db758dbad8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":230},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8424e5735114ddaa855de21415f38ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":230},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e9ff0bdc9a24b8991ab94e3faa7b498",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":339},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ecf5e9026548569b8b049b93f5b20f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":339},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u23.png"}},
{
          "id":"77e5e1dbd168474f87f1d8cf54cf0b80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":268,
              "y":344},
            "size":{
              "width":347,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16698770f445426fa945bc3923bad38e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":268,
                  "y":344},
                "size":{
                  "width":347,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"928021afe9a84620bf9446b8d0b99097",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":370},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e830b607fb2340c7b5200fa3de2fcbca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":370},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u23.png"}},
{
          "id":"044d58c4347b4d7fbdefaf4eeeb542a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":268,
              "y":375},
            "size":{
              "width":257,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6df51bda6e554b26b0985c8b372ed77b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":268,
                  "y":375},
                "size":{
                  "width":257,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d05c24c83894ba385d52cec64d66467",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":402},
            "size":{
              "width":20,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"558c80029fee414aa10198a6f2b24deb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":402},
                "size":{
                  "width":20,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员首页/u23.png"}},
{
          "id":"b49603ac5b0849259c33726acf25646c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":270,
              "y":407},
            "size":{
              "width":393,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ad266b855f44f93b61a15ae91a627d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":270,
                  "y":407},
                "size":{
                  "width":393,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"486282fec9444aec804df7f35d746e31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":120},
            "size":{
              "width":173,
              "height":610}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c98f845efc944a0d811a1d7e66db11f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":120},
                "size":{
                  "width":173,
                  "height":610}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u35.png"}},
{
          "id":"c5f967ba4ab5494381b125a9fa37fa31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":100},
            "size":{
              "width":150,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d555faaae93f4a76a8da54ebbe0dbaea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":100},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商家中心首页/u37.png"}},
{
          "id":"75c24440f3924159b3803df69a51126f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":59,
              "y":150},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dafecbc444134b79838894ea69af18d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":59,
                  "y":150},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"830c634c13304fba85416a61ea6adc5c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":268},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"4b0370028f60425f98084aafce9fad34",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":278},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1549b8e3fba4a5f9ebde2c6f73c8b84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":278},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d3d761070ea4ad2a2f555cf50fda437",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":306},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c97ccf7db279439d9ba9d6dd6103c3e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":306},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57a3183b1dca4ffe99b8acaa8a19fed2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":335},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68ae90e0c8134541adbeb5c1830cef2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":335},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de69fb4b3c8342ff908f010b11f8ae87",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":364},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84c74816944a45369cd9fdce81b63524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":364},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6eb209134c264a5a8458f2f8fa4bc09a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":393},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"fe35e81b754e4d9d8e5c2c8fc036cc4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":56,
              "y":411},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d07db69ae25648888361a8dff4f139b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":56,
                  "y":411},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cf38c7e00e9e49db9d00eff869dc7953",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":207},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa717c52e92b4fc89f6d04fc9715e0f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":207},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fd7a07111d54be69ee7fa9eaafa96de",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":440},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e645e7d44add4334b142178326e64c9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":440},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b29a3054a7cf4dd89da09643ce266be3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":61,
              "y":178},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e3c5809883b47388b4c768daa58cf03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":178},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fbb0a1696544bc1b1780b42588c4e20",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":554},
            "size":{
              "width":150,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/会员首页/u41_line.png"}},
{
          "id":"1b405a3ea5b04041aff40ad38091a76c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":467},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2163b55f7ea241c99d4933f080b26d61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":467},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bf98b28a4d54d8aa3ccfb05badcdfae",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":527},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8a41871ed74147b6095168de8221fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":527},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1bb60a0f434db89c300043fd3c4f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":58,
              "y":569},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cd00fa6ab444bc39e68223ccd407b21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":58,
                  "y":569},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcae6a5eef9c43dfa45fd0d97dde0332",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":56,
              "y":597},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbdea730a49a4b0b846b261ac6259b9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":56,
                  "y":597},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b5f78a62c9942cba6061eee7aeebb29",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":626},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb9a790ae1e7478d9acd2a9acea50073",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":626},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2d8bebc48a74c768afaa8136c367c5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":655},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0028e4a054a641cfb112ae46bf7dbe24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":655},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f6cf56140964c66a00715af4eb3520b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":684},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64caed65fdf043178add51966d2c881a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":684},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46d4880aa88745c786ea5ff15966ce26",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":58,
              "y":496},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5d48fc93314922b67af8260db773b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":58,
                  "y":496},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2fb8eba80524fb095b2cec8565cd3b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":61,
              "y":236},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"295735740240499190cd6db5cd1764e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":61,
                  "y":236},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "80ccc3c553b84561ab04263c9f4299a3":{
      "scriptId":"u0"},
    "d528104d68b548b28a13a2f6387a1350":{
      "scriptId":"u1"},
    "e3356c74242240309ed338b1be749c32":{
      "scriptId":"u2"},
    "bcf6de890c0b439bb6e34694b02e0ee2":{
      "scriptId":"u3"},
    "44bd651e0a4c4fd3b92191b3e0211692":{
      "scriptId":"u4"},
    "9f2bdde2a55546e58b0adbc26ea20177":{
      "scriptId":"u5"},
    "f5fbf4d0288e4d808eab3ab03e469c28":{
      "scriptId":"u6"},
    "50e84c666f00481bbabda88939fd117e":{
      "scriptId":"u7"},
    "9f09a19526a541149403e056e62e7534":{
      "scriptId":"u8"},
    "2e4b2ecff0d947de824174f5e404697f":{
      "scriptId":"u9"},
    "08328b636dc64e08a9ada6397f31972e":{
      "scriptId":"u10"},
    "fe8194e27795478a9a2d77374575be9a":{
      "scriptId":"u11"},
    "74a2aff0cdb04715bdfad057f6c0ec3b":{
      "scriptId":"u12"},
    "a5bd852ddb6a4bbca1e2d142c3bddb3c":{
      "scriptId":"u13"},
    "c205453213a44d48832d3a1442ef7d4e":{
      "scriptId":"u14"},
    "b0d64a57d6604c9995ffe0390c904f57":{
      "scriptId":"u15"},
    "edb339d591a04b01bcdf41c3298ef22e":{
      "scriptId":"u16"},
    "523e08f6a28642a7bd5f8c2b377245d7":{
      "scriptId":"u17"},
    "236630f3a40e4dc68ee1308ab81053a2":{
      "scriptId":"u18"},
    "75a15c75e5dd4f99911d56ee75adf224":{
      "scriptId":"u19"},
    "1ff79213b5424278b44738df79278e05":{
      "scriptId":"u20"},
    "c50988cffaa24f71ba43c4db758dbad8":{
      "scriptId":"u21"},
    "e8424e5735114ddaa855de21415f38ca":{
      "scriptId":"u22"},
    "7e9ff0bdc9a24b8991ab94e3faa7b498":{
      "scriptId":"u23"},
    "d5ecf5e9026548569b8b049b93f5b20f":{
      "scriptId":"u24"},
    "77e5e1dbd168474f87f1d8cf54cf0b80":{
      "scriptId":"u25"},
    "16698770f445426fa945bc3923bad38e":{
      "scriptId":"u26"},
    "928021afe9a84620bf9446b8d0b99097":{
      "scriptId":"u27"},
    "e830b607fb2340c7b5200fa3de2fcbca":{
      "scriptId":"u28"},
    "044d58c4347b4d7fbdefaf4eeeb542a9":{
      "scriptId":"u29"},
    "6df51bda6e554b26b0985c8b372ed77b":{
      "scriptId":"u30"},
    "8d05c24c83894ba385d52cec64d66467":{
      "scriptId":"u31"},
    "558c80029fee414aa10198a6f2b24deb":{
      "scriptId":"u32"},
    "b49603ac5b0849259c33726acf25646c":{
      "scriptId":"u33"},
    "2ad266b855f44f93b61a15ae91a627d8":{
      "scriptId":"u34"},
    "486282fec9444aec804df7f35d746e31":{
      "scriptId":"u35"},
    "c98f845efc944a0d811a1d7e66db11f1":{
      "scriptId":"u36"},
    "c5f967ba4ab5494381b125a9fa37fa31":{
      "scriptId":"u37"},
    "d555faaae93f4a76a8da54ebbe0dbaea":{
      "scriptId":"u38"},
    "75c24440f3924159b3803df69a51126f":{
      "scriptId":"u39"},
    "dafecbc444134b79838894ea69af18d3":{
      "scriptId":"u40"},
    "830c634c13304fba85416a61ea6adc5c":{
      "scriptId":"u41"},
    "4b0370028f60425f98084aafce9fad34":{
      "scriptId":"u42"},
    "a1549b8e3fba4a5f9ebde2c6f73c8b84":{
      "scriptId":"u43"},
    "4d3d761070ea4ad2a2f555cf50fda437":{
      "scriptId":"u44"},
    "c97ccf7db279439d9ba9d6dd6103c3e6":{
      "scriptId":"u45"},
    "57a3183b1dca4ffe99b8acaa8a19fed2":{
      "scriptId":"u46"},
    "68ae90e0c8134541adbeb5c1830cef2d":{
      "scriptId":"u47"},
    "de69fb4b3c8342ff908f010b11f8ae87":{
      "scriptId":"u48"},
    "84c74816944a45369cd9fdce81b63524":{
      "scriptId":"u49"},
    "6eb209134c264a5a8458f2f8fa4bc09a":{
      "scriptId":"u50"},
    "fe35e81b754e4d9d8e5c2c8fc036cc4c":{
      "scriptId":"u51"},
    "d07db69ae25648888361a8dff4f139b1":{
      "scriptId":"u52"},
    "cf38c7e00e9e49db9d00eff869dc7953":{
      "scriptId":"u53"},
    "aa717c52e92b4fc89f6d04fc9715e0f1":{
      "scriptId":"u54"},
    "0fd7a07111d54be69ee7fa9eaafa96de":{
      "scriptId":"u55"},
    "e645e7d44add4334b142178326e64c9c":{
      "scriptId":"u56"},
    "b29a3054a7cf4dd89da09643ce266be3":{
      "scriptId":"u57"},
    "2e3c5809883b47388b4c768daa58cf03":{
      "scriptId":"u58"},
    "7fbb0a1696544bc1b1780b42588c4e20":{
      "scriptId":"u59"},
    "1b405a3ea5b04041aff40ad38091a76c":{
      "scriptId":"u60"},
    "2163b55f7ea241c99d4933f080b26d61":{
      "scriptId":"u61"},
    "0bf98b28a4d54d8aa3ccfb05badcdfae":{
      "scriptId":"u62"},
    "bf8a41871ed74147b6095168de8221fd":{
      "scriptId":"u63"},
    "3e1bb60a0f434db89c300043fd3c4f1c":{
      "scriptId":"u64"},
    "6cd00fa6ab444bc39e68223ccd407b21":{
      "scriptId":"u65"},
    "dcae6a5eef9c43dfa45fd0d97dde0332":{
      "scriptId":"u66"},
    "dbdea730a49a4b0b846b261ac6259b9d":{
      "scriptId":"u67"},
    "4b5f78a62c9942cba6061eee7aeebb29":{
      "scriptId":"u68"},
    "fb9a790ae1e7478d9acd2a9acea50073":{
      "scriptId":"u69"},
    "a2d8bebc48a74c768afaa8136c367c5b":{
      "scriptId":"u70"},
    "0028e4a054a641cfb112ae46bf7dbe24":{
      "scriptId":"u71"},
    "7f6cf56140964c66a00715af4eb3520b":{
      "scriptId":"u72"},
    "64caed65fdf043178add51966d2c881a":{
      "scriptId":"u73"},
    "46d4880aa88745c786ea5ff15966ce26":{
      "scriptId":"u74"},
    "8c5d48fc93314922b67af8260db773b7":{
      "scriptId":"u75"},
    "c2fb8eba80524fb095b2cec8565cd3b1":{
      "scriptId":"u76"},
    "295735740240499190cd6db5cd1764e5":{
      "scriptId":"u77"}}});